// Auto-generated from Nation/Assets/Scenes/Startup.unity + Card.cs — all 69 cards.
window.NATION_CARDS = [
 {
  "id": 0,
  "name": "Coin",
  "age": 0,
  "ageName": "Basics",
  "color": "orange",
  "cost": 0,
  "isPerson": false,
  "isBuilding": false,
  "money": 1,
  "attack": 0,
  "happy": 0,
  "science": 0,
  "food": 0,
  "effect": "The starting coin card. +1 Coin.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Money1.png"
 },
 {
  "id": 1,
  "name": "Damage",
  "age": 0,
  "ageName": "Basics",
  "color": "orange",
  "cost": 0,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 1,
  "happy": 0,
  "science": 0,
  "food": 0,
  "effect": "The starting attack card. +1 Attack.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Attack1.png"
 },
 {
  "id": 2,
  "name": "Happiness",
  "age": 0,
  "ageName": "Basics",
  "color": "orange",
  "cost": 0,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 0,
  "happy": 1,
  "science": 0,
  "food": 0,
  "effect": "The starting happiness card. +1 Happiness.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Happy1.png"
 },
 {
  "id": 3,
  "name": "Science",
  "age": 0,
  "ageName": "Basics",
  "color": "orange",
  "cost": 0,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 0,
  "happy": 0,
  "science": 1,
  "food": 0,
  "effect": "The starting science card. +1 Science.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Science1.png"
 },
 {
  "id": 4,
  "name": "Food",
  "age": 0,
  "ageName": "Basics",
  "color": "orange",
  "cost": 0,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 0,
  "happy": 0,
  "science": 0,
  "food": 1,
  "effect": "The starting food card. +1 Food.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Food1.png"
 },
 {
  "id": 5,
  "name": "Assassin",
  "age": 1,
  "ageName": "Age I",
  "color": "yellow",
  "cost": 2,
  "isPerson": true,
  "isBuilding": false,
  "money": 1,
  "attack": 1,
  "happy": 0,
  "science": 0,
  "food": -1,
  "effect": "+1 Attack, +1 Coin, \u22121 Food. Rival discards a Person card.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Assassin.png"
 },
 {
  "id": 6,
  "name": "Migrate",
  "age": 1,
  "ageName": "Age I",
  "color": "yellow",
  "cost": 1,
  "isPerson": false,
  "isBuilding": false,
  "money": 1,
  "attack": 0,
  "happy": 0,
  "science": 0,
  "food": 1,
  "effect": "+1 Food, +1 Coin.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Migrate.png"
 },
 {
  "id": 7,
  "name": "Wiseman",
  "age": 1,
  "ageName": "Age I",
  "color": "yellow",
  "cost": 2,
  "isPerson": true,
  "isBuilding": false,
  "money": 1,
  "attack": 0,
  "happy": 0,
  "science": 1,
  "food": 0,
  "effect": "+1 Science, +1 Coin.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Wiseman.png"
 },
 {
  "id": 8,
  "name": "Chief",
  "age": 1,
  "ageName": "Age I",
  "color": "yellow",
  "cost": 3,
  "isPerson": true,
  "isBuilding": false,
  "money": 0,
  "attack": 3,
  "happy": 0,
  "science": 0,
  "food": -1,
  "effect": "+3 Attack, \u22121 Food, then make a choice.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Chief.png"
 },
 {
  "id": 9,
  "name": "Hunter",
  "age": 1,
  "ageName": "Age I",
  "color": "yellow",
  "cost": 2,
  "isPerson": true,
  "isBuilding": false,
  "money": 0,
  "attack": 1,
  "happy": 0,
  "science": 0,
  "food": 1,
  "effect": "+1 Attack, +1 Food.",
  "synergy": "Combo with Gatherer: +3 Attack & +3 Coins.",
  "special": false,
  "disabled": false,
  "img": "cards/Hunter.png"
 },
 {
  "id": 10,
  "name": "Gatherer",
  "age": 1,
  "ageName": "Age I",
  "color": "yellow",
  "cost": 2,
  "isPerson": true,
  "isBuilding": false,
  "money": 1,
  "attack": 0,
  "happy": 0,
  "science": 0,
  "food": 1,
  "effect": "+1 Food, +1 Coin.",
  "synergy": "Combo with Hunter: +3 Attack & +3 Coins.",
  "special": false,
  "disabled": false,
  "img": "cards/Gatherer.png"
 },
 {
  "id": 11,
  "name": "Hunting Party",
  "age": 1,
  "ageName": "Age I",
  "color": "yellow",
  "cost": 3,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 2,
  "happy": 0,
  "science": 0,
  "food": 2,
  "effect": "+2 Attack, +2 Food.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Hunting_Party.png"
 },
 {
  "id": 12,
  "name": "Warriors",
  "age": 1,
  "ageName": "Age I",
  "color": "yellow",
  "cost": 4,
  "isPerson": false,
  "isBuilding": false,
  "money": 2,
  "attack": 3,
  "happy": 0,
  "science": 0,
  "food": -2,
  "effect": "+3 Attack, +2 Coins, \u22122 Food.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Warriors.png"
 },
 {
  "id": 13,
  "name": "Hut",
  "age": 1,
  "ageName": "Age I",
  "color": "yellow",
  "cost": 3,
  "isPerson": false,
  "isBuilding": true,
  "money": 0,
  "attack": 0,
  "happy": 3,
  "science": 1,
  "food": 0,
  "effect": "+3 Happiness, +1 Science.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Hut.png"
 },
 {
  "id": 14,
  "name": "Meeting",
  "age": 1,
  "ageName": "Age I",
  "color": "yellow",
  "cost": 4,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 0,
  "happy": 1,
  "science": 2,
  "food": 0,
  "effect": "+1 Happiness, +2 Science.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Meeting.png"
 },
 {
  "id": 15,
  "name": "Dancing",
  "age": 1,
  "ageName": "Age I",
  "color": "yellow",
  "cost": 1,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 0,
  "happy": 2,
  "science": 0,
  "food": 0,
  "effect": "+2 Happiness.",
  "synergy": "Combo with Space Disco: +10 Happiness.",
  "special": false,
  "disabled": false,
  "img": "cards/Dancing.png"
 },
 {
  "id": 16,
  "name": "Cave",
  "age": 1,
  "ageName": "Age I",
  "color": "yellow",
  "cost": 1,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 1,
  "happy": 0,
  "science": 0,
  "food": 1,
  "effect": "+1 Attack, +1 Food.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Cave.png"
 },
 {
  "id": 17,
  "name": "Thief",
  "age": 1,
  "ageName": "Age I",
  "color": "yellow",
  "cost": 1,
  "isPerson": true,
  "isBuilding": false,
  "money": 1,
  "attack": 1,
  "happy": 0,
  "science": 0,
  "food": 0,
  "effect": "+1 Coin, +1 Attack. Rival loses 1 Food.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Thief.png"
 },
 {
  "id": 18,
  "name": "Architect",
  "age": 2,
  "ageName": "Age II",
  "color": "green",
  "cost": 3,
  "isPerson": true,
  "isBuilding": false,
  "money": 1,
  "attack": 0,
  "happy": 0,
  "science": 1,
  "food": -1,
  "effect": "+1 Coin, +1 Science, +1 Health, \u22121 Food.",
  "synergy": "Combo with Engineer: heal +4 more.",
  "special": false,
  "disabled": false,
  "img": "cards/Architect.png"
 },
 {
  "id": 19,
  "name": "Army",
  "age": 2,
  "ageName": "Age II",
  "color": "green",
  "cost": 5,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 6,
  "happy": 0,
  "science": 0,
  "food": -2,
  "effect": "+6 Attack, \u22122 Food.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Army.png"
 },
 {
  "id": 20,
  "name": "Baker",
  "age": 2,
  "ageName": "Age II",
  "color": "green",
  "cost": 3,
  "isPerson": true,
  "isBuilding": false,
  "money": 1,
  "attack": 0,
  "happy": 0,
  "science": 0,
  "food": 2,
  "effect": "+2 Food, +1 Coin.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Baker.png"
 },
 {
  "id": 21,
  "name": "Bard",
  "age": 2,
  "ageName": "Age II",
  "color": "green",
  "cost": 2,
  "isPerson": true,
  "isBuilding": false,
  "money": 1,
  "attack": 0,
  "happy": 3,
  "science": 0,
  "food": -1,
  "effect": "+3 Happiness, +1 Coin, \u22121 Food.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Bard.png"
 },
 {
  "id": 22,
  "name": "Declare War",
  "age": 2,
  "ageName": "Age II",
  "color": "green",
  "cost": 4,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 5,
  "happy": -1,
  "science": 0,
  "food": 0,
  "effect": "If you have Happiness: +5 Attack, \u22121 Happiness.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Declare_War.png"
 },
 {
  "id": 23,
  "name": "Farm",
  "age": 2,
  "ageName": "Age II",
  "color": "green",
  "cost": 4,
  "isPerson": false,
  "isBuilding": true,
  "money": 0,
  "attack": 3,
  "happy": 0,
  "science": 0,
  "food": 4,
  "effect": "Choose your reward.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Farm.png"
 },
 {
  "id": 24,
  "name": "Forum",
  "age": 2,
  "ageName": "Age II",
  "color": "green",
  "cost": 2,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 0,
  "happy": 0,
  "science": 1,
  "food": 0,
  "effect": "+1 Science. Permanently remove a card from your deck.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Forum.png"
 },
 {
  "id": 25,
  "name": "General",
  "age": 2,
  "ageName": "Age II",
  "color": "green",
  "cost": 5,
  "isPerson": true,
  "isBuilding": false,
  "money": 0,
  "attack": 4,
  "happy": 0,
  "science": 0,
  "food": -1,
  "effect": "+4 Attack, \u22121 Food, then make a choice.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/General.png"
 },
 {
  "id": 26,
  "name": "Market",
  "age": 2,
  "ageName": "Age II",
  "color": "green",
  "cost": 2,
  "isPerson": false,
  "isBuilding": true,
  "money": 0,
  "attack": 0,
  "happy": 1,
  "science": 0,
  "food": 1,
  "effect": "+1 Food, +1 Happiness. Buy a Person card for 1 less this turn.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Market.png"
 },
 {
  "id": 27,
  "name": "Philosopher",
  "age": 2,
  "ageName": "Age II",
  "color": "green",
  "cost": 2,
  "isPerson": true,
  "isBuilding": false,
  "money": 0,
  "attack": 0,
  "happy": 0,
  "science": 1,
  "food": -1,
  "effect": "\u22121 Food. +1 Science for each Person you've played this turn.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Philosopher.png"
 },
 {
  "id": 28,
  "name": "Potter",
  "age": 2,
  "ageName": "Age II",
  "color": "green",
  "cost": 3,
  "isPerson": true,
  "isBuilding": false,
  "money": 2,
  "attack": 0,
  "happy": 0,
  "science": 0,
  "food": 0,
  "effect": "+2 Coins.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Potter.png"
 },
 {
  "id": 29,
  "name": "Privateer",
  "age": 2,
  "ageName": "Age II",
  "color": "green",
  "cost": 4,
  "isPerson": true,
  "isBuilding": false,
  "money": 2,
  "attack": 2,
  "happy": 0,
  "science": 0,
  "food": -1,
  "effect": "+3 Attack, +2 Coins, \u22121 Food. Rival discards a card.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Privateer.png"
 },
 {
  "id": 30,
  "name": "Professor",
  "age": 2,
  "ageName": "Age II",
  "color": "green",
  "cost": 3,
  "isPerson": true,
  "isBuilding": false,
  "money": 0,
  "attack": 0,
  "happy": 0,
  "science": 2,
  "food": -1,
  "effect": "+2 Science, \u22121 Food. Your Person cards cost 2 less.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Professor.png"
 },
 {
  "id": 31,
  "name": "Shipyard",
  "age": 2,
  "ageName": "Age II",
  "color": "green",
  "cost": 5,
  "isPerson": false,
  "isBuilding": true,
  "money": 1,
  "attack": 1,
  "happy": 0,
  "science": 0,
  "food": 1,
  "effect": "+1 Coin, +1 Attack, +1 Food. Draw a card.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Shipyard.png"
 },
 {
  "id": 32,
  "name": "University",
  "age": 2,
  "ageName": "Age II",
  "color": "green",
  "cost": 5,
  "isPerson": false,
  "isBuilding": true,
  "money": 0,
  "attack": 0,
  "happy": 0,
  "science": 4,
  "food": 0,
  "effect": "+4 Science.",
  "synergy": "Combo with Professor: +1 Coin.",
  "special": false,
  "disabled": false,
  "img": "cards/University.png"
 },
 {
  "id": 33,
  "name": "Wall",
  "age": 2,
  "ageName": "Age II",
  "color": "green",
  "cost": 3,
  "isPerson": false,
  "isBuilding": true,
  "money": 0,
  "attack": 0,
  "happy": 0,
  "science": 0,
  "food": 0,
  "effect": "+1 Happiness. Stays in play and absorbs 3 damage.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Wall.png"
 },
 {
  "id": 34,
  "name": "Athlete",
  "age": 3,
  "ageName": "Age III",
  "color": "blue",
  "cost": 4,
  "isPerson": true,
  "isBuilding": false,
  "money": 0,
  "attack": 0,
  "happy": 1,
  "science": 0,
  "food": 0,
  "effect": "+2 Happiness, +3 Coins, \u22121 Food.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Athlete.png"
 },
 {
  "id": 35,
  "name": "Construction Crew",
  "age": 3,
  "ageName": "Age III",
  "color": "blue",
  "cost": 3,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 0,
  "happy": 0,
  "science": 0,
  "food": -2,
  "effect": "\u22122 Food. Your next building is free.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Construction_Crew.png"
 },
 {
  "id": 36,
  "name": "Demolition Crew",
  "age": 3,
  "ageName": "Age III",
  "color": "blue",
  "cost": 4,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 5,
  "happy": 0,
  "science": 0,
  "food": -2,
  "effect": "+5 Attack, \u22122 Food. Rival discards a Building.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Demolition_Crew.png"
 },
 {
  "id": 37,
  "name": "Doctor",
  "age": 3,
  "ageName": "Age III",
  "color": "blue",
  "cost": 4,
  "isPerson": true,
  "isBuilding": false,
  "money": 0,
  "attack": 0,
  "happy": 4,
  "science": 0,
  "food": -1,
  "effect": "+4 Happiness, \u22121 Food. Draw a Person card.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Doctor.png"
 },
 {
  "id": 38,
  "name": "Emergency Medical Team",
  "age": 3,
  "ageName": "Age III",
  "color": "blue",
  "cost": 4,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 0,
  "happy": 5,
  "science": 0,
  "food": -2,
  "effect": "+5 Happiness, \u22122 Food. Draw a card.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Emergency_Medical_Team.png"
 },
 {
  "id": 39,
  "name": "Engineer",
  "age": 3,
  "ageName": "Age III",
  "color": "blue",
  "cost": 4,
  "isPerson": true,
  "isBuilding": false,
  "money": 0,
  "attack": 3,
  "happy": 0,
  "science": 3,
  "food": -1,
  "effect": "+3 Attack, +3 Science, \u22121 Food.",
  "synergy": "Combo with Architect: heal +4 more.",
  "special": false,
  "disabled": false,
  "img": "cards/Engineer.png"
 },
 {
  "id": 40,
  "name": "Factory",
  "age": 3,
  "ageName": "Age III",
  "color": "blue",
  "cost": 5,
  "isPerson": false,
  "isBuilding": true,
  "money": 0,
  "attack": 4,
  "happy": -3,
  "science": 0,
  "food": 4,
  "effect": "+4 Attack, +4 Food, \u22123 Happiness.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Factory.png"
 },
 {
  "id": 41,
  "name": "International Summit",
  "age": 3,
  "ageName": "Age III",
  "color": "blue",
  "cost": 3,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 0,
  "happy": 0,
  "science": 2,
  "food": 0,
  "effect": "+2 Science. +2 more if you're behind in Age.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/International_Summit.png"
 },
 {
  "id": 42,
  "name": "King",
  "age": 3,
  "ageName": "Age III",
  "color": "blue",
  "cost": 5,
  "isPerson": true,
  "isBuilding": false,
  "money": 0,
  "attack": 0,
  "happy": 0,
  "science": 0,
  "food": -1,
  "effect": "\u22121 Food. Make a royal choice.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/King.png"
 },
 {
  "id": 43,
  "name": "Military Draft",
  "age": 3,
  "ageName": "Age III",
  "color": "blue",
  "cost": 5,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 7,
  "happy": -2,
  "science": 0,
  "food": 0,
  "effect": "+7 Attack, \u22122 Happiness.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Military_Draft.png"
 },
 {
  "id": 44,
  "name": "Navy",
  "age": 3,
  "ageName": "Age III",
  "color": "blue",
  "cost": 6,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 8,
  "happy": 0,
  "science": 0,
  "food": -2,
  "effect": "+8 Attack, \u22122 Food.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Navy.png"
 },
 {
  "id": 45,
  "name": "Printing Press",
  "age": 3,
  "ageName": "Age III",
  "color": "blue",
  "cost": 5,
  "isPerson": false,
  "isBuilding": true,
  "money": 2,
  "attack": 0,
  "happy": 1,
  "science": 2,
  "food": 0,
  "effect": "+2 Coins, +2 Science, +1 Happiness.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Printing_Press.png"
 },
 {
  "id": 46,
  "name": "Theater",
  "age": 3,
  "ageName": "Age III",
  "color": "blue",
  "cost": 3,
  "isPerson": false,
  "isBuilding": true,
  "money": 1,
  "attack": 0,
  "happy": 2,
  "science": 0,
  "food": 0,
  "effect": "+2 Happiness, +1 Coin.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Theater.png"
 },
 {
  "id": 47,
  "name": "Train Station",
  "age": 3,
  "ageName": "Age III",
  "color": "blue",
  "cost": 6,
  "isPerson": false,
  "isBuilding": true,
  "money": 2,
  "attack": 0,
  "happy": 0,
  "science": 0,
  "food": 2,
  "effect": "+2 Coins, +2 Food. Draw a card.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Train_Station.png"
 },
 {
  "id": 48,
  "name": "Air Force",
  "age": 4,
  "ageName": "Age IV",
  "color": "purple",
  "cost": 7,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 10,
  "happy": 0,
  "science": 0,
  "food": -2,
  "effect": "+10 Attack, \u22122 Food.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Air_Force.png"
 },
 {
  "id": 49,
  "name": "Airport",
  "age": 4,
  "ageName": "Age IV",
  "color": "purple",
  "cost": 7,
  "isPerson": false,
  "isBuilding": true,
  "money": 3,
  "attack": 0,
  "happy": 3,
  "science": 0,
  "food": 0,
  "effect": "+3 Coins, +3 Happiness. Draw a card.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Airport.png"
 },
 {
  "id": 50,
  "name": "CEO",
  "age": 4,
  "ageName": "Age IV",
  "color": "purple",
  "cost": 6,
  "isPerson": true,
  "isBuilding": false,
  "money": 6,
  "attack": 0,
  "happy": 0,
  "science": 0,
  "food": -1,
  "effect": "+6 Coins, \u22121 Food.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/CEO.png"
 },
 {
  "id": 51,
  "name": "Chemist",
  "age": 4,
  "ageName": "Age IV",
  "color": "purple",
  "cost": 5,
  "isPerson": true,
  "isBuilding": false,
  "money": 0,
  "attack": 4,
  "happy": 0,
  "science": 4,
  "food": -1,
  "effect": "+4 Attack, +4 Science, \u22121 Food.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Chemist.png"
 },
 {
  "id": 52,
  "name": "ICBM",
  "age": 4,
  "ageName": "Age IV",
  "color": "purple",
  "cost": 6,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 8,
  "happy": -2,
  "science": 0,
  "food": 0,
  "effect": "+8 Attack, \u22122 Happiness.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/ICBM.png"
 },
 {
  "id": 53,
  "name": "Investors",
  "age": 4,
  "ageName": "Age IV",
  "color": "purple",
  "cost": 3,
  "isPerson": true,
  "isBuilding": false,
  "money": 3,
  "attack": 0,
  "happy": 0,
  "science": 0,
  "food": -2,
  "effect": "+3 Coins, \u22122 Food. Make a choice.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Investors.png"
 },
 {
  "id": 54,
  "name": "National Holiday",
  "age": 4,
  "ageName": "Age IV",
  "color": "purple",
  "cost": 4,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 0,
  "happy": 4,
  "science": 0,
  "food": 2,
  "effect": "+4 Happiness, +2 Food.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/National_Holiday.png"
 },
 {
  "id": 55,
  "name": "Nuclear Warhead",
  "age": 4,
  "ageName": "Age IV",
  "color": "purple",
  "cost": 6,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 12,
  "happy": -7,
  "science": 0,
  "food": 0,
  "effect": "+12 Attack, \u22127 Happiness.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Nuclear_Warhead.png"
 },
 {
  "id": 56,
  "name": "President",
  "age": 4,
  "ageName": "Age IV",
  "color": "purple",
  "cost": 6,
  "isPerson": true,
  "isBuilding": false,
  "money": 0,
  "attack": 0,
  "happy": 0,
  "science": 0,
  "food": -1,
  "effect": "\u22121 Food. Make a presidential choice.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/President.png"
 },
 {
  "id": 57,
  "name": "Tank",
  "age": 4,
  "ageName": "Age IV",
  "color": "purple",
  "cost": 5,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 5,
  "happy": 0,
  "science": 0,
  "food": 0,
  "effect": "+5 Attack.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Tank.png"
 },
 {
  "id": 58,
  "name": "The Internet",
  "age": 4,
  "ageName": "Age IV",
  "color": "purple",
  "cost": 6,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 0,
  "happy": 3,
  "science": 1,
  "food": 0,
  "effect": "+3 Happiness, +1 Science. Draw a card.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/The_Internet.png"
 },
 {
  "id": 59,
  "name": "Giant Robot Of Death",
  "age": 5,
  "ageName": "Age V",
  "color": "red",
  "cost": 8,
  "isPerson": true,
  "isBuilding": true,
  "money": 0,
  "attack": 20,
  "happy": 0,
  "science": 0,
  "food": 0,
  "effect": "+20 Attack.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Giant_Robot_Of_Death.png"
 },
 {
  "id": 60,
  "name": "Mind Control",
  "age": 5,
  "ageName": "Age V",
  "color": "red",
  "cost": 12,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 999,
  "happy": 0,
  "science": 0,
  "food": 0,
  "effect": "Instantly win the game.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Mind_Control.png"
 },
 {
  "id": 61,
  "name": "Teleportation",
  "age": 5,
  "ageName": "Age V",
  "color": "red",
  "cost": 8,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 0,
  "happy": 0,
  "science": 0,
  "food": 0,
  "effect": "Draw a card, then swap a card from your discard pile with one from your rival's.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Teleportation.png"
 },
 {
  "id": 62,
  "name": "Time Machine",
  "age": 5,
  "ageName": "Age V",
  "color": "red",
  "cost": 8,
  "isPerson": false,
  "isBuilding": true,
  "money": 0,
  "attack": 0,
  "happy": 0,
  "science": 0,
  "food": 0,
  "effect": "Undo all the damage you took last turn.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/Time_Machine.png"
 },
 {
  "id": 63,
  "name": "War Satellite",
  "age": 5,
  "ageName": "Age V",
  "color": "red",
  "cost": 8,
  "isPerson": false,
  "isBuilding": true,
  "money": 0,
  "attack": 10,
  "happy": 0,
  "science": 0,
  "food": 0,
  "effect": "+10 Attack. Stays in play.",
  "synergy": null,
  "special": false,
  "disabled": false,
  "img": "cards/War_Satellite.png"
 },
 {
  "id": 64,
  "name": "Cannibalism",
  "age": 1,
  "ageName": "Age I",
  "color": "yellow",
  "cost": 1,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 0,
  "happy": 0,
  "science": 0,
  "food": 0,
  "effect": "+3 Food, \u22122 Happiness.",
  "synergy": null,
  "special": true,
  "disabled": false,
  "img": "cards/Cannibalism.png"
 },
 {
  "id": 65,
  "name": "Space Disco",
  "age": 5,
  "ageName": "Age V",
  "color": "red",
  "cost": 7,
  "isPerson": false,
  "isBuilding": true,
  "money": 0,
  "attack": 0,
  "happy": 0,
  "science": 0,
  "food": 0,
  "effect": "+10 Happiness.",
  "synergy": "Combo with Dancing: +10 Happiness.",
  "special": true,
  "disabled": false,
  "img": "cards/Space_Disco.png"
 },
 {
  "id": 66,
  "name": "Insta Food Inc",
  "age": 5,
  "ageName": "Age V",
  "color": "red",
  "cost": 8,
  "isPerson": false,
  "isBuilding": true,
  "money": 0,
  "attack": 0,
  "happy": 0,
  "science": 0,
  "food": 0,
  "effect": "+10 Food, plus 1 Food for every Science you have.",
  "synergy": null,
  "special": true,
  "disabled": false,
  "img": "cards/Insta_Food_Inc.png"
 },
 {
  "id": 67,
  "name": "Fire",
  "age": null,
  "ageName": "Special",
  "color": "fire",
  "cost": 1,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 0,
  "happy": 0,
  "science": 0,
  "food": 0,
  "effect": "1st play: \u221210 Health (ouch!). 2nd play: a free Age-up, then it burns out of your deck forever.",
  "synergy": null,
  "special": true,
  "disabled": true,
  "img": "cards/Fire.png"
 },
 {
  "id": 68,
  "name": "National Park",
  "age": 3,
  "ageName": "Age III",
  "color": "blue",
  "cost": 4,
  "isPerson": false,
  "isBuilding": false,
  "money": 0,
  "attack": 0,
  "happy": 0,
  "science": 0,
  "food": 0,
  "effect": "Choose: +3 Science or +5 Happiness.",
  "synergy": null,
  "special": false,
  "disabled": true,
  "img": "cards/National_Park.png"
 }
];
