'use strict';
/* ============================================================
   STARSPELL i18n — the strings table.
   Pick order: ?lang=xx → saved pref → browser language → en.
   ?lang also SAVES, so a player who follows a ?lang=es link
   stays in Spanish. Keys fall back to English per-string, so a
   partially translated language ships gracefully.
   Home screen is wired through SS_T(); battle/versus/profile
   strings migrate here incrementally.
   ============================================================ */
const SS_STR = {
  en: {
    rotate: 'turn your phone upright to play',
    title: 'STARSPELL',
    tagline: 'weave words · fell the star-beasts',
    campaign: 'CAMPAIGN',
    act1: 'ACT I · THE MEADOW SKY', act2: 'ACT II · THE DEEP NIGHT',
    act3: 'ACT III · THE CROWN OF DAWN', act4: 'ACT IV · THE ENDLESS HUNT',
    tBoss: 'BOSS', tElite: 'ELITE',
    cont: 'CONTINUE', fightN: 'fight %1 of 5',
    quick: 'QUICK PLAY',
    daily: 'DAILY HUNT', dailyOpen: 'one sky, shared by all · %1 left',
    dailyDone: 'today: %1 · next sky in %2', cdHM: '%1h %2m', cdH: '%1h', cdM: '%1m',
    board: 'LEADERBOARD', profile: 'PROFILE',
    versus: '⚔ VERSUS ⚔',
    endWin: 'THE SKY IS QUIET', endWinSub: 'every star-beast has fallen · the night is yours',
    endLose: 'THE STARS CLAIM YOU', endLoseSub: 'the ascent ends here',
    fanWin: 'VICTORY', fanCamp: 'CHAMPION OF THE SKY', fanVs: 'TRIUMPH',
    fanVsSub: '%1 is cast down', fanVsSubMany: 'every rival is cast down',
    stScore: 'score', stBest: 'best %1', newBest: '✦ NEW BEST ✦',
    endTomeTax: '◉ tome’s price · −%1%',
    tileFade: 'unspent · the shimmer fades',
    inkTele: '✦ the void drinks your letters ✦',
    inkHint: 'inked · worth nothing',
    stBeasts: 'beasts felled', stWords: 'words woven', stLetters: 'letters cast',
    stFinest: 'finest word', stBigHit: 'mightiest hit', stTime: 'run time', stSigils: 'sigils held',
    newRun: 'NEW RUN', tryAgain: 'TRY AGAIN', home: 'HOME',
    shareBtn: '✶ SHARE TODAY\'S HUNT', shareCopied: '✶ COPIED — GO BOAST', shareFail: '✶ COPY FAILED',
    shHead: 'STARSPELL Daily · %1', shScore: '%1 pts',
    shFinest: 'finest word: %1 tiles', shFinest1: 'finest word: 1 tile',
    shNoWord: 'no word cast', shStreak: '%1-night streak', shStreak1: 'night one',
    sigilHead: '— CHOOSE A SIGIL —', vsSigilHead: '— A SIGIL OFFERS ITSELF —',
    unlHead: 'SIGIL DISCOVERED',
    unlSkies: 'now appearing in your skies.',
    unlTap: 'tap to continue',
    slpHead: 'STILL SLEEPING',
    slpSub: '%1 sigils await discovery',
    slpSub1: 'one sigil awaits discovery',
    slpNone: 'the whole sky is yours',
    skiesTitle: 'YOUR SKIES',
    skiesNear: '%1 awake · %2 nearly there',
    rarityRare: 'RARE', rarityEpic: 'EPIC', rarityLegendary: 'LEGENDARY',
    upHead: '— STRENGTHEN A SIGIL —', upMax: 'AT ITS HEIGHT',
    inspTitle: 'YOUR POWERS', inspSub: 'tap outside to close', inspSign: 'BIRTH SIGN',
    cdMS: '%1m %2s', cdS: '%1s', cdD: '%1d', cdDH: '%1d %2h',
    lbTitle: 'THE NIGHT\'S FINEST', lbDaily: 'DAILY', lbWeekly: 'WEEKLY',
    lbNewSky: 'new sky in %1', lbWeekEnds: 'week ends in %1',
    lbLoading: 'consulting the stars…', lbEmpty: 'no hunts recorded yet — be the first',
    lbYou: 'YOU', lbYouRank: 'your place: #%1 of %2',
    lbLocal: 'local standings — the wider sky is unreachable',
    dpOneSky: 'one sky, shared by all', dpAwait: 'today\'s sky awaits you',
    dpPlayed: 'your hunt today: %1',
    stkLit: 'the lantern is lit', stkNight: 'night %1', stkKeep: 'keep the flame · %1',
    stkSheet: 'THE LANTERN', stkWeekHead: 'THE LAST SEVEN NIGHTS', stkLegend: '✓ hunted · ◌ grace night · ○ missed',
    stkCold: 'the lantern is dark', stkColdSub: 'tonight’s hunt lights it', stkBest: 'longest flame · %1',
    stkNextMark: 'next mark · night %1', stkGraceHeld: 'a grace night is held for you', stkGraceBridge: 'last night was missed · your grace night holds the flame',
    stkGraceSpent: 'grace night held — re-earned in %1 more hunts', stkGraceSpent1: 'grace night held — re-earned in 1 more hunt', stkGraced: 'a grace night held the flame',
    stkMsHead: 'THE LANTERN GROWS', stkMs7: 'SEVEN NIGHTS', stkMs30: 'THIRTY NIGHTS',
    stkMs100: 'ONE HUNDRED NIGHTS', stkMsSub7: 'an ember crowns the glass', stkMsSub30: 'the iron is gilded, and the light gets out',
    stkMsSub100: 'a comet keeps watch over your flame',
    dpPlay: 'BEGIN THE HUNT', dpAgain: 'HUNT AGAIN', dpTop: 'TODAY\'S FINEST',
    newCamp: 'NEW GAME',
    contCamp: 'CONTINUE GAME',
    // the endless climb (v0.68.0)
    endless: 'ENDLESS', endlessSub: 'how far can you climb?', hardLbl: 'HARD',
    endlessCont: 'level %1 · the climb holds', endlessBest: 'best · level %1',
    endlessTitle: 'THE ENDLESS SKY', endLvl: 'LEVEL %1', endLvlShort: 'L %1',
    endLvlReached: 'level reached', endBestLvl: 'best level %1',
    endEndTitle: 'THE CLIMB ENDS', endEndSub: 'the stars kept count · every rung is written',
    endAgain: 'CLIMB AGAIN', endContBtn: 'CONTINUE THE CLIMB', endNewBtn: 'BEGIN A NEW CLIMB',
    endStands: 'Your climb stands at level %1.',
    lbAllTime: 'the endless ledger · every climb remembered', lbHardTime: 'the ember ledger · every hard clear remembered',
    mapTitle: 'THE CAMPAIGN SKY', mapHint: 'tap the glowing constellation to enter the fight', mapDest: 'journey\'s end',
    restartTitle: 'RESTART YOUR GAME?', restartBody: 'This will restart your current game in progress.',
    restartBack: 'BACK', restartNew: 'NEW',
    zpTitle: 'CHOOSE YOUR SIGN', zpSub: 'born beneath one sky · each sign bends the climb',
    zpBegin: 'BEGIN THE CLIMB', zpSkip: 'walk unsigned · the classic climb',
    zpPurify: 'tap a tile to purify it', zShell: 'THE SHELL HOLDS',
    zpOpenName: 'THE OPEN SKY', zpOpenTitle: 'THE UNSIGNED CLIMB',
    zpOpenDesc: 'No sign, no power — the classic climb, as the first stars saw it.', zpRec: 'cleared ×%1 · best %2',
    svLevel: 'LEVEL %1', svLevelMax: 'LEVEL 50 · AT ITS HEIGHT', svHead: 'YOUR SIGN RISES',
    svReward: 'THE LEVEL BEARS A GIFT', svRwVessel: '+%1 starting health under this sign', svRwGilded: 'a gilded tile opens the climb',
    rating: 'star rating', rVeilRow: 'veil my rating from others', rVeiled: 'veiled', rShown: 'shown',
    rHiddenCard: 'veiled in starlight', rYourVeil: 'others see your rating veiled',
    rt0: 'STARDUST', rt1: 'EMBER STAR', rt2: 'RISING STAR', rt3: 'GILDED STAR',
    rt4: 'NOVA', rt5: 'SUPERNOVA', rt6: 'CELESTIAL CROWN',
    // friends · invites · summons (v0.25.0)
    vsAs: 'as %1', vsFriends: '— FRIENDS —', vsNoFriends: 'no friends yet — invite one below, or add a recent rival',
    vsOnline: 'online', vsOffline: 'offline', vsInDuel: '⚔ in a duel',
    vsSeen: 'seen %1 ago', vsChallenge: 'CHALLENGE', vsRecent: 'recent rivals',
    vsAdd: '+ ADD', vsRemove: 'remove', vsFriendLink: '✶ SHARE MY FRIEND LINK',
    vsMore: '+ %1 more', vsModeTurns: 'TURNS', vsModeTimed: 'TIMED',
    vsModeBg: 'BATTLEGROUND', vsTurnsSub: 'trade words blow for blow — no clock, no mercy', vsTimedSub: 'three minutes, both weaving at once',
    vsBgSub: 'two to four mages · every hit finds the leader', vsInvite: '⚔ INVITE A FRIEND', vsInviteSub: 'text them a link — one tap and you duel',
    vsFind: 'FIND A RIVAL', vsFindSub: 'quick match beneath the open sky', vsOrSeal: '— or answer a summons —',
    vsOrReach: '— or reach a mage yourself —', vsByName: 'BY NAME', vsNamePh: 'a mage’s name', vsNameSeek: 'seeking %1 among the stars…',
    vsNameNone: 'no mage bears the name %1 — check the spelling and try again', vsNameSelf: 'that is your own name — the stars will not set you against yourself', vsWaitAway: '%1 is away from the sky — your summons waits under their stars until they return', vsWaitBusy: '%1 is mid-duel — your summons waits for it to end',
    // recent rivals (v0.55.0, task 44)
    vsRecentHead: '— RECENT RIVALS —', vsNoRecent: 'no rivals yet — your first duel writes the first name here', vsAgoTonight: 'tonight', vsAgoLastNight: 'last night', vsAgoNights: '%1 nights ago', vsAgoLong: 'long ago', vsAgain: '⚔ AGAIN',
    vsSeal: 'ENTER A SEAL CODE', vsNoSky: 'the wider sky is unreachable —\nduels need a connection', vsConsult: 'consulting the stars…',
    vsRefused: 'the stars refused — try again', vsColdSeal: 'that seal answers to no one', vsSent: 'SUMMONS SENT TO %1',
    vsWaitAnswer: 'waiting for %1 to answer… the seal above works too', vsDeclined: '%1 declined the summons — share the seal, or challenge another', vsShareInvite: '✶ SHARE INVITE LINK',
    vsCopied: '✶ LINK COPIED — SEND IT', vsCopyFail: '✶ COPY FAILED — share the seal', vsShareText: '%1 summons you to a STARSPELL duel — tap to answer:',
    vsFriendText: 'add %1 as a STARSPELL friend:', lobbyTitle: 'THE SUMMONS IS SEALED', lobbySub: 'share the link — or your rival enters this seal under VERSUS',
    smTitle: '⚔ %1 challenges you', smAccept: 'ACCEPT', smMore: '+ %1 more summons',
    smJoining: 'answering the summons…', smCold: 'that seal has gone cold — the duel is over or full', frAdded: '✦ %1 is now your friend',
    frLinkTitle: 'a friend joins your sky', vsFriendsOn: '✦ %1 of your friends online', endAddFriend: '✦ ADD %1 AS A FRIEND',
    endFriends: '✦ FRIENDS ✦',
    vsLang: '⚔ this duel is woven in %1',
    nameTakenTitle: '✦ A NAME ALREADY WRITTEN ✦', nameTakenBody: 'the stars already know another %1 · from tonight you are %2',
    nameHeldTitle: '✦ THAT NAME IS SPOKEN FOR ✦', nameHeldBody: 'another stargazer already answers to %1 · you remain %2',
    // sigil names/descs come from data.js in English; other languages carry a `sig` map
    // zodiac titles/descs come from data.js in English; other languages carry a `zod` map
  },
  es: {
    rotate: 'gira el teléfono en vertical para jugar',
    title: 'STARSPELL',
    tagline: 'teje palabras · derriba a las bestias estelares',
    campaign: 'CAMPAÑA',
    act1: 'ACTO I · EL CIELO DEL PRADO', act2: 'ACTO II · LA NOCHE PROFUNDA',
    act3: 'ACTO III · LA CORONA DEL ALBA', act4: 'ACTO IV · LA CACERÍA SIN FIN',
    tBoss: 'JEFE', tElite: 'ÉLITE',
    beast: {
      vulpes: 'EL ZORRO DE ASCUAS', lepus: 'LA LIEBRE DE LUNA', serpens: 'LA SERPIENTE DE MAREA',
      delphinus: 'EL DELFÍN ESTELAR', columba: 'LA PALOMA HERALDO', lacerta: 'EL LAGARTO ZIGZAG',
      cygnus: 'EL CISNE DE LOS VIENTOS', pavo: 'EL PAVO REAL VELADO', cancer: 'EL CANGREJO SOMBRÍO',
      corvus: 'EL CUERVO HUECO', ursa: 'LA OSA DEL INVIERNO', aranea: 'LA VIUDA DE SEDA',
      aquila: 'EL ÁGUILA DEL TRUENO', lupus: 'EL LOBO HAMBRIENTO DE ESTRELLAS', monoceros: 'EL UNICORNIO DE CRISTAL',
      cassiopeia: 'LA REINA VANIDOSA', cetus: 'EL LEVIATÁN HUNDIDO', orion: 'EL CAZADOR DE LAS ESTRELLAS',
      strix: 'EL BÚHO DEL VACÍO', leo: 'EL LEÓN SOBERANO', taurus: 'EL TORO DE OJOS DE TORMENTA',
      scorpius: 'EL AGUIJÓN CARMESÍ', draco: 'EL DEVORAESTRELLAS', phoenix: 'LA PRIMERA LLAMA',
      centaurus: 'EL CENTAURO PRIMOGÉNITO', sagittarius: 'EL ARQUERO DEL CENIT',
    },
    cont: 'CONTINUAR', fightN: 'combate %1 de 5',
    quick: 'PARTIDA RÁPIDA',
    daily: 'CAZA DIARIA', dailyOpen: 'un mismo cielo para todos · quedan %1',
    dailyDone: 'hoy: %1 · nuevo cielo en %2', cdHM: '%1 h %2 min', cdH: '%1 h', cdM: '%1 min',
    board: 'CLASIFICACIÓN', profile: 'PERFIL',
    versus: '⚔ VERSUS ⚔',
    endWin: 'EL CIELO CALLA', endWinSub: 'todas las bestias estelares han caído · la noche es tuya',
    endLose: 'LAS ESTRELLAS TE RECLAMAN', endLoseSub: 'el ascenso termina aquí',
    fanWin: 'VICTORIA', fanCamp: 'CAMPEÓN DEL CIELO', fanVs: 'TRIUNFO',
    fanVsSub: '%1 ha caído', fanVsSubMany: 'todos los rivales han caído',
    stScore: 'puntos', stBest: 'récord %1', newBest: '✦ ¡NUEVO RÉCORD! ✦',
    endTomeTax: '◉ precio del tomo · −%1%',
    tileFade: 'sin usar · el brillo se apaga',
    inkTele: '✦ el vacío bebe tus letras ✦',
    inkHint: 'entintada · no vale nada',
    stBeasts: 'bestias derribadas', stWords: 'palabras tejidas', stLetters: 'letras lanzadas',
    stFinest: 'mejor palabra', stBigHit: 'golpe supremo', stTime: 'duración', stSigils: 'sigilos',
    newRun: 'NUEVA PARTIDA', tryAgain: 'REINTENTAR', home: 'INICIO',
    shareBtn: '✶ COMPARTIR LA CAZA', shareCopied: '✶ COPIADO — A PRESUMIR', shareFail: '✶ ERROR AL COPIAR',
    shHead: 'STARSPELL Caza diaria · %1', shScore: '%1 puntos',
    shFinest: 'mejor palabra: %1 fichas', shFinest1: 'mejor palabra: 1 ficha',
    shNoWord: 'sin palabra', shStreak: 'racha de %1 noches', shStreak1: 'primera noche',
    sigilHead: '— ELIGE UN SIGILO —', vsSigilHead: '— UN SIGILO SE OFRECE —',
    unlHead: 'SIGILO DESCUBIERTO',
    unlSkies: 'ya brilla en tus cielos.',
    unlTap: 'toca para continuar',
    slpHead: 'AÚN DORMIDOS',
    slpSub: '%1 sigilos por descubrir',
    slpSub1: 'un sigilo por descubrir',
    slpNone: 'todo el cielo es tuyo',
    skiesTitle: 'TUS CIELOS',
    skiesNear: '%1 despiertos · %2 a punto',
    rarityRare: 'RARO', rarityEpic: 'ÉPICO', rarityLegendary: 'LEGENDARIO',
    upHead: '— FORTALECE UN SIGILO —', upMax: 'EN SU CENIT',
    inspTitle: 'TUS PODERES', inspSub: 'toca fuera para cerrar', inspSign: 'SIGNO NATAL',
    cdMS: '%1 min %2 s', cdS: '%1 s', cdD: '%1 d', cdDH: '%1 d %2 h',
    lbTitle: 'LO MEJOR DE LA NOCHE', lbDaily: 'DIARIA', lbWeekly: 'SEMANAL',
    lbNewSky: 'nuevo cielo en %1', lbWeekEnds: 'la semana termina en %1',
    lbLoading: 'consultando a las estrellas…', lbEmpty: 'aún no hay cazas registradas — sé el primero',
    lbYou: 'TÚ', lbYouRank: 'tu puesto: #%1 de %2',
    lbLocal: 'clasificación local — el cielo ancho es inalcanzable',
    dpOneSky: 'un mismo cielo para todos', dpAwait: 'el cielo de hoy te espera',
    dpPlayed: 'tu caza de hoy: %1',
    stkLit: 'el farol está encendido', stkNight: 'noche %1', stkKeep: 'mantén la llama · %1',
    stkSheet: 'EL FAROL', stkWeekHead: 'LAS ÚLTIMAS SIETE NOCHES', stkLegend: '✓ cazada · ◌ noche de gracia · ○ perdida',
    stkCold: 'el farol está apagado', stkColdSub: 'la caza de esta noche lo enciende', stkBest: 'llama más larga · %1',
    stkNextMark: 'próxima marca · noche %1', stkGraceHeld: 'tienes una noche de gracia guardada', stkGraceBridge: 'anoche se perdió · tu noche de gracia sostiene la llama',
    stkGraceSpent: 'la noche de gracia sostuvo la llama — se recupera en %1 cazas más', stkGraceSpent1: 'la noche de gracia sostuvo la llama — se recupera en 1 caza más', stkGraced: 'una noche de gracia sostuvo la llama',
    stkMsHead: 'EL FAROL CRECE', stkMs7: 'SIETE NOCHES', stkMs30: 'TREINTA NOCHES',
    stkMs100: 'CIEN NOCHES', stkMsSub7: 'una brasa corona el cristal', stkMsSub30: 'el hierro se dora y la luz se escapa',
    stkMsSub100: 'un cometa vela por tu llama',
    dpPlay: 'COMENZAR LA CAZA', dpAgain: 'CAZAR DE NUEVO', dpTop: 'LO MEJOR DE HOY',
    newCamp: 'NUEVA PARTIDA',
    contCamp: 'CONTINUAR PARTIDA',
    endless: 'SIN FIN', endlessSub: '¿hasta dónde llegarás?', hardLbl: 'DIFÍCIL',
    endlessCont: 'nivel %1 · el ascenso aguarda', endlessBest: 'récord · nivel %1',
    endlessTitle: 'EL CIELO SIN FIN', endLvl: 'NIVEL %1', endLvlShort: 'NV %1',
    endLvlReached: 'nivel alcanzado', endBestLvl: 'mejor nivel %1',
    endEndTitle: 'EL ASCENSO TERMINA', endEndSub: 'las estrellas llevaron la cuenta · cada peldaño queda escrito',
    endAgain: 'ESCALAR DE NUEVO', endContBtn: 'CONTINUAR EL ASCENSO', endNewBtn: 'EMPEZAR OTRO ASCENSO',
    endStands: 'El ascenso aguarda en el nivel %1.',
    lbAllTime: 'el registro sin fin · cada ascenso queda guardado', lbHardTime: 'el registro de brasas · cada victoria difícil queda guardada',
    mapTitle: 'EL CIELO DE LA CAMPAÑA', mapHint: 'toca la constelación que brilla para entrar en combate', mapDest: 'fin del viaje',
    restartTitle: '¿REINICIAR TU PARTIDA?', restartBody: 'Esto reiniciará tu partida actual en curso.',
    restartBack: 'VOLVER', restartNew: 'NUEVA',
    zpTitle: 'ELIGE TU SIGNO', zpSub: 'nacido bajo un mismo cielo · cada signo dobla el ascenso',
    zpBegin: 'COMIENZA EL ASCENSO', zpSkip: 'subir sin signo · el ascenso clásico',
    zpPurify: 'toca una ficha para purificarla', zShell: 'EL CAPARAZÓN RESISTE',
    zpOpenName: 'EL CIELO ABIERTO', zpOpenTitle: 'EL ASCENSO SIN SIGNO',
    zpOpenDesc: 'Sin signo, sin poder — el ascenso clásico, como lo vieron las primeras estrellas.', zpRec: 'superado ×%1 · mejor %2',
    svLevel: 'NIVEL %1', svLevelMax: 'NIVEL 50 · EN SU CENIT', svHead: 'TU SIGNO ASCIENDE',
    svReward: 'EL NIVEL TRAE UN DON', svRwVessel: '+%1 de salud inicial bajo este signo', svRwGilded: 'una ficha dorada abre el ascenso',
    rating: 'clasificación estelar', rVeilRow: 'velar mi clasificación ante los demás', rVeiled: 'velada', rShown: 'visible',
    rHiddenCard: 'velada por la luz de las estrellas', rYourVeil: 'los demás ven tu clasificación velada',
    rt0: 'POLVO DE ESTRELLAS', rt1: 'ESTRELLA DE ASCUAS', rt2: 'ESTRELLA NACIENTE', rt3: 'ESTRELLA DORADA',
    rt4: 'NOVA', rt5: 'SUPERNOVA', rt6: 'CORONA CELESTE',
    // friends · invites · summons (v0.25.0)
    vsAs: 'como %1', vsFriends: '— AMIGOS —', vsNoFriends: 'aún no tienes amigos — invita a uno abajo o añade a un rival reciente',
    vsOnline: 'en línea', vsOffline: 'desconectado', vsInDuel: '⚔ en un duelo',
    vsSeen: 'visto hace %1', vsChallenge: 'RETAR', vsRecent: 'rivales recientes',
    vsAdd: '+ AÑADIR', vsRemove: 'quitar', vsFriendLink: '✶ COMPARTIR MI ENLACE DE AMISTAD',
    vsMore: '+ %1 más', vsModeTurns: 'TURNOS', vsModeTimed: 'CONTRARRELOJ',
    vsModeBg: 'CAMPO DE BATALLA', vsTurnsSub: 'palabra por palabra, golpe a golpe — sin reloj, sin piedad', vsTimedSub: 'tres minutos, los dos tejiendo a la vez',
    vsBgSub: 'de dos a cuatro magos · cada golpe busca al líder', vsInvite: '⚔ INVITAR A UN AMIGO', vsInviteSub: 'envíale un enlace — un toque y a duelo',
    vsFind: 'BUSCAR RIVAL', vsFindSub: 'partida rápida bajo el cielo abierto', vsOrSeal: '— o responde a una llamada —',
    vsOrReach: '— o busca tú a un mago —', vsByName: 'POR NOMBRE', vsNamePh: 'nombre de un mago', vsNameSeek: 'buscando a %1 entre las estrellas…',
    vsNameNone: 'ningún mago lleva el nombre %1 — revisa la ortografía e inténtalo de nuevo', vsNameSelf: 'ese es tu propio nombre — las estrellas no te enfrentarán contigo mismo', vsWaitAway: '%1 está lejos del cielo — tu llamada espera bajo sus estrellas hasta que vuelva', vsWaitBusy: '%1 está en pleno duelo — tu llamada espera a que termine',
    // recent rivals (v0.55.0, task 44)
    vsRecentHead: '— RIVALES RECIENTES —', vsNoRecent: 'aún sin rivales — tu primer duelo escribe aquí el primer nombre', vsAgoTonight: 'esta noche', vsAgoLastNight: 'anoche', vsAgoNights: 'hace %1 noches', vsAgoLong: 'hace mucho', vsAgain: '⚔ OTRA VEZ',
    vsSeal: 'INTRODUCIR UN SELLO', vsNoSky: 'el cielo ancho es inalcanzable —\nlos duelos necesitan conexión', vsConsult: 'consultando a las estrellas…',
    vsRefused: 'las estrellas se negaron — inténtalo de nuevo', vsColdSeal: 'ese sello no responde a nadie', vsSent: 'LLAMADA ENVIADA A %1',
    vsWaitAnswer: 'esperando la respuesta de %1… el sello de arriba también sirve', vsDeclined: '%1 rechazó la llamada — comparte el sello o reta a otro', vsShareInvite: '✶ COMPARTIR ENLACE',
    vsCopied: '✶ ENLACE COPIADO — ENVÍALO', vsCopyFail: '✶ ERROR AL COPIAR — comparte el sello', vsShareText: '%1 te reta a un duelo de STARSPELL — toca para responder:',
    vsFriendText: 'añade a %1 como amigo en STARSPELL:', lobbyTitle: 'LA LLAMADA ESTÁ SELLADA', lobbySub: 'comparte el enlace — o tu rival introduce este sello en VERSUS',
    smTitle: '⚔ %1 te reta', smAccept: 'ACEPTAR', smMore: '+ %1 llamadas más',
    smJoining: 'respondiendo a la llamada…', smCold: 'ese sello se ha enfriado — el duelo terminó o está lleno', frAdded: '✦ %1 ya es tu amigo',
    frLinkTitle: 'un amigo se une a tu cielo', vsFriendsOn: '✦ %1 de tus amigos en línea', endAddFriend: '✦ AÑADIR A %1 COMO AMIGO',
    endFriends: '✦ AMIGOS ✦',
    vsLang: '⚔ este duelo se teje en %1',
    nameTakenTitle: '✦ UN NOMBRE YA ESCRITO ✦', nameTakenBody: 'las estrellas ya conocen a otro %1 · desde esta noche eres %2',
    nameHeldTitle: '✦ ESE NOMBRE YA TIENE DUEÑO ✦', nameHeldBody: 'otro observador ya responde a %1 · sigues siendo %2',
    zod: {
      aries: ['EL CARNERO', 'Cada combate abre con una embestida: la bestia recibe %1.'],
      taurus: ['EL TORO', 'El toro resiste: +%1 de salud máxima al empezar el ascenso.'],
      gemini: ['LOS GEMELOS', 'Letras gemelas: las palabras que usan la misma letra dos veces hacen +%1.'],
      cancer: ['EL CANGREJO', 'El caparazón resiste: el primer golpe de cada combate hace un %1% menos.'],
      leo: ['EL LEÓN', 'El rugido: las palabras de 6+ letras hacen +%1.'],
      virgo: ['LA DONCELLA', 'Una vez por combate, toca tu signo y luego una ficha para purificarla en una letra nueva.',
        'Dos veces por combate, toca tu signo y luego una ficha para purificarla en una letra nueva.',
        'Tres veces por combate, toca tu signo y luego una ficha para purificarla en una letra nueva.'],
      libra: ['LA BALANZA', 'La balanza: las palabras con vocales y consonantes en equilibrio hacen +%1.'],
      scorpio: ['EL ESCORPIÓN', 'El veneno crece con cada palabra — la bestia sufre hasta %1 tras cada lance.',
        'El veneno crece al doble con cada palabra — la bestia sufre hasta %1 tras cada lance.'],
      sagittarius: ['EL ARQUERO', 'La flecha presta: SCRY también golpea a la bestia por %1.'],
      capricorn: ['LA CABRA MARINA', 'El ascenso: las palabras hacen +1 por cada dos bestias derribadas en la partida.',
        'El ascenso: las palabras hacen +1 por cada bestia derribada en la partida.',
        'El ascenso: las palabras hacen +2 por cada bestia derribada en la partida.'],
      aquarius: ['EL AGUADOR', 'Una vez por combate, caer bajo la mitad de salud vierte las aguas: cura %1.',
        'Dos veces por combate, caer bajo la mitad de salud vierte las aguas: cura %1.'],
      pisces: ['LOS PECES GEMELOS', 'La corriente profunda: las palabras tejidas a un lance del golpe hacen +%1%.'],
    },
    sig: {
      quill: ['PLUMA DE ASCUAS', 'Cada palabra inflige +%1 de daño.'],
      choir: ['CORO DE VOCALES', 'Cada vocal vale +%1.'],
      runes: ['RUNAS DEL RÍO', 'S, R, E y T valen +%1 cada una.'],
      salve: ['BÁLSAMO LUNAR', 'Las palabras de 5+ letras te curan %1.'],
      aegis: ['ÉGIDA DEL ALBA', '+%1 de salud máxima, curada al instante.'],
      first: ['PRIMERA LUZ', 'Tu primera palabra de cada combate hace el doble.', 'Tu primera palabra de cada combate hace el triple.'],
      hush: ['RELOJ SUSURRANTE', 'Las bestias golpean un lance más tarde.', 'Las bestias golpean dos lances más tarde.'],
      comet: ['ESTELA DE COMETA', 'Tu primer SCRY de cada combate no acelera el golpe.', 'Tus dos primeros SCRY de cada combate no aceleran el golpe.', 'Tus tres primeros SCRY de cada combate no aceleran el golpe.'],
      shield: ['ESCUDO DE PLATA', 'Bloquea el primer golpe de cada combate.', 'Bloquea los dos primeros golpes de cada combate.'],
      leech: ['BEBEDOR DE ROCÍO', 'Cada palabra te cura %1.'],
      longbow: ['ARCO ESTELAR', 'Las palabras de 6+ letras hacen +%1.'],
      gilded: ['ALBA DORADA', 'Cada combate empieza con una ficha dorada.', 'Cada combate empieza con dos fichas doradas.', 'Cada combate empieza con dos fichas estelares.'],
      forge: ['FORJA ESTELAR', 'Las fichas forjadas suben un nivel más.', 'Las fichas forjadas suben un nivel más, y las palabras de 4 letras forjan.'],
      blood: ['TINTA DE SANGRE', 'Tus palabras +%1%. Los golpes de las bestias +%2%.'],
      tome: ['TOMO SUSURRANTE', 'El ojo ◉ revela una palabra fuerte, una vez por combate. Precio del tomo: −25% de la puntuación final.', 'El ojo ◉ revela una palabra fuerte, dos veces por combate. Precio del tomo: −25% de la puntuación final.', 'El ojo ◉ revela una palabra fuerte, dos veces por combate. Precio del tomo: −15% de la puntuación final.'],
      storm: ['ATATORMENTAS', 'Cada tercera palabra golpea dos veces.', 'Cada segunda palabra golpea dos veces.'],
      roots: ['RAÍCES TELÚRICAS', 'Las palabras hacen +%1 por cada sigilo que tengas.'],
      ward: ['GUARDA LUNAR', 'Los golpes de las bestias hacen %1 menos, nunca menos de 1.'],
      echo: ['ECO DE RUINA', 'El daño sobrante hiere a la siguiente bestia.', 'El daño sobrante hiere a la siguiente bestia con la mitad más.', 'El daño sobrante hiere a la siguiente bestia al doble.'],
      feather: ['PLUMA DE FÉNIX', 'Una vez por partida, sobrevive a la muerte con %1 de salud.'],
      eclipse: ['EL ECLIPSE', 'Los golpes de las bestias hacen solo la mitad.', 'Los golpes de las bestias hacen solo un tercio.'],
      nova: ['CORONA DE NOVAS', 'Las palabras de %1+ letras hacen el doble.'],
      verse: ['EL VERSO SIN FIN', 'Las palabras hacen +%1 por cada palabra tejida en la partida.'],
      meteor: ['CORAZÓN DEL METEORO', 'Derribar una bestia te restaura toda la salud.', 'Derribar una bestia da +3 de salud máxima y te restaura del todo.'],
    },
    unl: {
      comet: 'Invoca SCRY %1 veces.',
      longbow: 'Teje %1 palabras de seis letras o más.',
      gilded: 'Forja %1 fichas con palabras largas.',
      forge: 'Teje %1 palabras de siete letras o más.',
      blood: 'Inflige %1 de daño con una sola palabra.',
      tome: 'Derriba %1 bestias estelares.',
      storm: 'Gana %1 cacerías.',
      echo: 'Derrama %1 de daño sobrante.',
      eclipse: 'Resiste %1 golpes de bestia.',
      nova: 'Teje una palabra de ocho letras.',
      verse: 'Teje %1 palabras en total.',
      meteor: 'Derriba %1 bestias con diez de salud o menos.',
    },
  },
  fr: {
    rotate: 'tourne ton téléphone à la verticale pour jouer',
    title: 'STARSPELL',
    tagline: 'tisse des mots · terrasse les bêtes stellaires',
    campaign: 'CAMPAGNE',
    act1: 'ACTE I · LE CIEL DU PRÉ', act2: 'ACTE II · LA NUIT PROFONDE',
    act3: 'ACTE III · LA COURONNE DE L\'AUBE', act4: 'ACTE IV · LA CHASSE SANS FIN',
    tBoss: 'BOSS', tElite: 'ÉLITE',
    beast: {
      vulpes: 'LE RENARD DE BRAISE', lepus: 'LE LIÈVRE DE LUNE', serpens: 'LE SERPENT DES MARÉES',
      delphinus: 'LE DAUPHIN ÉTOILÉ', columba: 'LA COLOMBE MESSAGÈRE', lacerta: 'LE LÉZARD ZIGZAG',
      cygnus: 'LE CYGNE DES VENTS', pavo: 'LE PAON VOILÉ', cancer: 'LE CRABE DES TÉNÈBRES',
      corvus: 'LE CORBEAU CREUX', ursa: 'L\'OURSE DE L\'HIVER', aranea: 'LA VEUVE DE SOIE',
      aquila: 'L\'AIGLE DU TONNERRE', lupus: 'LE LOUP AFFAMÉ D\'ÉTOILES', monoceros: 'LA LICORNE DE VERRE',
      cassiopeia: 'LA REINE VANITEUSE', cetus: 'LE LÉVIATHAN NOYÉ', orion: 'LE CHASSEUR DES ÉTOILES',
      strix: 'LE HIBOU DU VIDE', leo: 'LE LION SOUVERAIN', taurus: 'LE TAUREAU À L\'ŒIL D\'ORAGE',
      scorpius: 'LE DARD CRAMOISI', draco: 'LE DÉVOREUR D\'ÉTOILES', phoenix: 'LA PREMIÈRE FLAMME',
      centaurus: 'LE CENTAURE PREMIER-NÉ', sagittarius: 'L\'ARCHER DU ZÉNITH',
    },
    cont: 'CONTINUER', fightN: 'combat %1 sur 5',
    quick: 'PARTIE RAPIDE',
    daily: 'CHASSE DU JOUR', dailyOpen: 'un même ciel, partagé par tous · %1 restant',
    dailyDone: 'aujourd’hui : %1 · prochain ciel dans %2', cdHM: '%1 h %2 min', cdH: '%1 h', cdM: '%1 min',
    board: 'CLASSEMENT', profile: 'PROFIL',
    versus: '⚔ VERSUS ⚔',
    endWin: 'LE CIEL SE TAIT', endWinSub: 'toutes les bêtes stellaires sont tombées · la nuit est à toi',
    endLose: 'LES ÉTOILES TE RÉCLAMENT', endLoseSub: 'l’ascension s’arrête ici',
    fanWin: 'VICTOIRE', fanCamp: 'CHAMPION DU CIEL', fanVs: 'TRIOMPHE',
    fanVsSub: '%1 est terrassé', fanVsSubMany: 'tous les rivaux sont terrassés',
    stScore: 'score', stBest: 'record %1', newBest: '✦ NOUVEAU RECORD ! ✦',
    endTomeTax: '◉ prix du tome · −%1 %',
    tileFade: 'inutilisée · l’éclat s’éteint',
    inkTele: '✦ le vide boit vos lettres ✦',
    inkHint: 'encrée · ne vaut rien',
    stBeasts: 'bêtes terrassées', stWords: 'mots tissés', stLetters: 'lettres lancées',
    stFinest: 'plus beau mot', stBigHit: 'coup suprême', stTime: 'durée', stSigils: 'sceaux',
    newRun: 'NOUVELLE PARTIE', tryAgain: 'RÉESSAYER', home: 'ACCUEIL',
    shareBtn: '✶ PARTAGER LA CHASSE', shareCopied: '✶ COPIÉ — VA FRIMER', shareFail: '✶ ÉCHEC DE LA COPIE',
    shHead: 'STARSPELL Chasse du jour · %1', shScore: '%1 pts',
    shFinest: 'plus beau mot : %1 tuiles', shFinest1: 'plus beau mot : 1 tuile',
    shNoWord: 'aucun mot lancé', shStreak: 'série de %1 nuits', shStreak1: 'première nuit',
    sigilHead: '— CHOISIS UN SCEAU —', vsSigilHead: '— UN SCEAU S’OFFRE À TOI —',
    unlHead: 'SCEAU DÉCOUVERT',
    unlSkies: 'il brille désormais dans tes cieux.',
    unlTap: 'touche pour continuer',
    slpHead: 'ENCORE ENDORMIS',
    slpSub: '%1 sceaux à découvrir',
    slpSub1: 'un sceau à découvrir',
    slpNone: 'le ciel entier est à toi',
    skiesTitle: 'TES CIEUX',
    skiesNear: '%1 éveillés · %2 presque là',
    rarityRare: 'RARE', rarityEpic: 'ÉPIQUE', rarityLegendary: 'LÉGENDAIRE',
    upHead: '— RENFORCE UN SCEAU —', upMax: 'À SON APOGÉE',
    inspTitle: 'TES POUVOIRS', inspSub: 'touche en dehors pour fermer', inspSign: 'SIGNE NATAL',
    cdMS: '%1 min %2 s', cdS: '%1 s', cdD: '%1 j', cdDH: '%1 j %2 h',
    lbTitle: 'LE MEILLEUR DE LA NUIT', lbDaily: 'DU JOUR', lbWeekly: 'SEMAINE',
    lbNewSky: 'nouveau ciel dans %1', lbWeekEnds: 'la semaine s’achève dans %1',
    lbLoading: 'on consulte les étoiles…', lbEmpty: 'aucune chasse enregistrée — sois le premier',
    lbYou: 'TOI', lbYouRank: 'ta place : #%1 sur %2',
    lbLocal: 'classement local — le grand ciel est hors de portée',
    dpOneSky: 'un même ciel, partagé par tous', dpAwait: 'le ciel du jour t’attend',
    dpPlayed: 'ta chasse du jour : %1',
    stkLit: 'la lanterne est allumée', stkNight: 'nuit %1', stkKeep: 'garde la flamme · %1',
    stkSheet: 'LA LANTERNE', stkWeekHead: 'LES SEPT DERNIÈRES NUITS', stkLegend: '✓ chassée · ◌ nuit de grâce · ○ manquée',
    stkCold: 'la lanterne est éteinte', stkColdSub: 'la chasse de ce soir l’allume', stkBest: 'plus longue flamme · %1',
    stkNextMark: 'prochain jalon · nuit %1', stkGraceHeld: 'une nuit de grâce vous est réservée', stkGraceBridge: 'la nuit dernière a été manquée · votre nuit de grâce tient la flamme',
    stkGraceSpent: 'la nuit de grâce a tenu la flamme — regagnée dans %1 chasses', stkGraceSpent1: 'la nuit de grâce a tenu la flamme — regagnée dans 1 chasse', stkGraced: 'une nuit de grâce a tenu la flamme',
    stkMsHead: 'LA LANTERNE GRANDIT', stkMs7: 'SEPT NUITS', stkMs30: 'TRENTE NUITS',
    stkMs100: 'CENT NUITS', stkMsSub7: 'une braise couronne le verre', stkMsSub30: 'le fer est doré, et la lumière s’échappe',
    stkMsSub100: 'une comète veille sur ta flamme',
    dpPlay: 'LANCER LA CHASSE', dpAgain: 'CHASSER ENCORE', dpTop: 'LES MEILLEURS DU JOUR',
    newCamp: 'NOUVELLE PARTIE',
    contCamp: 'CONTINUER LA PARTIE',
    endless: 'SANS FIN', endlessSub: 'jusqu\'où grimperas-tu ?', hardLbl: 'DIFFICILE',
    endlessCont: 'niveau %1 · l\'ascension t\'attend', endlessBest: 'record · niveau %1',
    endlessTitle: 'LE CIEL SANS FIN', endLvl: 'NIVEAU %1', endLvlShort: 'NIV %1',
    endLvlReached: 'niveau atteint', endBestLvl: 'meilleur niveau %1',
    endEndTitle: 'L\'ASCENSION S\'ACHÈVE', endEndSub: 'les étoiles ont tenu le compte · chaque échelon est écrit',
    endAgain: 'GRIMPER ENCORE', endContBtn: 'CONTINUER L\'ASCENSION', endNewBtn: 'NOUVELLE ASCENSION',
    endStands: 'L\'ascension t\'attend au niveau %1.',
    lbAllTime: 'le registre sans fin · chaque ascension retenue', lbHardTime: 'le registre de braise · chaque victoire difficile retenue',
    mapTitle: 'LE CIEL DE LA CAMPAGNE', mapHint: 'touchez la constellation qui brille pour entrer au combat', mapDest: 'fin du voyage',
    restartTitle: 'RECOMMENCER VOTRE PARTIE ?', restartBody: 'Votre partie en cours sera recommencée depuis le début.',
    restartBack: 'RETOUR', restartNew: 'NOUVELLE',
    zpTitle: 'CHOISIS TON SIGNE', zpSub: 'nés sous un même ciel · chaque signe infléchit l\'ascension',
    zpBegin: 'COMMENCER L\'ASCENSION', zpSkip: 'grimper sans signe · l\'ascension classique',
    zpPurify: 'touche une tuile pour la purifier', zShell: 'LA CARAPACE TIENT',
    zpOpenName: 'LE CIEL OUVERT', zpOpenTitle: 'L\'ASCENSION SANS SIGNE',
    zpOpenDesc: 'Sans signe, sans pouvoir — l\'ascension classique, telle que les premières étoiles l\'ont vue.', zpRec: 'réussi ×%1 · record %2',
    svLevel: 'NIVEAU %1', svLevelMax: 'NIVEAU 50 · À SON APOGÉE', svHead: 'TON SIGNE S\'ÉLÈVE',
    svReward: 'LE NIVEAU PORTE UN DON', svRwVessel: '+%1 de santé de départ sous ce signe', svRwGilded: 'une tuile dorée ouvre l\'ascension',
    rating: 'cote stellaire', rVeilRow: 'voiler ma cote aux autres', rVeiled: 'voilée', rShown: 'visible',
    rHiddenCard: 'voilée dans la lumière des étoiles', rYourVeil: 'les autres voient ta cote voilée',
    rt0: 'POUSSIÈRE D\'ÉTOILES', rt1: 'ÉTOILE DE BRAISE', rt2: 'ÉTOILE MONTANTE', rt3: 'ÉTOILE DORÉE',
    rt4: 'NOVA', rt5: 'SUPERNOVA', rt6: 'COURONNE CÉLESTE',
    // friends · invites · summons (v0.25.0)
    vsAs: 'en tant que %1', vsFriends: '— AMIS —', vsNoFriends: 'pas encore d\'amis — invitez-en un ci-dessous, ou ajoutez un rival récent',
    vsOnline: 'en ligne', vsOffline: 'hors ligne', vsInDuel: '⚔ en duel',
    vsSeen: 'vu il y a %1', vsChallenge: 'DÉFIER', vsRecent: 'rivaux récents',
    vsAdd: '+ AJOUTER', vsRemove: 'retirer', vsFriendLink: '✶ PARTAGER MON LIEN D\'AMI',
    vsMore: '+ %1 autres', vsModeTurns: 'TOURS', vsModeTimed: 'CHRONO',
    vsModeBg: 'CHAMP DE BATAILLE', vsTurnsSub: 'mot pour mot, coup pour coup — sans horloge, sans pitié', vsTimedSub: 'trois minutes, tous deux tissant à la fois',
    vsBgSub: 'deux à quatre mages · chaque coup frappe le meneur', vsInvite: '⚔ INVITER UN AMI', vsInviteSub: 'envoyez-lui un lien — un geste et le duel commence',
    vsFind: 'TROUVER UN RIVAL', vsFindSub: 'partie rapide sous le ciel ouvert', vsOrSeal: '— ou répondez à un appel —',
    vsOrReach: '— ou cherchez un mage vous-même —', vsByName: 'PAR NOM', vsNamePh: 'le nom d’un mage', vsNameSeek: 'recherche de %1 parmi les étoiles…',
    vsNameNone: 'aucun mage ne porte le nom %1 — vérifiez l’orthographe et réessayez', vsNameSelf: 'c’est votre propre nom — les étoiles ne vous opposeront pas à vous-même', vsWaitAway: '%1 est loin du ciel — votre appel attend sous ses étoiles jusqu’à son retour', vsWaitBusy: '%1 est en plein duel — votre appel attend qu’il s’achève',
    // recent rivals (v0.55.0, task 44)
    vsRecentHead: '— RIVAUX RÉCENTS —', vsNoRecent: 'pas encore de rivaux — ton premier duel écrira le premier nom ici', vsAgoTonight: 'ce soir', vsAgoLastNight: 'hier soir', vsAgoNights: 'il y a %1 nuits', vsAgoLong: 'il y a longtemps', vsAgain: '⚔ ENCORE',
    vsSeal: 'SAISIR UN SCEAU', vsNoSky: 'le grand ciel est hors d\'atteinte —\nles duels ont besoin d\'une connexion', vsConsult: 'consultation des étoiles…',
    vsRefused: 'les étoiles ont refusé — réessayez', vsColdSeal: 'ce sceau ne répond à personne', vsSent: 'APPEL ENVOYÉ À %1',
    vsWaitAnswer: 'en attente de la réponse de %1… le sceau ci-dessus marche aussi', vsDeclined: '%1 a décliné l\'appel — partagez le sceau, ou défiez quelqu\'un d\'autre', vsShareInvite: '✶ PARTAGER LE LIEN',
    vsCopied: '✶ LIEN COPIÉ — ENVOYEZ-LE', vsCopyFail: '✶ COPIE ÉCHOUÉE — partagez le sceau', vsShareText: '%1 vous appelle à un duel STARSPELL — touchez pour répondre :',
    vsFriendText: 'ajoutez %1 comme ami sur STARSPELL :', lobbyTitle: 'L\'APPEL EST SCELLÉ', lobbySub: 'partagez le lien — ou votre rival saisit ce sceau sous VERSUS',
    smTitle: '⚔ %1 vous défie', smAccept: 'ACCEPTER', smMore: '+ %1 autres appels',
    smJoining: 'réponse à l\'appel…', smCold: 'ce sceau s\'est refroidi — le duel est fini ou complet', frAdded: '✦ %1 est désormais votre ami',
    frLinkTitle: 'un ami rejoint votre ciel', vsFriendsOn: '✦ %1 de vos amis en ligne', endAddFriend: '✦ AJOUTER %1 COMME AMI',
    endFriends: '✦ AMIS ✦',
    vsLang: '⚔ ce duel se tisse en %1',
    nameTakenTitle: '✦ UN NOM DÉJÀ ÉCRIT ✦', nameTakenBody: 'les étoiles connaissent déjà un autre %1 · dès ce soir vous êtes %2',
    nameHeldTitle: '✦ CE NOM EST DÉJÀ PRIS ✦', nameHeldBody: 'un autre astronome répond déjà à %1 · vous restez %2',
    zod: {
      aries: ['LE BÉLIER', 'Chaque combat s\'ouvre sur une charge : la bête subit %1.'],
      taurus: ['LE TAUREAU', 'Le taureau endure : +%1 de santé maximale au départ de l\'ascension.'],
      gemini: ['LES JUMEAUX', 'Lettres jumelles : les mots utilisant deux fois la même lettre font +%1.'],
      cancer: ['LE CRABE', 'La carapace tient : le premier coup de chaque combat fait %1 % de moins.'],
      leo: ['LE LION', 'Le rugissement : les mots de 6 lettres ou plus font +%1.'],
      virgo: ['LA VIERGE', 'Une fois par combat, touche ton signe puis une tuile pour la purifier en une nouvelle lettre.',
        'Deux fois par combat, touche ton signe puis une tuile pour la purifier en une nouvelle lettre.',
        'Trois fois par combat, touche ton signe puis une tuile pour la purifier en une nouvelle lettre.'],
      libra: ['LA BALANCE', 'La balance : les mots aux voyelles et consonnes en équilibre font +%1.'],
      scorpio: ['LE SCORPION', 'Le venin croît à chaque mot — la bête en subit jusqu\'à %1 après chaque lancer.',
        'Le venin croît deux fois plus vite à chaque mot — la bête en subit jusqu\'à %1 après chaque lancer.'],
      sagittarius: ['L\'ARCHER', 'La flèche encochée : SCRY frappe aussi la bête pour %1.'],
      capricorn: ['LA CHÈVRE DES MERS', 'L\'ascension : les mots font +1 pour deux bêtes terrassées dans la partie.',
        'L\'ascension : les mots font +1 par bête terrassée dans la partie.',
        'L\'ascension : les mots font +2 par bête terrassée dans la partie.'],
      aquarius: ['LE PORTEUR D\'EAU', 'Une fois par combat, tomber sous la moitié de sa santé verse les eaux : soigne %1.',
        'Deux fois par combat, tomber sous la moitié de sa santé verse les eaux : soigne %1.'],
      pisces: ['LES POISSONS JUMEAUX', 'Le courant profond : les mots tissés à un lancer du coup font +%1 %.'],
    },
    sig: {
      quill: ['PLUME DE BRAISE', 'Chaque mot inflige +%1 dégâts.'],
      choir: ['CHŒUR DE VOYELLES', 'Chaque voyelle vaut +%1.'],
      runes: ['RUNES DE LA RIVIÈRE', 'S, R, E et T valent +%1 chacune.'],
      salve: ['BAUME DE LUNE', 'Les mots de 5 lettres et plus te soignent de %1.'],
      aegis: ['ÉGIDE DE L’AUBE', '+%1 de santé max, soignée aussitôt.'],
      first: ['PREMIÈRE LUEUR', 'Ton premier mot de chaque combat frappe double.', 'Ton premier mot de chaque combat frappe triple.'],
      hush: ['SABLIER FEUTRÉ', 'Les bêtes frappent un lancer plus tard.', 'Les bêtes frappent deux lancers plus tard.'],
      comet: ['TRAÎNÉE DE COMÈTE', 'Ton premier SCRY de chaque combat ne hâte pas la frappe.', 'Tes deux premiers SCRY de chaque combat ne hâtent pas la frappe.', 'Tes trois premiers SCRY de chaque combat ne hâtent pas la frappe.'],
      shield: ['BOUCLIER D’ARGENT', 'Bloque la première frappe de chaque combat.', 'Bloque les deux premières frappes de chaque combat.'],
      leech: ['BUVEUR DE ROSÉE', 'Chaque mot te soigne de %1.'],
      longbow: ['ARC ÉTOILÉ', 'Les mots de 6 lettres et plus font +%1.'],
      gilded: ['AUBE DORÉE', 'Chaque combat commence avec une tuile dorée.', 'Chaque combat commence avec deux tuiles dorées.', 'Chaque combat commence avec deux tuiles étoilées.'],
      forge: ['FORGE STELLAIRE', 'Les tuiles forgées gagnent un palier de plus.', 'Les tuiles forgées gagnent un palier de plus, et les mots de 4 lettres forgent.'],
      blood: ['ENCRE DE SANG', 'Tes mots +%1%. Les frappes des bêtes +%2%.'],
      tome: ['TOME MURMURANT', 'L’œil ◉ révèle un mot puissant, une fois par combat. Prix du tome : −25 % du score final.', 'L’œil ◉ révèle un mot puissant, deux fois par combat. Prix du tome : −25 % du score final.', 'L’œil ◉ révèle un mot puissant, deux fois par combat. Prix du tome : −15 % du score final.'],
      storm: ['LIEUR D’ORAGES', 'Un mot sur trois frappe deux fois.', 'Un mot sur deux frappe deux fois.'],
      roots: ['RACINES TELLURIQUES', 'Les mots font +%1 par sceau que tu détiens.'],
      ward: ['GARDE DE LUNE', 'Les frappes des bêtes font %1 de moins, jamais sous 1.'],
      echo: ['ÉCHO DE RUINE', 'Les dégâts en excès blessent la bête suivante.', 'Les dégâts en excès blessent la bête suivante, moitié en plus.', 'Les dégâts en excès blessent la bête suivante au double.'],
      feather: ['PLUME DE PHÉNIX', 'Une fois par partie, survis à la mort avec %1 de santé.'],
      eclipse: ['L’ÉCLIPSE', 'Les frappes des bêtes ne font que la moitié.', 'Les frappes des bêtes ne font qu’un tiers.'],
      nova: ['COURONNE DE NOVAE', 'Les mots de %1 lettres et plus frappent double.'],
      verse: ['LE VERS SANS FIN', 'Les mots font +%1 par mot tissé dans la partie.'],
      meteor: ['CŒUR DU MÉTÉORE', 'Terrasser une bête te rend toute ta santé.', 'Terrasser une bête donne +3 de santé max, puis te rend toute ta santé.'],
    },
    unl: {
      comet: 'Invoque SCRY %1 fois.',
      longbow: 'Tisse %1 mots de six lettres ou plus.',
      gilded: 'Forge %1 tuiles avec de longs mots.',
      forge: 'Tisse %1 mots de sept lettres ou plus.',
      blood: 'Inflige %1 dégâts avec un seul mot.',
      tome: 'Abats %1 bêtes stellaires.',
      storm: 'Remporte %1 chasses.',
      echo: 'Déverse %1 dégâts en excès.',
      eclipse: 'Encaisse %1 frappes de bête.',
      nova: 'Tisse un mot de huit lettres.',
      verse: 'Tisse %1 mots au total.',
      meteor: 'Abats %1 bêtes à dix points de vie ou moins.',
    },
  },
  pt: {
    rotate: 'gire o celular na vertical para jogar',
    title: 'STARSPELL',
    tagline: 'teça palavras · derrube as feras estelares',
    campaign: 'CAMPANHA',
    act1: 'ATO I · O CÉU DO PRADO', act2: 'ATO II · A NOITE PROFUNDA',
    act3: 'ATO III · A COROA DA ALVORADA', act4: 'ATO IV · A CAÇADA SEM FIM',
    tBoss: 'CHEFE', tElite: 'ELITE',
    beast: {
      vulpes: 'A RAPOSA DE BRASAS', lepus: 'A LEBRE ENLUARADA', serpens: 'A SERPENTE DAS MARÉS',
      delphinus: 'O GOLFINHO ESTELAR', columba: 'A POMBA ARAUTO', lacerta: 'O LAGARTO ZIGUEZAGUE',
      cygnus: 'O CISNE DOS VENTOS', pavo: 'O PAVÃO VELADO', cancer: 'O CARANGUEJO SOMBRIO',
      corvus: 'O CORVO OCO', ursa: 'A URSA DO INVERNO', aranea: 'A VIÚVA DE SEDA',
      aquila: 'A ÁGUIA DO TROVÃO', lupus: 'O LOBO FAMINTO DE ESTRELAS', monoceros: 'O UNICÓRNIO DE VIDRO',
      cassiopeia: 'A RAINHA VAIDOSA', cetus: 'O LEVIATÃ AFUNDADO', orion: 'O CAÇADOR ESTELAR',
      strix: 'A CORUJA DO VAZIO', leo: 'O LEÃO SOBERANO', taurus: 'O TOURO DE OLHOS DE TEMPESTADE',
      scorpius: 'O FERRÃO CARMESIM', draco: 'O DEVORADOR DE ESTRELAS', phoenix: 'A PRIMEIRA CHAMA',
      centaurus: 'O CENTAURO PRIMOGÉNITO', sagittarius: 'O ARQUEIRO DO ZÉNITE',
    },
    cont: 'CONTINUAR', fightN: 'luta %1 de 5',
    quick: 'JOGO RÁPIDO',
    daily: 'CAÇADA DIÁRIA', dailyOpen: 'um só céu, de todos · faltam %1',
    dailyDone: 'hoje: %1 · novo céu em %2', cdHM: '%1 h %2 min', cdH: '%1 h', cdM: '%1 min',
    board: 'PLACAR', profile: 'PERFIL',
    versus: '⚔ VERSUS ⚔',
    endWin: 'O CÉU SILENCIA', endWinSub: 'todas as feras estelares caíram · a noite é sua',
    endLose: 'AS ESTRELAS TE RECLAMAM', endLoseSub: 'a subida termina aqui',
    fanWin: 'VITÓRIA', fanCamp: 'CAMPEÃO DO CÉU', fanVs: 'TRIUNFO',
    fanVsSub: '%1 caiu', fanVsSubMany: 'todos os rivais caíram',
    stScore: 'pontos', stBest: 'recorde %1', newBest: '✦ NOVO RECORDE! ✦',
    endTomeTax: '◉ preço do tomo · −%1%',
    tileFade: 'sem uso · o brilho se apaga',
    inkTele: '✦ o vazio bebe suas letras ✦',
    inkHint: 'entintada · não vale nada',
    stBeasts: 'feras derrubadas', stWords: 'palavras tecidas', stLetters: 'letras lançadas',
    stFinest: 'melhor palavra', stBigHit: 'golpe supremo', stTime: 'duração', stSigils: 'sígilos',
    newRun: 'NOVA PARTIDA', tryAgain: 'TENTAR DE NOVO', home: 'INÍCIO',
    shareBtn: '✶ COMPARTILHAR A CAÇADA', shareCopied: '✶ COPIADO — VÁ SE GABAR', shareFail: '✶ FALHA AO COPIAR',
    shHead: 'STARSPELL Caçada diária · %1', shScore: '%1 pontos',
    shFinest: 'melhor palavra: %1 peças', shFinest1: 'melhor palavra: 1 peça',
    shNoWord: 'nenhuma palavra', shStreak: 'sequência de %1 noites', shStreak1: 'primeira noite',
    sigilHead: '— ESCOLHA UM SÍGILO —', vsSigilHead: '— UM SÍGILO SE OFERECE —',
    unlHead: 'SÍGILO DESCOBERTO',
    unlSkies: 'já brilha nos teus céus.',
    unlTap: 'toca para continuar',
    slpHead: 'AINDA ADORMECIDOS',
    slpSub: '%1 sígilos por descobrir',
    slpSub1: 'um sígilo por descobrir',
    slpNone: 'o céu inteiro é teu',
    skiesTitle: 'OS TEUS CÉUS',
    skiesNear: '%1 despertos · %2 quase lá',
    rarityRare: 'RARO', rarityEpic: 'ÉPICO', rarityLegendary: 'LENDÁRIO',
    upHead: '— FORTALEÇA UM SÍGILO —', upMax: 'NO SEU AUGE',
    inspTitle: 'OS TEUS PODERES', inspSub: 'toca fora para fechar', inspSign: 'SIGNO NATAL',
    cdMS: '%1 min %2 s', cdS: '%1 s', cdD: '%1 d', cdDH: '%1 d %2 h',
    lbTitle: 'O MELHOR DA NOITE', lbDaily: 'DIÁRIA', lbWeekly: 'SEMANAL',
    lbNewSky: 'novo céu em %1', lbWeekEnds: 'a semana termina em %1',
    lbLoading: 'consultando as estrelas…', lbEmpty: 'nenhuma caçada registrada — seja o primeiro',
    lbYou: 'VOCÊ', lbYouRank: 'seu lugar: #%1 de %2',
    lbLocal: 'placar local — o céu maior está fora de alcance',
    dpOneSky: 'um só céu, de todos', dpAwait: 'o céu de hoje espera por você',
    dpPlayed: 'sua caçada de hoje: %1',
    stkLit: 'a lanterna está acesa', stkNight: 'noite %1', stkKeep: 'mantenha a chama · %1',
    stkSheet: 'A LANTERNA', stkWeekHead: 'AS ÚLTIMAS SETE NOITES', stkLegend: '✓ caçada · ◌ noite de graça · ○ perdida',
    stkCold: 'a lanterna está apagada', stkColdSub: 'a caçada desta noite a acende', stkBest: 'chama mais longa · %1',
    stkNextMark: 'próxima marca · noite %1', stkGraceHeld: 'uma noite de graça está guardada para você', stkGraceBridge: 'ontem à noite foi perdida · sua noite de graça segura a chama',
    stkGraceSpent: 'a noite de graça segurou a chama — recuperada em %1 caçadas', stkGraceSpent1: 'a noite de graça segurou a chama — recuperada em 1 caçada', stkGraced: 'uma noite de graça segurou a chama',
    stkMsHead: 'A LANTERNA CRESCE', stkMs7: 'SETE NOITES', stkMs30: 'TRINTA NOITES',
    stkMs100: 'CEM NOITES', stkMsSub7: 'uma brasa coroa o vidro', stkMsSub30: 'o ferro é dourado, e a luz escapa',
    stkMsSub100: 'um cometa vela pela sua chama',
    dpPlay: 'INICIAR A CAÇADA', dpAgain: 'CAÇAR DE NOVO', dpTop: 'O MELHOR DE HOJE',
    newCamp: 'NOVO JOGO',
    contCamp: 'CONTINUAR JOGO',
    endless: 'SEM FIM', endlessSub: 'até onde você pode subir?', hardLbl: 'DIFÍCIL',
    endlessCont: 'nível %1 · a subida aguarda', endlessBest: 'recorde · nível %1',
    endlessTitle: 'O CÉU SEM FIM', endLvl: 'NÍVEL %1', endLvlShort: 'NV %1',
    endLvlReached: 'nível alcançado', endBestLvl: 'melhor nível %1',
    endEndTitle: 'A SUBIDA TERMINA', endEndSub: 'as estrelas contaram tudo · cada degrau fica escrito',
    endAgain: 'SUBIR DE NOVO', endContBtn: 'CONTINUAR A SUBIDA', endNewBtn: 'COMEÇAR OUTRA SUBIDA',
    endStands: 'A subida aguarda no nível %1.',
    lbAllTime: 'o registro sem fim · cada subida guardada', lbHardTime: 'o registro de brasas · cada vitória difícil guardada',
    mapTitle: 'O CÉU DA CAMPANHA', mapHint: 'toque na constelação brilhante para entrar na luta', mapDest: 'fim da jornada',
    restartTitle: 'REINICIAR SEU JOGO?', restartBody: 'Isso reiniciará seu jogo atual em andamento.',
    restartBack: 'VOLTAR', restartNew: 'NOVA',
    zpTitle: 'ESCOLHE O TEU SIGNO', zpSub: 'nascidos sob um só céu · cada signo verga a subida',
    zpBegin: 'COMEÇAR A SUBIDA', zpSkip: 'subir sem signo · a subida clássica',
    zpPurify: 'toca numa peça para a purificar', zShell: 'A CARAPAÇA AGUENTA',
    zpOpenName: 'O CÉU ABERTO', zpOpenTitle: 'A SUBIDA SEM SIGNO',
    zpOpenDesc: 'Sem signo, sem poder — a subida clássica, como as primeiras estrelas a viram.', zpRec: 'concluída ×%1 · melhor %2',
    svLevel: 'NÍVEL %1', svLevelMax: 'NÍVEL 50 · NO SEU AUGE', svHead: 'O TEU SIGNO ASCENDE',
    svReward: 'O NÍVEL TRAZ UM DOM', svRwVessel: '+%1 de vida inicial sob este signo', svRwGilded: 'uma peça dourada abre a subida',
    rating: 'classificação estelar', rVeilRow: 'velar minha classificação dos outros', rVeiled: 'velada', rShown: 'visível',
    rHiddenCard: 'velada na luz das estrelas', rYourVeil: 'os outros veem sua classificação velada',
    rt0: 'POEIRA ESTELAR', rt1: 'ESTRELA DE BRASA', rt2: 'ESTRELA ASCENDENTE', rt3: 'ESTRELA DOURADA',
    rt4: 'NOVA', rt5: 'SUPERNOVA', rt6: 'COROA CELESTE',
    // friends · invites · summons (v0.25.0)
    vsAs: 'como %1', vsFriends: '— AMIGOS —', vsNoFriends: 'ainda sem amigos — convide um abaixo ou adicione um rival recente',
    vsOnline: 'online', vsOffline: 'offline', vsInDuel: '⚔ em duelo',
    vsSeen: 'visto há %1', vsChallenge: 'DESAFIAR', vsRecent: 'rivais recentes',
    vsAdd: '+ ADICIONAR', vsRemove: 'remover', vsFriendLink: '✶ PARTILHAR O MEU LINK DE AMIGO',
    vsMore: '+ %1 mais', vsModeTurns: 'TURNOS', vsModeTimed: 'CONTRA O TEMPO',
    vsModeBg: 'CAMPO DE BATALHA', vsTurnsSub: 'palavra por palavra, golpe a golpe — sem relógio, sem piedade', vsTimedSub: 'três minutos, ambos a tecer ao mesmo tempo',
    vsBgSub: 'dois a quatro magos · cada golpe acha o líder', vsInvite: '⚔ CONVIDAR UM AMIGO', vsInviteSub: 'envie-lhe um link — um toque e o duelo começa',
    vsFind: 'ENCONTRAR UM RIVAL', vsFindSub: 'partida rápida sob o céu aberto', vsOrSeal: '— ou responda a um chamado —',
    vsOrReach: '— ou procure um mago você mesmo —', vsByName: 'POR NOME', vsNamePh: 'o nome de um mago', vsNameSeek: 'procurando %1 entre as estrelas…',
    vsNameNone: 'nenhum mago tem o nome %1 — confira a grafia e tente de novo', vsNameSelf: 'esse é o seu próprio nome — as estrelas não o colocarão contra si mesmo', vsWaitAway: '%1 está longe do céu — o seu chamado espera sob as estrelas dele até voltar', vsWaitBusy: '%1 está em pleno duelo — o seu chamado espera que termine',
    // recent rivals (v0.55.0, task 44)
    vsRecentHead: '— RIVAIS RECENTES —', vsNoRecent: 'ainda sem rivais — seu primeiro duelo escreve aqui o primeiro nome', vsAgoTonight: 'esta noite', vsAgoLastNight: 'ontem à noite', vsAgoNights: 'há %1 noites', vsAgoLong: 'há muito tempo', vsAgain: '⚔ DE NOVO',
    vsSeal: 'INSERIR UM SELO', vsNoSky: 'o vasto céu está inalcançável —\nduelos precisam de ligação', vsConsult: 'consultando as estrelas…',
    vsRefused: 'as estrelas recusaram — tente de novo', vsColdSeal: 'esse selo não responde a ninguém', vsSent: 'CHAMADO ENVIADO A %1',
    vsWaitAnswer: 'à espera da resposta de %1… o selo acima também serve', vsDeclined: '%1 recusou o chamado — partilhe o selo ou desafie outro', vsShareInvite: '✶ PARTILHAR O LINK',
    vsCopied: '✶ LINK COPIADO — ENVIE-O', vsCopyFail: '✶ FALHA AO COPIAR — partilhe o selo', vsShareText: '%1 chama-te para um duelo de STARSPELL — toca para responder:',
    vsFriendText: 'adiciona %1 como amigo no STARSPELL:', lobbyTitle: 'O CHAMADO ESTÁ SELADO', lobbySub: 'partilhe o link — ou o seu rival insere este selo em VERSUS',
    smTitle: '⚔ %1 desafia-te', smAccept: 'ACEITAR', smMore: '+ %1 chamados mais',
    smJoining: 'respondendo ao chamado…', smCold: 'esse selo esfriou — o duelo acabou ou está cheio', frAdded: '✦ %1 agora é teu amigo',
    frLinkTitle: 'um amigo junta-se ao teu céu', vsFriendsOn: '✦ %1 dos teus amigos online', endAddFriend: '✦ ADICIONAR %1 COMO AMIGO',
    endFriends: '✦ AMIGOS ✦',
    vsLang: '⚔ este duelo se tece em %1',
    nameTakenTitle: '✦ UM NOME JÁ ESCRITO ✦', nameTakenBody: 'as estrelas já conhecem outro %1 · desta noite em diante és %2',
    nameHeldTitle: '✦ ESSE NOME JÁ TEM DONO ✦', nameHeldBody: 'outro observador já atende por %1 · continuas a ser %2',
    zod: {
      aries: ['O CARNEIRO', 'Cada combate abre com uma investida: a fera sofre %1.'],
      taurus: ['O TOURO', 'O touro resiste: +%1 de vida máxima no início da subida.'],
      gemini: ['OS GÉMEOS', 'Letras gémeas: palavras que usam a mesma letra duas vezes causam +%1.'],
      cancer: ['O CARANGUEJO', 'A carapaça aguenta: o primeiro golpe de cada combate causa %1% menos.'],
      leo: ['O LEÃO', 'O rugido: palavras de 6+ letras causam +%1.'],
      virgo: ['A DONZELA', 'Uma vez por combate, toca no teu signo e depois numa peça para a purificar numa letra nova.',
        'Duas vezes por combate, toca no teu signo e depois numa peça para a purificar numa letra nova.',
        'Três vezes por combate, toca no teu signo e depois numa peça para a purificar numa letra nova.'],
      libra: ['A BALANÇA', 'A balança: palavras com vogais e consoantes em equilíbrio causam +%1.'],
      scorpio: ['O ESCORPIÃO', 'O veneno cresce a cada palavra — a fera sofre até %1 após cada lance.',
        'O veneno cresce em dobro a cada palavra — a fera sofre até %1 após cada lance.'],
      sagittarius: ['O ARQUEIRO', 'A flecha pronta: SCRY também atinge a fera por %1.'],
      capricorn: ['A CABRA-MARINHA', 'A subida: palavras causam +1 por cada duas feras abatidas na partida.',
        'A subida: palavras causam +1 por cada fera abatida na partida.',
        'A subida: palavras causam +2 por cada fera abatida na partida.'],
      aquarius: ['O AGUADEIRO', 'Uma vez por combate, cair abaixo de metade da vida verte as águas: cura %1.',
        'Duas vezes por combate, cair abaixo de metade da vida verte as águas: cura %1.'],
      pisces: ['OS PEIXES GÉMEOS', 'A corrente profunda: palavras tecidas a um lance do golpe causam +%1%.'],
    },
    sig: {
      quill: ['PENA DE BRASA', 'Cada palavra causa +%1 de dano.'],
      choir: ['CORO DE VOGAIS', 'Cada vogal vale +%1.'],
      runes: ['RUNAS DO RIO', 'S, R, E e T valem +%1 cada.'],
      salve: ['BÁLSAMO LUNAR', 'Palavras de 5+ letras curam %1.'],
      aegis: ['ÉGIDE DA ALVORADA', '+%1 de vida máxima, curada na hora.'],
      first: ['PRIMEIRA LUZ', 'Sua primeira palavra de cada luta causa o dobro.', 'Sua primeira palavra de cada luta causa o triplo.'],
      hush: ['AMPULHETA QUIETA', 'As feras golpeiam um lance mais tarde.', 'As feras golpeiam dois lances mais tarde.'],
      comet: ['RASTRO DE COMETA', 'Seu primeiro SCRY de cada luta não apressa o golpe.', 'Seus dois primeiros SCRY de cada luta não apressam o golpe.', 'Seus três primeiros SCRY de cada luta não apressam o golpe.'],
      shield: ['ESCUDO DE PRATA', 'Bloqueia o primeiro golpe de cada luta.', 'Bloqueia os dois primeiros golpes de cada luta.'],
      leech: ['BEBEDOR DE ORVALHO', 'Cada palavra cura %1.'],
      longbow: ['ARCO ESTELAR', 'Palavras de 6+ letras causam +%1.'],
      gilded: ['ALVORADA DOURADA', 'Cada luta começa com uma peça dourada.', 'Cada luta começa com duas peças douradas.', 'Cada luta começa com duas peças estelares.'],
      forge: ['FORJA ESTELAR', 'Peças forjadas sobem um nível a mais.', 'Peças forjadas sobem um nível a mais, e palavras de 4 letras forjam.'],
      blood: ['TINTA DE SANGUE', 'Suas palavras +%1%. Golpes das feras +%2%.'],
      tome: ['TOMO SUSSURRANTE', 'O olho ◉ revela uma palavra forte, uma vez por luta. Preço do tomo: −25% da pontuação final.', 'O olho ◉ revela uma palavra forte, duas vezes por luta. Preço do tomo: −25% da pontuação final.', 'O olho ◉ revela uma palavra forte, duas vezes por luta. Preço do tomo: −15% da pontuação final.'],
      storm: ['PRENDE-TORMENTAS', 'Cada terceira palavra golpeia duas vezes.', 'Cada segunda palavra golpeia duas vezes.'],
      roots: ['RAÍZES TELÚRICAS', 'Palavras causam +%1 por sígilo que você tiver.'],
      ward: ['GUARDA LUNAR', 'Golpes das feras causam %1 a menos, nunca abaixo de 1.'],
      echo: ['ECO DA RUÍNA', 'O dano excedente fere a próxima fera.', 'O dano excedente fere a próxima fera com metade a mais.', 'O dano excedente fere a próxima fera em dobro.'],
      feather: ['PENA DE FÊNIX', 'Uma vez por partida, sobreviva à morte com %1 de vida.'],
      eclipse: ['O ECLIPSE', 'Golpes das feras causam só a metade.', 'Golpes das feras causam só um terço.'],
      nova: ['COROA DE NOVAS', 'Palavras de %1+ letras causam o dobro.'],
      verse: ['O VERSO SEM FIM', 'Palavras causam +%1 por palavra tecida na partida.'],
      meteor: ['CORAÇÃO DO METEORO', 'Derrubar uma fera restaura toda a sua vida.', 'Derrubar uma fera dá +3 de vida máxima e restaura tudo.'],
    },
    unl: {
      comet: 'Invoca SCRY %1 vezes.',
      longbow: 'Tece %1 palavras de seis letras ou mais.',
      gilded: 'Forja %1 peças com palavras longas.',
      forge: 'Tece %1 palavras de sete letras ou mais.',
      blood: 'Causa %1 de dano com uma única palavra.',
      tome: 'Derruba %1 bestas estelares.',
      storm: 'Vence %1 caçadas.',
      echo: 'Derrama %1 de dano excedente.',
      eclipse: 'Aguenta %1 golpes de besta.',
      nova: 'Tece uma palavra de oito letras.',
      verse: 'Tece %1 palavras no total.',
      meteor: 'Derruba %1 bestas com dez de saúde ou menos.',
    },
  },
  de: {
    rotate: 'dreh dein Handy ins Hochformat, um zu spielen',
    title: 'STARSPELL',
    tagline: 'webe Worte · fälle die Sternenbestien',
    campaign: 'KAMPAGNE',
    act1: 'AKT I · DER WIESENHIMMEL', act2: 'AKT II · DIE TIEFE NACHT',
    act3: 'AKT III · DIE KRONE DER MORGENRÖTE', act4: 'AKT IV · DIE ENDLOSE JAGD',
    tBoss: 'BOSS', tElite: 'ELITE',
    beast: {
      vulpes: 'DER GLUTFUCHS', lepus: 'DER MONDHASE', serpens: 'DIE GEZEITENSCHLANGE',
      delphinus: 'DER STERNENDELPHIN', columba: 'DIE BOTENTAUBE', lacerta: 'DIE ZICKZACK-ECHSE',
      cygnus: 'DER WINDSCHWAN', pavo: 'DER VERSCHLEIERTE PFAU', cancer: 'DIE DÜSTERKRABBE',
      corvus: 'DER HOHLE RABE', ursa: 'DIE WINTERBÄRIN', aranea: 'DIE SEIDENWITWE',
      aquila: 'DER DONNERADLER', lupus: 'DER STERNHUNGRIGE WOLF', monoceros: 'DAS GLASEINHORN',
      cassiopeia: 'DIE EITLE KÖNIGIN', cetus: 'DER ERTRUNKENE LEVIATHAN', orion: 'DER STERNGEBUNDENE JÄGER',
      strix: 'DIE EULE DER LEERE', leo: 'DER LÖWENFÜRST', taurus: 'DER STURMÄUGIGE STIER',
      scorpius: 'DER KARMESINSTACHEL', draco: 'DER STERNENFRESSER', phoenix: 'DIE ERSTE FLAMME',
      centaurus: 'DER ERSTGEBORENE ZENTAUR', sagittarius: 'DER ZENIT-SCHÜTZE',
    },
    cont: 'WEITER', fightN: 'Kampf %1 von 5',
    quick: 'SCHNELLES SPIEL',
    daily: 'TAGESJAGD', dailyOpen: 'ein Himmel, geteilt mit allen · noch %1',
    dailyDone: 'heute: %1 · neuer Himmel in %2', cdHM: '%1 Std %2 Min', cdH: '%1 Std', cdM: '%1 Min',
    board: 'BESTENLISTE', profile: 'PROFIL',
    versus: '⚔ VERSUS ⚔',
    endWin: 'DER HIMMEL SCHWEIGT', endWinSub: 'alle Sternenbestien sind gefallen · die Nacht gehört dir',
    endLose: 'DIE STERNE HOLEN DICH', endLoseSub: 'der Aufstieg endet hier',
    fanWin: 'SIEG', fanCamp: 'MEISTER DES HIMMELS', fanVs: 'TRIUMPH',
    fanVsSub: '%1 ist bezwungen', fanVsSubMany: 'alle Rivalen sind bezwungen',
    stScore: 'Punkte', stBest: 'Rekord %1', newBest: '✦ NEUER REKORD! ✦',
    endTomeTax: '◉ Preis des Folianten · −%1%',
    tileFade: 'ungenutzt · der Glanz verblasst',
    inkTele: '✦ die Leere trinkt deine Buchstaben ✦',
    inkHint: 'geschwärzt · nichts wert',
    stBeasts: 'Bestien gefällt', stWords: 'Worte gewoben', stLetters: 'Buchstaben gewirkt',
    stFinest: 'schönstes Wort', stBigHit: 'stärkster Treffer', stTime: 'Laufzeit', stSigils: 'Sigel',
    newRun: 'NEUER LAUF', tryAgain: 'NOCHMAL', home: 'START',
    shareBtn: '✶ JAGD TEILEN', shareCopied: '✶ KOPIERT — GEH PRAHLEN', shareFail: '✶ KOPIEREN FEHLGESCHLAGEN',
    shHead: 'STARSPELL Tagesjagd · %1', shScore: '%1 Punkte',
    shFinest: 'bestes Wort: %1 Steine', shFinest1: 'bestes Wort: 1 Stein',
    shNoWord: 'kein Wort gewirkt', shStreak: '%1-Nächte-Serie', shStreak1: 'erste Nacht',
    sigilHead: '— WÄHLE EIN SIGEL —', vsSigilHead: '— EIN SIGEL BIETET SICH AN —',
    unlHead: 'SIGEL ENTDECKT',
    unlSkies: 'es leuchtet nun an deinem Himmel.',
    unlTap: 'zum Fortfahren tippen',
    slpHead: 'NOCH SCHLAFEND',
    slpSub: '%1 Sigel noch zu entdecken',
    slpSub1: 'ein Sigel noch zu entdecken',
    slpNone: 'der ganze Himmel gehört dir',
    skiesTitle: 'DEIN HIMMEL',
    skiesNear: '%1 erwacht · %2 fast so weit',
    rarityRare: 'SELTEN', rarityEpic: 'EPISCH', rarityLegendary: 'LEGENDÄR',
    upHead: '— STÄRKE EIN SIGEL —', upMax: 'AUF SEINER HÖHE',
    inspTitle: 'DEINE KRÄFTE', inspSub: 'zum Schließen außerhalb tippen', inspSign: 'GEBURTSZEICHEN',
    cdMS: '%1 Min %2 Sek', cdS: '%1 Sek', cdD: '%1 T', cdDH: '%1 T %2 Std',
    lbTitle: 'DIE BESTEN DER NACHT', lbDaily: 'TÄGLICH', lbWeekly: 'WOCHE',
    lbNewSky: 'neuer Himmel in %1', lbWeekEnds: 'Woche endet in %1',
    lbLoading: 'die Sterne werden befragt…', lbEmpty: 'noch keine Jagd verzeichnet — sei die erste',
    lbYou: 'DU', lbYouRank: 'dein Platz: #%1 von %2',
    lbLocal: 'lokale Wertung — der weite Himmel ist unerreichbar',
    dpOneSky: 'ein Himmel, geteilt mit allen', dpAwait: 'der heutige Himmel wartet auf dich',
    dpPlayed: 'deine Jagd heute: %1',
    stkLit: 'die Laterne brennt', stkNight: 'Nacht %1', stkKeep: 'halte die Flamme · %1',
    stkSheet: 'DIE LATERNE', stkWeekHead: 'DIE LETZTEN SIEBEN NÄCHTE', stkLegend: '✓ gejagt · ◌ Gnadennacht · ○ verpasst',
    stkCold: 'die Laterne ist dunkel', stkColdSub: 'die Jagd heute Nacht entzündet sie', stkBest: 'längste Flamme · %1',
    stkNextMark: 'nächste Marke · Nacht %1', stkGraceHeld: 'eine Gnadennacht liegt für dich bereit', stkGraceBridge: 'letzte Nacht verpasst · deine Gnadennacht hält die Flamme',
    stkGraceSpent: 'die Gnadennacht hielt die Flamme — in %1 Jagden zurückverdient', stkGraceSpent1: 'die Gnadennacht hielt die Flamme — in 1 Jagd zurückverdient', stkGraced: 'eine Gnadennacht hielt die Flamme',
    stkMsHead: 'DIE LATERNE WÄCHST', stkMs7: 'SIEBEN NÄCHTE', stkMs30: 'DREISSIG NÄCHTE',
    stkMs100: 'HUNDERT NÄCHTE', stkMsSub7: 'eine Glut krönt das Glas', stkMsSub30: 'das Eisen ist vergoldet, und das Licht bricht hervor',
    stkMsSub100: 'ein Komet wacht über deine Flamme',
    dpPlay: 'ZUR JAGD', dpAgain: 'ERNEUT JAGEN', dpTop: 'DIE BESTEN HEUTE',
    newCamp: 'NEUES SPIEL',
    contCamp: 'SPIEL FORTSETZEN',
    endless: 'ENDLOS', endlessSub: 'wie hoch kommst du?', hardLbl: 'SCHWER',
    endlessCont: 'Stufe %1 · der Aufstieg wartet', endlessBest: 'Rekord · Stufe %1',
    endlessTitle: 'DER ENDLOSE HIMMEL', endLvl: 'STUFE %1', endLvlShort: 'LV %1',
    endLvlReached: 'erreichte Stufe', endBestLvl: 'beste Stufe %1',
    endEndTitle: 'DER AUFSTIEG ENDET', endEndSub: 'die Sterne haben mitgezählt · jede Sprosse steht geschrieben',
    endAgain: 'NOCHMAL KLETTERN', endContBtn: 'AUFSTIEG FORTSETZEN', endNewBtn: 'NEUEN AUFSTIEG BEGINNEN',
    endStands: 'Dein Aufstieg wartet auf Stufe %1.',
    lbAllTime: 'das endlose Register · jeder Aufstieg bleibt', lbHardTime: 'das Glut-Register · jeder schwere Sieg bleibt',
    mapTitle: 'DER KAMPAGNENHIMMEL', mapHint: 'tippe auf das leuchtende Sternbild, um zu kämpfen', mapDest: 'Ende der Reise',
    restartTitle: 'SPIEL NEU STARTEN?', restartBody: 'Dein laufendes Spiel wird damit neu gestartet.',
    restartBack: 'ZURÜCK', restartNew: 'NEU',
    zpTitle: 'WÄHLE DEIN ZEICHEN', zpSub: 'unter einem Himmel geboren · jedes Zeichen formt den Aufstieg',
    zpBegin: 'DEN AUFSTIEG BEGINNEN', zpSkip: 'ohne Zeichen klettern · der klassische Aufstieg',
    zpPurify: 'tippe eine Kachel an, um sie zu läutern', zShell: 'DER PANZER HÄLT',
    zpOpenName: 'DER OFFENE HIMMEL', zpOpenTitle: 'DER AUFSTIEG OHNE ZEICHEN',
    zpOpenDesc: 'Kein Zeichen, keine Kraft — der klassische Aufstieg, wie ihn die ersten Sterne sahen.', zpRec: 'geschafft ×%1 · Bestwert %2',
    svLevel: 'STUFE %1', svLevelMax: 'STUFE 50 · AUF SEINER HÖHE', svHead: 'DEIN ZEICHEN STEIGT AUF',
    svReward: 'DIE STUFE TRÄGT EIN GESCHENK', svRwVessel: '+%1 Startgesundheit unter diesem Zeichen', svRwGilded: 'ein vergoldeter Stein eröffnet den Aufstieg',
    rating: 'Sternenwertung', rVeilRow: 'meine Wertung vor anderen verhüllen', rVeiled: 'verhüllt', rShown: 'sichtbar',
    rHiddenCard: 'im Sternenlicht verhüllt', rYourVeil: 'andere sehen deine Wertung verhüllt',
    rt0: 'STERNENSTAUB', rt1: 'GLUTSTERN', rt2: 'AUFGEHENDER STERN', rt3: 'GOLDSTERN',
    rt4: 'NOVA', rt5: 'SUPERNOVA', rt6: 'HIMMELSKRONE',
    // friends · invites · summons (v0.25.0)
    vsAs: 'als %1', vsFriends: '— FREUNDE —', vsNoFriends: 'noch keine Freunde — lade unten einen ein oder füge einen Rivalen hinzu',
    vsOnline: 'online', vsOffline: 'offline', vsInDuel: '⚔ im Duell',
    vsSeen: 'zuletzt vor %1', vsChallenge: 'FORDERN', vsRecent: 'letzte Rivalen',
    vsAdd: '+ HINZUFÜGEN', vsRemove: 'entfernen', vsFriendLink: '✶ MEINEN FREUNDESLINK TEILEN',
    vsMore: '+ %1 weitere', vsModeTurns: 'ZÜGE', vsModeTimed: 'AUF ZEIT',
    vsModeBg: 'SCHLACHTFELD', vsTurnsSub: 'Wort um Wort, Schlag um Schlag — keine Uhr, keine Gnade', vsTimedSub: 'drei Minuten, beide weben zugleich',
    vsBgSub: 'zwei bis vier Magier · jeder Treffer sucht den Führenden', vsInvite: '⚔ FREUND EINLADEN', vsInviteSub: 'schick ihm einen Link — ein Tipp, und ihr duelliert euch',
    vsFind: 'RIVALEN FINDEN', vsFindSub: 'Schnellduell unter offenem Himmel', vsOrSeal: '— oder folge einem Ruf —',
    vsOrReach: '— oder erreiche selbst einen Magier —', vsByName: 'NACH NAMEN', vsNamePh: 'Name eines Magiers', vsNameSeek: 'suche %1 zwischen den Sternen…',
    vsNameNone: 'kein Magier trägt den Namen %1 — prüfe die Schreibweise und versuch es erneut', vsNameSelf: 'das ist dein eigener Name — die Sterne stellen dich nicht gegen dich selbst', vsWaitAway: '%1 ist fern vom Himmel — dein Ruf wartet unter seinen Sternen, bis er zurückkehrt', vsWaitBusy: '%1 ist mitten im Duell — dein Ruf wartet auf dessen Ende',
    // recent rivals (v0.55.0, task 44)
    vsRecentHead: '— LETZTE RIVALEN —', vsNoRecent: 'noch keine Rivalen — dein erstes Duell schreibt hier den ersten Namen', vsAgoTonight: 'heute Nacht', vsAgoLastNight: 'letzte Nacht', vsAgoNights: 'vor %1 Nächten', vsAgoLong: 'vor langer Zeit', vsAgain: '⚔ NOCHMAL',
    vsSeal: 'SIEGEL EINGEBEN', vsNoSky: 'der weite Himmel ist unerreichbar —\nDuelle brauchen eine Verbindung', vsConsult: 'die Sterne werden befragt…',
    vsRefused: 'die Sterne verweigerten sich — versuch es erneut', vsColdSeal: 'dieses Siegel antwortet niemandem', vsSent: 'RUF GESANDT AN %1',
    vsWaitAnswer: 'warte auf die Antwort von %1… das Siegel oben geht auch', vsDeclined: '%1 hat den Ruf abgelehnt — teile das Siegel oder fordere jemand anderen', vsShareInvite: '✶ EINLADUNGSLINK TEILEN',
    vsCopied: '✶ LINK KOPIERT — SCHICK IHN', vsCopyFail: '✶ KOPIEREN FEHLGESCHLAGEN — teile das Siegel', vsShareText: '%1 ruft dich zu einem STARSPELL-Duell — tippe, um zu antworten:',
    vsFriendText: 'füge %1 als STARSPELL-Freund hinzu:', lobbyTitle: 'DER RUF IST BESIEGELT', lobbySub: 'teile den Link — oder dein Rivale gibt dieses Siegel unter VERSUS ein',
    smTitle: '⚔ %1 fordert dich heraus', smAccept: 'ANNEHMEN', smMore: '+ %1 weitere Rufe',
    smJoining: 'dem Ruf wird gefolgt…', smCold: 'dieses Siegel ist erkaltet — das Duell ist vorbei oder voll', frAdded: '✦ %1 ist jetzt dein Freund',
    frLinkTitle: 'ein Freund betritt deinen Himmel', vsFriendsOn: '✦ %1 deiner Freunde online', endAddFriend: '✦ %1 ALS FREUND HINZUFÜGEN',
    endFriends: '✦ FREUNDE ✦',
    vsLang: '⚔ dieses Duell wird auf %1 gewoben',
    nameTakenTitle: '✦ EIN NAME, SCHON GESCHRIEBEN ✦', nameTakenBody: 'die Sterne kennen schon einen %1 · ab heute Nacht bist du %2',
    nameHeldTitle: '✦ DIESER NAME IST VERGEBEN ✦', nameHeldBody: 'ein anderer Sterngucker hört schon auf %1 · du bleibst %2',
    zod: {
      aries: ['DER WIDDER', 'Jeder Kampf beginnt mit einem Rammstoß: das Biest erleidet %1.'],
      taurus: ['DER STIER', 'Der Stier hält stand: +%1 maximale Gesundheit zu Beginn des Aufstiegs.'],
      gemini: ['DIE ZWILLINGE', 'Zwillingsbuchstaben: Wörter, die denselben Buchstaben zweimal nutzen, machen +%1.'],
      cancer: ['DER KREBS', 'Der Panzer hält: der erste Schlag jedes Kampfes richtet %1% weniger an.'],
      leo: ['DER LÖWE', 'Das Brüllen: Wörter mit 6+ Buchstaben machen +%1.'],
      virgo: ['DIE JUNGFRAU', 'Einmal pro Kampf: tippe dein Zeichen und dann eine Kachel, um sie zu einem neuen Buchstaben zu läutern.',
        'Zweimal pro Kampf: tippe dein Zeichen und dann eine Kachel, um sie zu einem neuen Buchstaben zu läutern.',
        'Dreimal pro Kampf: tippe dein Zeichen und dann eine Kachel, um sie zu einem neuen Buchstaben zu läutern.'],
      libra: ['DIE WAAGE', 'Die Waage: Wörter mit Vokalen und Konsonanten im Gleichgewicht machen +%1.'],
      scorpio: ['DER SKORPION', 'Das Gift wächst mit jedem Wort — das Biest erleidet bis zu %1 nach jedem Wurf.',
        'Das Gift wächst doppelt mit jedem Wort — das Biest erleidet bis zu %1 nach jedem Wurf.'],
      sagittarius: ['DER SCHÜTZE', 'Der gespannte Pfeil: SCRY trifft das Biest zusätzlich für %1.'],
      capricorn: ['DIE MEERZIEGE', 'Der Aufstieg: Wörter machen +1 für je zwei gefällte Biester dieser Partie.',
        'Der Aufstieg: Wörter machen +1 für jedes gefällte Biest dieser Partie.',
        'Der Aufstieg: Wörter machen +2 für jedes gefällte Biest dieser Partie.'],
      aquarius: ['DER WASSERTRÄGER', 'Einmal pro Kampf: fällst du unter die halbe Gesundheit, strömen die Wasser — heilt %1.',
        'Zweimal pro Kampf: fällst du unter die halbe Gesundheit, strömen die Wasser — heilt %1.'],
      pisces: ['DIE ZWILLINGSFISCHE', 'Die tiefe Strömung: Wörter, einen Wurf vor dem Schlag gewoben, machen +%1%.'],
    },
    sig: {
      quill: ['GLUTFEDER', 'Jedes Wort verursacht +%1 Schaden.'],
      choir: ['VOKALCHOR', 'Jeder Vokal zählt +%1.'],
      runes: ['FLUSSRUNEN', 'S, R, E und T zählen je +%1.'],
      salve: ['MONDSALBE', 'Worte mit 5+ Buchstaben heilen dich um %1.'],
      aegis: ['ÄGIS DER DÄMMERUNG', '+%1 maximale Gesundheit, sofort geheilt.'],
      first: ['ERSTES LICHT', 'Dein erstes Wort jedes Kampfes zählt doppelt.', 'Dein erstes Wort jedes Kampfes zählt dreifach.'],
      hush: ['STILLES STUNDENGLAS', 'Bestien schlagen einen Wurf später zu.', 'Bestien schlagen zwei Würfe später zu.'],
      comet: ['KOMETENSCHWEIF', 'Dein erster SCRY jedes Kampfes beschleunigt den Schlag nicht.', 'Deine ersten zwei SCRY jedes Kampfes beschleunigen den Schlag nicht.', 'Deine ersten drei SCRY jedes Kampfes beschleunigen den Schlag nicht.'],
      shield: ['SILBERSCHILD', 'Blockt den ersten Schlag jedes Kampfes.', 'Blockt die ersten zwei Schläge jedes Kampfes.'],
      leech: ['TAUTRINKER', 'Jedes Wort heilt dich um %1.'],
      longbow: ['STERNENBOGEN', 'Worte mit 6+ Buchstaben machen +%1.'],
      gilded: ['GOLDENE DÄMMERUNG', 'Jeder Kampf beginnt mit einem vergoldeten Stein.', 'Jeder Kampf beginnt mit zwei vergoldeten Steinen.', 'Jeder Kampf beginnt mit zwei Sternensteinen.'],
      forge: ['STERNENSCHMIEDE', 'Geschmiedete Steine kommen eine Stufe höher.', 'Geschmiedete Steine kommen eine Stufe höher, und Worte mit 4 Buchstaben schmieden.'],
      blood: ['BLUTTINTE', 'Deine Worte +%1%. Bestienschläge +%2%.'],
      tome: ['FLÜSTERNDER FOLIANT', 'Das Auge ◉ enthüllt ein starkes Wort, einmal pro Kampf. Preis des Folianten: −25% der Endpunktzahl.', 'Das Auge ◉ enthüllt ein starkes Wort, zweimal pro Kampf. Preis des Folianten: −25% der Endpunktzahl.', 'Das Auge ◉ enthüllt ein starkes Wort, zweimal pro Kampf. Preis des Folianten: −15% der Endpunktzahl.'],
      storm: ['STURMBINDER', 'Jedes dritte Wort schlägt zweimal zu.', 'Jedes zweite Wort schlägt zweimal zu.'],
      roots: ['LEYLINIEN-WURZELN', 'Worte machen +%1 je Sigel, das du trägst.'],
      ward: ['MONDWACHT', 'Bestienschläge machen %1 weniger, nie unter 1.'],
      echo: ['ECHO DES VERFALLS', 'Überschüssiger Schaden trifft die nächste Bestie.', 'Überschüssiger Schaden trifft die nächste Bestie, anderthalbfach.', 'Überschüssiger Schaden trifft die nächste Bestie doppelt.'],
      feather: ['PHÖNIXFEDER', 'Einmal pro Lauf überlebst du den Tod mit %1 Gesundheit.'],
      eclipse: ['DIE FINSTERNIS', 'Bestienschläge machen nur die Hälfte.', 'Bestienschläge machen nur ein Drittel.'],
      nova: ['KRONE DER NOVAE', 'Worte mit %1+ Buchstaben zählen doppelt.'],
      verse: ['DER ENDLOSE VERS', 'Worte machen +%1 je gewobenem Wort dieses Laufs.'],
      meteor: ['HERZ DES METEORS', 'Eine gefällte Bestie heilt dich vollständig.', 'Eine gefällte Bestie gibt +3 maximale Gesundheit und heilt dich vollständig.'],
    },
    unl: {
      comet: 'Rufe SCRY %1-mal an.',
      longbow: 'Webe %1 Wörter mit sechs Buchstaben oder mehr.',
      gilded: 'Schmiede %1 Steine mit langen Wörtern.',
      forge: 'Webe %1 Wörter mit sieben Buchstaben oder mehr.',
      blood: 'Füge mit einem einzigen Wort %1 Schaden zu.',
      tome: 'Fälle %1 Sternenbestien.',
      storm: 'Gewinne %1 Jagden.',
      echo: 'Verschütte %1 Punkte Überschaden.',
      eclipse: 'Überstehe %1 Bestienschläge.',
      nova: 'Webe ein Wort mit acht Buchstaben.',
      verse: 'Webe insgesamt %1 Wörter.',
      meteor: 'Fälle %1 Bestien mit zehn oder weniger Leben.',
    },
  },
};

// native names, for the language sheet — never translated
const SS_LANGS = {
  en: 'English', es: 'Español', fr: 'Français', pt: 'Português', de: 'Deutsch',
};

const SS_LANG = (() => {
  const qs = new URLSearchParams(location.search);
  const q = (qs.get('lang') || '').toLowerCase();
  if (SS_STR[q]) { try { localStorage.setItem('beta3.lang', q); } catch (e) { } return q; }
  let saved = null;
  try { saved = localStorage.getItem('beta3.lang'); } catch (e) { }
  if (SS_STR[saved]) return saved;
  // a saved pref naming a language that no longer ships (the v0.71.0 cut to
  // five) is cleared, and the pick falls through to the device locale below —
  // the player lands in their locale's best of the five, else English.
  if (saved) { try { localStorage.removeItem('beta3.lang'); } catch (e) { } }
  const nav = ((navigator.language || 'en').slice(0, 2)).toLowerCase();
  return SS_STR[nav] ? nav : 'en';
})();

function SS_T(key) {
  let s = (SS_STR[SS_LANG] && SS_STR[SS_LANG][key]) || SS_STR.en[key] || key;
  for (let i = 1; i < arguments.length; i++) s = s.replace('%' + i, arguments[i]);
  return s;
}

// Localized name/desc for a sigil def, at a TIER of its ladder (v0.66.0;
// default 1 keeps every pre-tier call site exact). English lives in data.js
// (the canonical copy); other languages carry a `sig` map of id →
// [name, desc] — grown to [name, descI, descII, …] where a tier changes the
// WORDS — and fall back per-sigil so a partial map ships gracefully (the
// index clamps, so an untranslated ladder shows its base desc). Template
// descs carry %1..%k, substituted from the def fields `dvf` names at the
// tier's own values (ssSigilField walks 'lb.add' paths) — the text is
// GENERATED from the numbers, so desc and effect can never drift.
function SS_SIG(s, tier) {
  const t = Math.max(1, Math.min((tier | 0) || 1, 1 + ((s.tl || []).length)));
  const m = (SS_STR[SS_LANG] && SS_STR[SS_LANG].sig) || {};
  const e = m[s.id];
  let desc = e ? e[Math.min(t, e.length - 1)] : ((t >= 2 && s.tl[t - 2].desc) || s.desc);
  if (s.dvf) for (let i = 0; i < s.dvf.length; i++) desc = desc.replace('%' + (i + 1), ssSigilField(s, s.dvf[i], t));
  return { name: e ? e[0] : s.name, desc };
}

/* The sentence that unlocks a locked sigil, localized. English is canonical in
   data.js (`lock.how`, %1 = the target) so the condition and its number can
   never drift apart; other languages carry an `unl` map of id → sentence and
   fall back per-sigil, so a partial translation ships gracefully. Returns ''
   for a sigil that was never locked. */
function SS_SIG_HOW(s) {
  if (!s || !s.lock) return '';
  const m = (SS_STR[SS_LANG] && SS_STR[SS_LANG].unl) || {};
  return String(m[s.id] || s.lock.how || '').replace('%1', s.lock.n);
}

// Localized flavor title for a beast. English lives in data.js (the canonical
// copy); other languages carry a `beast` map of id → title with per-beast
// fallback. Latin constellation NAMES (VULPES, ORION…) are never translated.
function SS_BEAST_T(b) {
  const m = (SS_STR[SS_LANG] && SS_STR[SS_LANG].beast) || {};
  return m[b.id] || b.title;
}

// Localized title/desc for a zodiac sign, at a LEVEL of its ladder
// (v0.69.0; default 1 keeps every pre-level call site exact — SS_SIG's own
// law). English lives in data.js (the canonical copy); other languages
// carry a `zod` map of id → [title, desc] — grown to [title, desc0,
// desc1, …] where a level advances the WORDING (`db` on the def lists the
// crossing levels; the index clamps, so a partial translation shows its
// base desc) — with per-sign fallback. Template descs carry %1..%k,
// substituted from the def fields `dvf` names at the level's own values
// (ssSignVal) — the text is GENERATED from the numbers, so desc and
// effect can never drift. Latin sign NAMES (ARIES, LIBRA…) never
// translate.
function SS_ZOD(z, lv) {
  const L = Math.max(1, (lv | 0) || 1);
  const m = (SS_STR[SS_LANG] && SS_STR[SS_LANG].zod) || {};
  const t = m[z.id];
  const band = (z.db || []).filter((b) => b <= L).length;
  let desc;
  if (t) desc = t[Math.min(1 + band, t.length - 1)];
  else desc = band > 0 && z.dvs ? z.dvs[Math.min(band - 1, z.dvs.length - 1)] : z.desc;
  if (z.dvf) for (let i = 0; i < z.dvf.length; i++) desc = desc.replace('%' + (i + 1), ssSignVal(z.id, z.dvf[i], L));
  return { title: t ? t[0] : z.title, desc };
}

// Act display name — acts carry a nameKey into the strings table.
function SS_ACT_N(act) { return SS_T(act.nameKey); }

try { document.title = SS_T('title'); } catch (e) { }
