'use strict';
/* ============================================================
   STARSPELL i18n — the strings table.
   Pick order: ?lang=xx → saved pref → browser language → en.
   ?lang also SAVES, so a player who follows a ?lang=es link
   stays in Spanish. Keys fall back to English per-string, so a
   partially translated language ships gracefully.
   Home screen is wired through SS_T(); battle/versus/profile
   strings migrate here incrementally.
   ============================================================ */
const SS_STR = {
  en: {
    rotate: 'turn your phone upright to play',
    title: 'STARSPELL',
    tagline: 'weave words · fell the star-beasts',
    campaign: 'CAMPAIGN', campaignSub: 'four acts · one long night',
    act1: 'ACT I · THE MEADOW SKY', act2: 'ACT II · THE DEEP NIGHT',
    act3: 'ACT III · THE CROWN OF DAWN', act4: 'ACT IV · THE ENDLESS HUNT',
    tBoss: 'BOSS', tElite: 'ELITE',
    cont: 'CONTINUE', fightN: 'fight %1 of 5',
    quick: 'QUICK PLAY', quickSub: 'five beasts, then the Star Eater',
    daily: 'DAILY HUNT', dailyOpen: 'one sky, shared by all · %1 left',
    dailyDone: 'today: %1 · next sky in %2', cdHM: '%1h %2m', cdH: '%1h', cdM: '%1m',
    board: 'LEADERBOARD', profile: 'PROFILE',
    versus: '⚔ VERSUS ⚔', versusSub: 'duel beneath the stars',
    endWin: 'THE SKY IS QUIET', endWinSub: 'every star-beast has fallen · the night is yours',
    endLose: 'THE STARS CLAIM YOU', endLoseSub: 'the ascent ends here',
    stScore: 'score', stBest: 'best %1', newBest: '✦ NEW BEST ✦',
    stBeasts: 'beasts felled', stWords: 'words woven', stLetters: 'letters cast',
    stFinest: 'finest word', stBigHit: 'mightiest hit', stTime: 'run time', stSigils: 'sigils held',
    newRun: 'NEW RUN', tryAgain: 'TRY AGAIN', home: 'HOME',
    shareBtn: '✶ SHARE TODAY\'S HUNT', shareCopied: '✶ COPIED — GO BOAST', shareFail: '✶ COPY FAILED',
    sigilHead: '— CHOOSE A SIGIL —', vsSigilHead: '— A SIGIL OFFERS ITSELF —',
    rarityRare: 'RARE', rarityLegendary: 'LEGENDARY',
    cdMS: '%1m %2s', cdS: '%1s', cdD: '%1d', cdDH: '%1d %2h',
    lbTitle: 'THE NIGHT\'S FINEST', lbDaily: 'DAILY', lbWeekly: 'WEEKLY',
    lbNewSky: 'new sky in %1', lbWeekEnds: 'week ends in %1',
    lbLoading: 'consulting the stars…', lbEmpty: 'no hunts recorded yet — be the first',
    lbYou: 'YOU', lbYouRank: 'your place: #%1 of %2',
    lbLocal: 'local standings — the wider sky is unreachable',
    dpOneSky: 'one sky, shared by all', dpAwait: 'today\'s sky awaits you',
    dpPlayed: 'your hunt today: %1', dpStreak: 'hunting streak: %1 days',
    dpPlay: 'BEGIN THE HUNT', dpAgain: 'HUNT AGAIN', dpTop: 'TODAY\'S FINEST',
    newCamp: 'NEW CAMPAIGN', newCampSub: 'begin the long night anew',
    mapTitle: 'THE CAMPAIGN SKY', mapHint: 'tap the glowing constellation to enter the fight', mapDest: 'journey\'s end',
    abandonTitle: 'ABANDON THE CLIMB?', abandonBody: 'your checkpoint at %1, fight %2, will fade into the dark',
    abandonYes: 'ABANDON', abandonNo: 'KEEP CLIMBING',
    zpTitle: 'CHOOSE YOUR SIGN', zpSub: 'born beneath one sky · each sign bends the climb',
    zpBegin: 'BEGIN THE CLIMB', zpSkip: 'walk unsigned · the classic climb',
    zpPurify: 'tap a tile to purify it', zShell: 'THE SHELL HOLDS',
    rating: 'star rating', rVeilRow: 'veil my rating from others', rVeiled: 'veiled', rShown: 'shown',
    rHiddenCard: 'veiled in starlight', rYourVeil: 'others see your rating veiled',
    rt0: 'STARDUST', rt1: 'EMBER STAR', rt2: 'RISING STAR', rt3: 'GILDED STAR',
    rt4: 'NOVA', rt5: 'SUPERNOVA', rt6: 'CELESTIAL CROWN',
    // sigil names/descs come from data.js in English; other languages carry a `sig` map
    // zodiac titles/descs come from data.js in English; other languages carry a `zod` map
  },
  es: {
    rotate: 'gira el teléfono en vertical para jugar',
    title: 'STARSPELL',
    tagline: 'teje palabras · derriba a las bestias estelares',
    campaign: 'CAMPAÑA', campaignSub: 'cuatro actos · una larga noche',
    act1: 'ACTO I · EL CIELO DEL PRADO', act2: 'ACTO II · LA NOCHE PROFUNDA',
    act3: 'ACTO III · LA CORONA DEL ALBA', act4: 'ACTO IV · LA CACERÍA SIN FIN',
    tBoss: 'JEFE', tElite: 'ÉLITE',
    beast: {
      vulpes: 'EL ZORRO DE ASCUAS', lepus: 'LA LIEBRE DE LUNA', serpens: 'LA SERPIENTE DE MAREA',
      delphinus: 'EL DELFÍN ESTELAR', columba: 'LA PALOMA HERALDO', lacerta: 'EL LAGARTO ZIGZAG',
      cygnus: 'EL CISNE DE LOS VIENTOS', pavo: 'EL PAVO REAL VELADO', cancer: 'EL CANGREJO SOMBRÍO',
      corvus: 'EL CUERVO HUECO', ursa: 'LA OSA DEL INVIERNO', aranea: 'LA VIUDA DE SEDA',
      aquila: 'EL ÁGUILA DEL TRUENO', lupus: 'EL LOBO HAMBRIENTO DE ESTRELLAS', monoceros: 'EL UNICORNIO DE CRISTAL',
      cassiopeia: 'LA REINA VANIDOSA', cetus: 'EL LEVIATÁN HUNDIDO', orion: 'EL CAZADOR DE LAS ESTRELLAS',
      strix: 'EL BÚHO DEL VACÍO', leo: 'EL LEÓN SOBERANO', taurus: 'EL TORO DE OJOS DE TORMENTA',
      scorpius: 'EL AGUIJÓN CARMESÍ', draco: 'EL DEVORAESTRELLAS', phoenix: 'LA PRIMERA LLAMA',
      centaurus: 'EL CENTAURO PRIMOGÉNITO', sagittarius: 'EL ARQUERO DEL CENIT',
    },
    cont: 'CONTINUAR', fightN: 'combate %1 de 5',
    quick: 'PARTIDA RÁPIDA', quickSub: 'cinco bestias, y luego el Devorador de Estrellas',
    daily: 'CAZA DIARIA', dailyOpen: 'un mismo cielo para todos · quedan %1',
    dailyDone: 'hoy: %1 · nuevo cielo en %2', cdHM: '%1 h %2 min', cdH: '%1 h', cdM: '%1 min',
    board: 'CLASIFICACIÓN', profile: 'PERFIL',
    versus: '⚔ VERSUS ⚔', versusSub: 'duelo bajo las estrellas',
    endWin: 'EL CIELO CALLA', endWinSub: 'todas las bestias estelares han caído · la noche es tuya',
    endLose: 'LAS ESTRELLAS TE RECLAMAN', endLoseSub: 'el ascenso termina aquí',
    stScore: 'puntos', stBest: 'récord %1', newBest: '✦ ¡NUEVO RÉCORD! ✦',
    stBeasts: 'bestias derribadas', stWords: 'palabras tejidas', stLetters: 'letras lanzadas',
    stFinest: 'mejor palabra', stBigHit: 'golpe supremo', stTime: 'duración', stSigils: 'sigilos',
    newRun: 'NUEVA PARTIDA', tryAgain: 'REINTENTAR', home: 'INICIO',
    shareBtn: '✶ COMPARTIR LA CAZA', shareCopied: '✶ COPIADO — A PRESUMIR', shareFail: '✶ ERROR AL COPIAR',
    sigilHead: '— ELIGE UN SIGILO —', vsSigilHead: '— UN SIGILO SE OFRECE —',
    rarityRare: 'RARO', rarityLegendary: 'LEGENDARIO',
    cdMS: '%1 min %2 s', cdS: '%1 s', cdD: '%1 d', cdDH: '%1 d %2 h',
    lbTitle: 'LO MEJOR DE LA NOCHE', lbDaily: 'DIARIA', lbWeekly: 'SEMANAL',
    lbNewSky: 'nuevo cielo en %1', lbWeekEnds: 'la semana termina en %1',
    lbLoading: 'consultando a las estrellas…', lbEmpty: 'aún no hay cazas registradas — sé el primero',
    lbYou: 'TÚ', lbYouRank: 'tu puesto: #%1 de %2',
    lbLocal: 'clasificación local — el cielo ancho es inalcanzable',
    dpOneSky: 'un mismo cielo para todos', dpAwait: 'el cielo de hoy te espera',
    dpPlayed: 'tu caza de hoy: %1', dpStreak: 'racha de caza: %1 días',
    dpPlay: 'COMENZAR LA CAZA', dpAgain: 'CAZAR DE NUEVO', dpTop: 'LO MEJOR DE HOY',
    newCamp: 'NUEVA CAMPAÑA', newCampSub: 'empieza de nuevo la larga noche',
    mapTitle: 'EL CIELO DE LA CAMPAÑA', mapHint: 'toca la constelación que brilla para entrar en combate', mapDest: 'fin del viaje',
    abandonTitle: '¿ABANDONAR EL ASCENSO?', abandonBody: 'tu punto de control en %1, combate %2, se desvanecerá en la oscuridad',
    abandonYes: 'ABANDONAR', abandonNo: 'SEGUIR SUBIENDO',
    zpTitle: 'ELIGE TU SIGNO', zpSub: 'nacido bajo un mismo cielo · cada signo dobla el ascenso',
    zpBegin: 'COMIENZA EL ASCENSO', zpSkip: 'subir sin signo · el ascenso clásico',
    zpPurify: 'toca una ficha para purificarla', zShell: 'EL CAPARAZÓN RESISTE',
    rating: 'clasificación estelar', rVeilRow: 'velar mi clasificación ante los demás', rVeiled: 'velada', rShown: 'visible',
    rHiddenCard: 'velada por la luz de las estrellas', rYourVeil: 'los demás ven tu clasificación velada',
    rt0: 'POLVO DE ESTRELLAS', rt1: 'ESTRELLA DE ASCUAS', rt2: 'ESTRELLA NACIENTE', rt3: 'ESTRELLA DORADA',
    rt4: 'NOVA', rt5: 'SUPERNOVA', rt6: 'CORONA CELESTE',
    zod: {
      aries: ['EL CARNERO', 'Cada combate abre con una embestida: la bestia recibe 8.'],
      taurus: ['EL TORO', 'El toro resiste: +15 de salud máxima al empezar el ascenso.'],
      gemini: ['LOS GEMELOS', 'Letras gemelas: las palabras que usan la misma letra dos veces hacen +10.'],
      cancer: ['EL CANGREJO', 'El caparazón resiste: el primer golpe de cada combate hace la mitad.'],
      leo: ['EL LEÓN', 'El rugido: las palabras de 6+ letras hacen +8.'],
      virgo: ['LA DONCELLA', 'Una vez por combate, toca tu signo y luego una ficha para purificarla en una letra nueva.'],
      libra: ['LA BALANZA', 'La balanza: las palabras con vocales y consonantes en equilibrio hacen +10.'],
      scorpio: ['EL ESCORPIÓN', 'El veneno crece con cada palabra — la bestia lo sufre tras cada lance.'],
      sagittarius: ['EL ARQUERO', 'La flecha presta: SCRY también golpea a la bestia por 6.'],
      capricorn: ['LA CABRA MARINA', 'El ascenso: las palabras hacen +1 por cada bestia derribada en la partida.'],
      aquarius: ['EL AGUADOR', 'Una vez por combate, caer bajo la mitad de salud vierte las aguas: cura 8.'],
      pisces: ['LOS PECES GEMELOS', 'La corriente profunda: las palabras tejidas a un lance del golpe hacen +30%.'],
    },
    sig: {
      quill: ['PLUMA DE ASCUAS', 'Cada palabra inflige +4 de daño.'],
      choir: ['CORO DE VOCALES', 'Cada vocal vale +2.'],
      runes: ['RUNAS DEL RÍO', 'S, R, E y T valen +2 cada una.'],
      salve: ['BÁLSAMO LUNAR', 'Las palabras de 5+ letras te curan 4.'],
      aegis: ['ÉGIDA DEL ALBA', '+20 de salud máxima, curada al instante.'],
      first: ['PRIMERA LUZ', 'Tu primera palabra de cada combate hace el doble.'],
      hush: ['RELOJ SUSURRANTE', 'Las bestias golpean un lance más tarde.'],
      comet: ['ESTELA DE COMETA', 'SCRY ya no acelera el golpe.'],
      shield: ['ESCUDO DE PLATA', 'Bloquea el primer golpe de cada combate.'],
      leech: ['BEBEDOR DE ROCÍO', 'Cada palabra te cura 1.'],
      longbow: ['ARCO ESTELAR', 'Las palabras de 6+ letras hacen +12.'],
      gilded: ['ALBA DORADA', 'Cada combate empieza con una ficha dorada.'],
      forge: ['FORJA ESTELAR', 'Las fichas forjadas suben un nivel más.'],
      blood: ['TINTA DE SANGRE', 'Tus palabras +25%. Los golpes de las bestias +25%.'],
      tome: ['TOMO SUSURRANTE', 'El ojo ◉ revela una palabra fuerte, una vez por combate.'],
      storm: ['ATATORMENTAS', 'Cada tercera palabra golpea dos veces.'],
      roots: ['RAÍCES TELÚRICAS', 'Las palabras hacen +2 por cada sigilo que tengas.'],
      ward: ['GUARDA LUNAR', 'Los golpes de las bestias hacen 3 menos, nunca menos de 1.'],
      echo: ['ECO DE RUINA', 'El daño sobrante hiere a la siguiente bestia.'],
      feather: ['PLUMA DE FÉNIX', 'Una vez por partida, sobrevive a la muerte con 1 de salud.'],
      eclipse: ['EL ECLIPSE', 'Los golpes de las bestias hacen solo la mitad.'],
      nova: ['CORONA DE NOVAS', 'Las palabras de 7+ letras hacen el doble.'],
      verse: ['EL VERSO SIN FIN', 'Las palabras hacen +1 por cada palabra tejida en la partida.'],
      meteor: ['CORAZÓN DEL METEORO', 'Derribar una bestia te restaura toda la salud.'],
    },
  },
  fr: {
    rotate: 'tourne ton téléphone à la verticale pour jouer',
    title: 'STARSPELL',
    tagline: 'tisse des mots · terrasse les bêtes stellaires',
    campaign: 'CAMPAGNE', campaignSub: 'quatre actes · une longue nuit',
    act1: 'ACTE I · LE CIEL DU PRÉ', act2: 'ACTE II · LA NUIT PROFONDE',
    act3: 'ACTE III · LA COURONNE DE L\'AUBE', act4: 'ACTE IV · LA CHASSE SANS FIN',
    tBoss: 'BOSS', tElite: 'ÉLITE',
    beast: {
      vulpes: 'LE RENARD DE BRAISE', lepus: 'LE LIÈVRE DE LUNE', serpens: 'LE SERPENT DES MARÉES',
      delphinus: 'LE DAUPHIN ÉTOILÉ', columba: 'LA COLOMBE MESSAGÈRE', lacerta: 'LE LÉZARD ZIGZAG',
      cygnus: 'LE CYGNE DES VENTS', pavo: 'LE PAON VOILÉ', cancer: 'LE CRABE DES TÉNÈBRES',
      corvus: 'LE CORBEAU CREUX', ursa: 'L\'OURSE DE L\'HIVER', aranea: 'LA VEUVE DE SOIE',
      aquila: 'L\'AIGLE DU TONNERRE', lupus: 'LE LOUP AFFAMÉ D\'ÉTOILES', monoceros: 'LA LICORNE DE VERRE',
      cassiopeia: 'LA REINE VANITEUSE', cetus: 'LE LÉVIATHAN NOYÉ', orion: 'LE CHASSEUR DES ÉTOILES',
      strix: 'LE HIBOU DU VIDE', leo: 'LE LION SOUVERAIN', taurus: 'LE TAUREAU À L\'ŒIL D\'ORAGE',
      scorpius: 'LE DARD CRAMOISI', draco: 'LE DÉVOREUR D\'ÉTOILES', phoenix: 'LA PREMIÈRE FLAMME',
      centaurus: 'LE CENTAURE PREMIER-NÉ', sagittarius: 'L\'ARCHER DU ZÉNITH',
    },
    cont: 'CONTINUER', fightN: 'combat %1 sur 5',
    quick: 'PARTIE RAPIDE', quickSub: 'cinq bêtes, puis le Dévoreur d’Étoiles',
    daily: 'CHASSE DU JOUR', dailyOpen: 'un même ciel, partagé par tous · %1 restant',
    dailyDone: 'aujourd’hui : %1 · prochain ciel dans %2', cdHM: '%1 h %2 min', cdH: '%1 h', cdM: '%1 min',
    board: 'CLASSEMENT', profile: 'PROFIL',
    versus: '⚔ VERSUS ⚔', versusSub: 'duel sous les étoiles',
    endWin: 'LE CIEL SE TAIT', endWinSub: 'toutes les bêtes stellaires sont tombées · la nuit est à toi',
    endLose: 'LES ÉTOILES TE RÉCLAMENT', endLoseSub: 'l’ascension s’arrête ici',
    stScore: 'score', stBest: 'record %1', newBest: '✦ NOUVEAU RECORD ! ✦',
    stBeasts: 'bêtes terrassées', stWords: 'mots tissés', stLetters: 'lettres lancées',
    stFinest: 'plus beau mot', stBigHit: 'coup suprême', stTime: 'durée', stSigils: 'sceaux',
    newRun: 'NOUVELLE PARTIE', tryAgain: 'RÉESSAYER', home: 'ACCUEIL',
    shareBtn: '✶ PARTAGER LA CHASSE', shareCopied: '✶ COPIÉ — VA FRIMER', shareFail: '✶ ÉCHEC DE LA COPIE',
    sigilHead: '— CHOISIS UN SCEAU —', vsSigilHead: '— UN SCEAU S’OFFRE À TOI —',
    rarityRare: 'RARE', rarityLegendary: 'LÉGENDAIRE',
    cdMS: '%1 min %2 s', cdS: '%1 s', cdD: '%1 j', cdDH: '%1 j %2 h',
    lbTitle: 'LE MEILLEUR DE LA NUIT', lbDaily: 'DU JOUR', lbWeekly: 'SEMAINE',
    lbNewSky: 'nouveau ciel dans %1', lbWeekEnds: 'la semaine s’achève dans %1',
    lbLoading: 'on consulte les étoiles…', lbEmpty: 'aucune chasse enregistrée — sois le premier',
    lbYou: 'TOI', lbYouRank: 'ta place : #%1 sur %2',
    lbLocal: 'classement local — le grand ciel est hors de portée',
    dpOneSky: 'un même ciel, partagé par tous', dpAwait: 'le ciel du jour t’attend',
    dpPlayed: 'ta chasse du jour : %1', dpStreak: 'série de chasse : %1 jours',
    dpPlay: 'LANCER LA CHASSE', dpAgain: 'CHASSER ENCORE', dpTop: 'LES MEILLEURS DU JOUR',
    newCamp: 'NOUVELLE CAMPAGNE', newCampSub: 'recommencer la longue nuit',
    mapTitle: 'LE CIEL DE LA CAMPAGNE', mapHint: 'touchez la constellation qui brille pour entrer au combat', mapDest: 'fin du voyage',
    abandonTitle: 'ABANDONNER L’ASCENSION ?', abandonBody: 'votre point de contrôle — %1, combat %2 — se perdra dans la nuit',
    abandonYes: 'ABANDONNER', abandonNo: 'CONTINUER À GRIMPER',
    zpTitle: 'CHOISIS TON SIGNE', zpSub: 'nés sous un même ciel · chaque signe infléchit l\'ascension',
    zpBegin: 'COMMENCER L\'ASCENSION', zpSkip: 'grimper sans signe · l\'ascension classique',
    zpPurify: 'touche une tuile pour la purifier', zShell: 'LA CARAPACE TIENT',
    rating: 'cote stellaire', rVeilRow: 'voiler ma cote aux autres', rVeiled: 'voilée', rShown: 'visible',
    rHiddenCard: 'voilée dans la lumière des étoiles', rYourVeil: 'les autres voient ta cote voilée',
    rt0: 'POUSSIÈRE D\'ÉTOILES', rt1: 'ÉTOILE DE BRAISE', rt2: 'ÉTOILE MONTANTE', rt3: 'ÉTOILE DORÉE',
    rt4: 'NOVA', rt5: 'SUPERNOVA', rt6: 'COURONNE CÉLESTE',
    zod: {
      aries: ['LE BÉLIER', 'Chaque combat s\'ouvre sur une charge : la bête subit 8.'],
      taurus: ['LE TAUREAU', 'Le taureau endure : +15 de santé maximale au départ de l\'ascension.'],
      gemini: ['LES JUMEAUX', 'Lettres jumelles : les mots utilisant deux fois la même lettre font +10.'],
      cancer: ['LE CRABE', 'La carapace tient : le premier coup de chaque combat est réduit de moitié.'],
      leo: ['LE LION', 'Le rugissement : les mots de 6 lettres ou plus font +8.'],
      virgo: ['LA VIERGE', 'Une fois par combat, touche ton signe puis une tuile pour la purifier en une nouvelle lettre.'],
      libra: ['LA BALANCE', 'La balance : les mots aux voyelles et consonnes en équilibre font +10.'],
      scorpio: ['LE SCORPION', 'Le venin croît à chaque mot — la bête le subit après chaque lancer.'],
      sagittarius: ['L\'ARCHER', 'La flèche encochée : SCRY frappe aussi la bête pour 6.'],
      capricorn: ['LA CHÈVRE DES MERS', 'L\'ascension : les mots font +1 par bête terrassée dans la partie.'],
      aquarius: ['LE PORTEUR D\'EAU', 'Une fois par combat, tomber sous la moitié de sa santé verse les eaux : soigne 8.'],
      pisces: ['LES POISSONS JUMEAUX', 'Le courant profond : les mots tissés à un lancer du coup font +30 %.'],
    },
    sig: {
      quill: ['PLUME DE BRAISE', 'Chaque mot inflige +4 dégâts.'],
      choir: ['CHŒUR DE VOYELLES', 'Chaque voyelle vaut +2.'],
      runes: ['RUNES DE LA RIVIÈRE', 'S, R, E et T valent +2 chacune.'],
      salve: ['BAUME DE LUNE', 'Les mots de 5 lettres et plus te soignent de 4.'],
      aegis: ['ÉGIDE DE L’AUBE', '+20 de santé max, soignée aussitôt.'],
      first: ['PREMIÈRE LUEUR', 'Ton premier mot de chaque combat frappe double.'],
      hush: ['SABLIER FEUTRÉ', 'Les bêtes frappent un lancer plus tard.'],
      comet: ['TRAÎNÉE DE COMÈTE', 'SCRY ne hâte plus la frappe.'],
      shield: ['BOUCLIER D’ARGENT', 'Bloque la première frappe de chaque combat.'],
      leech: ['BUVEUR DE ROSÉE', 'Chaque mot te soigne de 1.'],
      longbow: ['ARC ÉTOILÉ', 'Les mots de 6 lettres et plus font +12.'],
      gilded: ['AUBE DORÉE', 'Chaque combat commence avec une tuile dorée.'],
      forge: ['FORGE STELLAIRE', 'Les tuiles forgées gagnent un palier de plus.'],
      blood: ['ENCRE DE SANG', 'Tes mots +25%. Les frappes des bêtes +25%.'],
      tome: ['TOME MURMURANT', 'L’œil ◉ révèle un mot puissant, une fois par combat.'],
      storm: ['LIEUR D’ORAGES', 'Un mot sur trois frappe deux fois.'],
      roots: ['RACINES TELLURIQUES', 'Les mots font +2 par sceau que tu détiens.'],
      ward: ['GARDE DE LUNE', 'Les frappes des bêtes font 3 de moins, jamais sous 1.'],
      echo: ['ÉCHO DE RUINE', 'Les dégâts en excès blessent la bête suivante.'],
      feather: ['PLUME DE PHÉNIX', 'Une fois par partie, survis à la mort avec 1 de santé.'],
      eclipse: ['L’ÉCLIPSE', 'Les frappes des bêtes ne font que la moitié.'],
      nova: ['COURONNE DE NOVAE', 'Les mots de 7 lettres et plus frappent double.'],
      verse: ['LE VERS SANS FIN', 'Les mots font +1 par mot tissé dans la partie.'],
      meteor: ['CŒUR DU MÉTÉORE', 'Terrasser une bête te rend toute ta santé.'],
    },
  },
  pt: {
    rotate: 'gire o celular na vertical para jogar',
    title: 'STARSPELL',
    tagline: 'teça palavras · derrube as feras estelares',
    campaign: 'CAMPANHA', campaignSub: 'quatro atos · uma longa noite',
    act1: 'ATO I · O CÉU DO PRADO', act2: 'ATO II · A NOITE PROFUNDA',
    act3: 'ATO III · A COROA DA ALVORADA', act4: 'ATO IV · A CAÇADA SEM FIM',
    tBoss: 'CHEFE', tElite: 'ELITE',
    beast: {
      vulpes: 'A RAPOSA DE BRASAS', lepus: 'A LEBRE ENLUARADA', serpens: 'A SERPENTE DAS MARÉS',
      delphinus: 'O GOLFINHO ESTELAR', columba: 'A POMBA ARAUTO', lacerta: 'O LAGARTO ZIGUEZAGUE',
      cygnus: 'O CISNE DOS VENTOS', pavo: 'O PAVÃO VELADO', cancer: 'O CARANGUEJO SOMBRIO',
      corvus: 'O CORVO OCO', ursa: 'A URSA DO INVERNO', aranea: 'A VIÚVA DE SEDA',
      aquila: 'A ÁGUIA DO TROVÃO', lupus: 'O LOBO FAMINTO DE ESTRELAS', monoceros: 'O UNICÓRNIO DE VIDRO',
      cassiopeia: 'A RAINHA VAIDOSA', cetus: 'O LEVIATÃ AFUNDADO', orion: 'O CAÇADOR ESTELAR',
      strix: 'A CORUJA DO VAZIO', leo: 'O LEÃO SOBERANO', taurus: 'O TOURO DE OLHOS DE TEMPESTADE',
      scorpius: 'O FERRÃO CARMESIM', draco: 'O DEVORADOR DE ESTRELAS', phoenix: 'A PRIMEIRA CHAMA',
      centaurus: 'O CENTAURO PRIMOGÉNITO', sagittarius: 'O ARQUEIRO DO ZÉNITE',
    },
    cont: 'CONTINUAR', fightN: 'luta %1 de 5',
    quick: 'JOGO RÁPIDO', quickSub: 'cinco feras, depois o Devorador de Estrelas',
    daily: 'CAÇADA DIÁRIA', dailyOpen: 'um só céu, de todos · faltam %1',
    dailyDone: 'hoje: %1 · novo céu em %2', cdHM: '%1 h %2 min', cdH: '%1 h', cdM: '%1 min',
    board: 'PLACAR', profile: 'PERFIL',
    versus: '⚔ VERSUS ⚔', versusSub: 'duelo sob as estrelas',
    endWin: 'O CÉU SILENCIA', endWinSub: 'todas as feras estelares caíram · a noite é sua',
    endLose: 'AS ESTRELAS TE RECLAMAM', endLoseSub: 'a subida termina aqui',
    stScore: 'pontos', stBest: 'recorde %1', newBest: '✦ NOVO RECORDE! ✦',
    stBeasts: 'feras derrubadas', stWords: 'palavras tecidas', stLetters: 'letras lançadas',
    stFinest: 'melhor palavra', stBigHit: 'golpe supremo', stTime: 'duração', stSigils: 'sígilos',
    newRun: 'NOVA PARTIDA', tryAgain: 'TENTAR DE NOVO', home: 'INÍCIO',
    shareBtn: '✶ COMPARTILHAR A CAÇADA', shareCopied: '✶ COPIADO — VÁ SE GABAR', shareFail: '✶ FALHA AO COPIAR',
    sigilHead: '— ESCOLHA UM SÍGILO —', vsSigilHead: '— UM SÍGILO SE OFERECE —',
    rarityRare: 'RARO', rarityLegendary: 'LENDÁRIO',
    cdMS: '%1 min %2 s', cdS: '%1 s', cdD: '%1 d', cdDH: '%1 d %2 h',
    lbTitle: 'O MELHOR DA NOITE', lbDaily: 'DIÁRIA', lbWeekly: 'SEMANAL',
    lbNewSky: 'novo céu em %1', lbWeekEnds: 'a semana termina em %1',
    lbLoading: 'consultando as estrelas…', lbEmpty: 'nenhuma caçada registrada — seja o primeiro',
    lbYou: 'VOCÊ', lbYouRank: 'seu lugar: #%1 de %2',
    lbLocal: 'placar local — o céu maior está fora de alcance',
    dpOneSky: 'um só céu, de todos', dpAwait: 'o céu de hoje espera por você',
    dpPlayed: 'sua caçada de hoje: %1', dpStreak: 'sequência de caçadas: %1 dias',
    dpPlay: 'INICIAR A CAÇADA', dpAgain: 'CAÇAR DE NOVO', dpTop: 'O MELHOR DE HOJE',
    newCamp: 'NOVA CAMPANHA', newCampSub: 'recomeçar a longa noite',
    mapTitle: 'O CÉU DA CAMPANHA', mapHint: 'toque na constelação brilhante para entrar na luta', mapDest: 'fim da jornada',
    abandonTitle: 'ABANDONAR A SUBIDA?', abandonBody: 'seu ponto de controle em %1, luta %2, se apagará na escuridão',
    abandonYes: 'ABANDONAR', abandonNo: 'SEGUIR SUBINDO',
    zpTitle: 'ESCOLHE O TEU SIGNO', zpSub: 'nascidos sob um só céu · cada signo verga a subida',
    zpBegin: 'COMEÇAR A SUBIDA', zpSkip: 'subir sem signo · a subida clássica',
    zpPurify: 'toca numa peça para a purificar', zShell: 'A CARAPAÇA AGUENTA',
    rating: 'classificação estelar', rVeilRow: 'velar minha classificação dos outros', rVeiled: 'velada', rShown: 'visível',
    rHiddenCard: 'velada na luz das estrelas', rYourVeil: 'os outros veem sua classificação velada',
    rt0: 'POEIRA ESTELAR', rt1: 'ESTRELA DE BRASA', rt2: 'ESTRELA ASCENDENTE', rt3: 'ESTRELA DOURADA',
    rt4: 'NOVA', rt5: 'SUPERNOVA', rt6: 'COROA CELESTE',
    zod: {
      aries: ['O CARNEIRO', 'Cada combate abre com uma investida: a fera sofre 8.'],
      taurus: ['O TOURO', 'O touro resiste: +15 de vida máxima no início da subida.'],
      gemini: ['OS GÉMEOS', 'Letras gémeas: palavras que usam a mesma letra duas vezes causam +10.'],
      cancer: ['O CARANGUEJO', 'A carapaça aguenta: o primeiro golpe de cada combate causa metade.'],
      leo: ['O LEÃO', 'O rugido: palavras de 6+ letras causam +8.'],
      virgo: ['A DONZELA', 'Uma vez por combate, toca no teu signo e depois numa peça para a purificar numa letra nova.'],
      libra: ['A BALANÇA', 'A balança: palavras com vogais e consoantes em equilíbrio causam +10.'],
      scorpio: ['O ESCORPIÃO', 'O veneno cresce a cada palavra — a fera sofre-o após cada lance.'],
      sagittarius: ['O ARQUEIRO', 'A flecha pronta: SCRY também atinge a fera por 6.'],
      capricorn: ['A CABRA-MARINHA', 'A subida: palavras causam +1 por cada fera abatida na partida.'],
      aquarius: ['O AGUADEIRO', 'Uma vez por combate, cair abaixo de metade da vida verte as águas: cura 8.'],
      pisces: ['OS PEIXES GÉMEOS', 'A corrente profunda: palavras tecidas a um lance do golpe causam +30%.'],
    },
    sig: {
      quill: ['PENA DE BRASA', 'Cada palavra causa +4 de dano.'],
      choir: ['CORO DE VOGAIS', 'Cada vogal vale +2.'],
      runes: ['RUNAS DO RIO', 'S, R, E e T valem +2 cada.'],
      salve: ['BÁLSAMO LUNAR', 'Palavras de 5+ letras curam 4.'],
      aegis: ['ÉGIDE DA ALVORADA', '+20 de vida máxima, curada na hora.'],
      first: ['PRIMEIRA LUZ', 'Sua primeira palavra de cada luta causa o dobro.'],
      hush: ['AMPULHETA QUIETA', 'As feras golpeiam um lance mais tarde.'],
      comet: ['RASTRO DE COMETA', 'SCRY não apressa mais o golpe.'],
      shield: ['ESCUDO DE PRATA', 'Bloqueia o primeiro golpe de cada luta.'],
      leech: ['BEBEDOR DE ORVALHO', 'Cada palavra cura 1.'],
      longbow: ['ARCO ESTELAR', 'Palavras de 6+ letras causam +12.'],
      gilded: ['ALVORADA DOURADA', 'Cada luta começa com uma peça dourada.'],
      forge: ['FORJA ESTELAR', 'Peças forjadas sobem um nível a mais.'],
      blood: ['TINTA DE SANGUE', 'Suas palavras +25%. Golpes das feras +25%.'],
      tome: ['TOMO SUSSURRANTE', 'O olho ◉ revela uma palavra forte, uma vez por luta.'],
      storm: ['PRENDE-TORMENTAS', 'Cada terceira palavra golpeia duas vezes.'],
      roots: ['RAÍZES TELÚRICAS', 'Palavras causam +2 por sígilo que você tiver.'],
      ward: ['GUARDA LUNAR', 'Golpes das feras causam 3 a menos, nunca abaixo de 1.'],
      echo: ['ECO DA RUÍNA', 'O dano excedente fere a próxima fera.'],
      feather: ['PENA DE FÊNIX', 'Uma vez por partida, sobreviva à morte com 1 de vida.'],
      eclipse: ['O ECLIPSE', 'Golpes das feras causam só a metade.'],
      nova: ['COROA DE NOVAS', 'Palavras de 7+ letras causam o dobro.'],
      verse: ['O VERSO SEM FIM', 'Palavras causam +1 por palavra tecida na partida.'],
      meteor: ['CORAÇÃO DO METEORO', 'Derrubar uma fera restaura toda a sua vida.'],
    },
  },
  de: {
    rotate: 'dreh dein Handy ins Hochformat, um zu spielen',
    title: 'STARSPELL',
    tagline: 'webe Worte · fälle die Sternenbestien',
    campaign: 'KAMPAGNE', campaignSub: 'vier Akte · eine lange Nacht',
    act1: 'AKT I · DER WIESENHIMMEL', act2: 'AKT II · DIE TIEFE NACHT',
    act3: 'AKT III · DIE KRONE DER MORGENRÖTE', act4: 'AKT IV · DIE ENDLOSE JAGD',
    tBoss: 'BOSS', tElite: 'ELITE',
    beast: {
      vulpes: 'DER GLUTFUCHS', lepus: 'DER MONDHASE', serpens: 'DIE GEZEITENSCHLANGE',
      delphinus: 'DER STERNENDELPHIN', columba: 'DIE BOTENTAUBE', lacerta: 'DIE ZICKZACK-ECHSE',
      cygnus: 'DER WINDSCHWAN', pavo: 'DER VERSCHLEIERTE PFAU', cancer: 'DIE DÜSTERKRABBE',
      corvus: 'DER HOHLE RABE', ursa: 'DIE WINTERBÄRIN', aranea: 'DIE SEIDENWITWE',
      aquila: 'DER DONNERADLER', lupus: 'DER STERNHUNGRIGE WOLF', monoceros: 'DAS GLASEINHORN',
      cassiopeia: 'DIE EITLE KÖNIGIN', cetus: 'DER ERTRUNKENE LEVIATHAN', orion: 'DER STERNGEBUNDENE JÄGER',
      strix: 'DIE EULE DER LEERE', leo: 'DER LÖWENFÜRST', taurus: 'DER STURMÄUGIGE STIER',
      scorpius: 'DER KARMESINSTACHEL', draco: 'DER STERNENFRESSER', phoenix: 'DIE ERSTE FLAMME',
      centaurus: 'DER ERSTGEBORENE ZENTAUR', sagittarius: 'DER ZENIT-SCHÜTZE',
    },
    cont: 'WEITER', fightN: 'Kampf %1 von 5',
    quick: 'SCHNELLES SPIEL', quickSub: 'fünf Bestien, dann der Sternenfresser',
    daily: 'TAGESJAGD', dailyOpen: 'ein Himmel, geteilt mit allen · noch %1',
    dailyDone: 'heute: %1 · neuer Himmel in %2', cdHM: '%1 Std %2 Min', cdH: '%1 Std', cdM: '%1 Min',
    board: 'BESTENLISTE', profile: 'PROFIL',
    versus: '⚔ VERSUS ⚔', versusSub: 'Duell unter Sternen',
    endWin: 'DER HIMMEL SCHWEIGT', endWinSub: 'alle Sternenbestien sind gefallen · die Nacht gehört dir',
    endLose: 'DIE STERNE HOLEN DICH', endLoseSub: 'der Aufstieg endet hier',
    stScore: 'Punkte', stBest: 'Rekord %1', newBest: '✦ NEUER REKORD! ✦',
    stBeasts: 'Bestien gefällt', stWords: 'Worte gewoben', stLetters: 'Buchstaben gewirkt',
    stFinest: 'schönstes Wort', stBigHit: 'stärkster Treffer', stTime: 'Laufzeit', stSigils: 'Sigel',
    newRun: 'NEUER LAUF', tryAgain: 'NOCHMAL', home: 'START',
    shareBtn: '✶ JAGD TEILEN', shareCopied: '✶ KOPIERT — GEH PRAHLEN', shareFail: '✶ KOPIEREN FEHLGESCHLAGEN',
    sigilHead: '— WÄHLE EIN SIGEL —', vsSigilHead: '— EIN SIGEL BIETET SICH AN —',
    rarityRare: 'SELTEN', rarityLegendary: 'LEGENDÄR',
    cdMS: '%1 Min %2 Sek', cdS: '%1 Sek', cdD: '%1 T', cdDH: '%1 T %2 Std',
    lbTitle: 'DIE BESTEN DER NACHT', lbDaily: 'TÄGLICH', lbWeekly: 'WOCHE',
    lbNewSky: 'neuer Himmel in %1', lbWeekEnds: 'Woche endet in %1',
    lbLoading: 'die Sterne werden befragt…', lbEmpty: 'noch keine Jagd verzeichnet — sei die erste',
    lbYou: 'DU', lbYouRank: 'dein Platz: #%1 von %2',
    lbLocal: 'lokale Wertung — der weite Himmel ist unerreichbar',
    dpOneSky: 'ein Himmel, geteilt mit allen', dpAwait: 'der heutige Himmel wartet auf dich',
    dpPlayed: 'deine Jagd heute: %1', dpStreak: 'Jagdserie: %1 Tage',
    dpPlay: 'ZUR JAGD', dpAgain: 'ERNEUT JAGEN', dpTop: 'DIE BESTEN HEUTE',
    newCamp: 'NEUE KAMPAGNE', newCampSub: 'die lange Nacht von vorn beginnen',
    mapTitle: 'DER KAMPAGNENHIMMEL', mapHint: 'tippe auf das leuchtende Sternbild, um zu kämpfen', mapDest: 'Ende der Reise',
    abandonTitle: 'DEN AUFSTIEG AUFGEBEN?', abandonBody: 'dein Speicherpunkt — %1, Kampf %2 — verblasst im Dunkel',
    abandonYes: 'AUFGEBEN', abandonNo: 'WEITER KLETTERN',
    zpTitle: 'WÄHLE DEIN ZEICHEN', zpSub: 'unter einem Himmel geboren · jedes Zeichen formt den Aufstieg',
    zpBegin: 'DEN AUFSTIEG BEGINNEN', zpSkip: 'ohne Zeichen klettern · der klassische Aufstieg',
    zpPurify: 'tippe eine Kachel an, um sie zu läutern', zShell: 'DER PANZER HÄLT',
    rating: 'Sternenwertung', rVeilRow: 'meine Wertung vor anderen verhüllen', rVeiled: 'verhüllt', rShown: 'sichtbar',
    rHiddenCard: 'im Sternenlicht verhüllt', rYourVeil: 'andere sehen deine Wertung verhüllt',
    rt0: 'STERNENSTAUB', rt1: 'GLUTSTERN', rt2: 'AUFGEHENDER STERN', rt3: 'GOLDSTERN',
    rt4: 'NOVA', rt5: 'SUPERNOVA', rt6: 'HIMMELSKRONE',
    zod: {
      aries: ['DER WIDDER', 'Jeder Kampf beginnt mit einem Rammstoß: das Biest erleidet 8.'],
      taurus: ['DER STIER', 'Der Stier hält stand: +15 maximale Gesundheit zu Beginn des Aufstiegs.'],
      gemini: ['DIE ZWILLINGE', 'Zwillingsbuchstaben: Wörter, die denselben Buchstaben zweimal nutzen, machen +10.'],
      cancer: ['DER KREBS', 'Der Panzer hält: der erste Schlag jedes Kampfes richtet nur die Hälfte an.'],
      leo: ['DER LÖWE', 'Das Brüllen: Wörter mit 6+ Buchstaben machen +8.'],
      virgo: ['DIE JUNGFRAU', 'Einmal pro Kampf: tippe dein Zeichen und dann eine Kachel, um sie zu einem neuen Buchstaben zu läutern.'],
      libra: ['DIE WAAGE', 'Die Waage: Wörter mit Vokalen und Konsonanten im Gleichgewicht machen +10.'],
      scorpio: ['DER SKORPION', 'Das Gift wächst mit jedem Wort — das Biest erleidet es nach jedem Wurf.'],
      sagittarius: ['DER SCHÜTZE', 'Der gespannte Pfeil: SCRY trifft das Biest zusätzlich für 6.'],
      capricorn: ['DIE MEERZIEGE', 'Der Aufstieg: Wörter machen +1 für jedes gefällte Biest dieser Partie.'],
      aquarius: ['DER WASSERTRÄGER', 'Einmal pro Kampf: fällst du unter die halbe Gesundheit, strömen die Wasser — heilt 8.'],
      pisces: ['DIE ZWILLINGSFISCHE', 'Die tiefe Strömung: Wörter, einen Wurf vor dem Schlag gewoben, machen +30%.'],
    },
    sig: {
      quill: ['GLUTFEDER', 'Jedes Wort verursacht +4 Schaden.'],
      choir: ['VOKALCHOR', 'Jeder Vokal zählt +2.'],
      runes: ['FLUSSRUNEN', 'S, R, E und T zählen je +2.'],
      salve: ['MONDSALBE', 'Worte mit 5+ Buchstaben heilen dich um 4.'],
      aegis: ['ÄGIS DER DÄMMERUNG', '+20 maximale Gesundheit, sofort geheilt.'],
      first: ['ERSTES LICHT', 'Dein erstes Wort jedes Kampfes zählt doppelt.'],
      hush: ['STILLES STUNDENGLAS', 'Bestien schlagen einen Wurf später zu.'],
      comet: ['KOMETENSCHWEIF', 'SCRY beschleunigt den Schlag nicht mehr.'],
      shield: ['SILBERSCHILD', 'Blockt den ersten Schlag jedes Kampfes.'],
      leech: ['TAUTRINKER', 'Jedes Wort heilt dich um 1.'],
      longbow: ['STERNENBOGEN', 'Worte mit 6+ Buchstaben machen +12.'],
      gilded: ['GOLDENE DÄMMERUNG', 'Jeder Kampf beginnt mit einem vergoldeten Stein.'],
      forge: ['STERNENSCHMIEDE', 'Geschmiedete Steine kommen eine Stufe höher.'],
      blood: ['BLUTTINTE', 'Deine Worte +25%. Bestienschläge +25%.'],
      tome: ['FLÜSTERNDER FOLIANT', 'Das Auge ◉ enthüllt ein starkes Wort, einmal pro Kampf.'],
      storm: ['STURMBINDER', 'Jedes dritte Wort schlägt zweimal zu.'],
      roots: ['LEYLINIEN-WURZELN', 'Worte machen +2 je Sigel, das du trägst.'],
      ward: ['MONDWACHT', 'Bestienschläge machen 3 weniger, nie unter 1.'],
      echo: ['ECHO DES VERFALLS', 'Überschüssiger Schaden trifft die nächste Bestie.'],
      feather: ['PHÖNIXFEDER', 'Einmal pro Lauf überlebst du den Tod mit 1 Gesundheit.'],
      eclipse: ['DIE FINSTERNIS', 'Bestienschläge machen nur die Hälfte.'],
      nova: ['KRONE DER NOVAE', 'Worte mit 7+ Buchstaben zählen doppelt.'],
      verse: ['DER ENDLOSE VERS', 'Worte machen +1 je gewobenem Wort dieses Laufs.'],
      meteor: ['HERZ DES METEORS', 'Eine gefällte Bestie heilt dich vollständig.'],
    },
  },
  ja: {
    rotate: 'タテ画面にして遊んでね',
    title: 'STARSPELL',
    tagline: '言葉を紡ぎ、星獣を討て',
    campaign: 'キャンペーン', campaignSub: '四幕・長き一夜',
    act1: '第一幕・草原の空', act2: '第二幕・深き夜',
    act3: '第三幕・暁の冠', act4: '第四幕・果てなき狩り',
    tBoss: 'ボス', tElite: '精鋭',
    beast: {
      vulpes: '燠火の狐', lepus: '月光の兎', serpens: '潮の大蛇',
      delphinus: '星明かりの海豚', columba: '先触れの鳩', lacerta: '稲妻の蜥蜴',
      cygnus: '風渡りの白鳥', pavo: '面紗の孔雀', cancer: '闇の蟹',
      corvus: '虚ろの鴉', ursa: '冬の熊', aranea: '絹の女郎蜘蛛',
      aquila: '雷鳴の鷲', lupus: '星に飢えた狼', monoceros: '硝子の一角獣',
      cassiopeia: '驕れる女王', cetus: '沈んだ海の巨獣', orion: '星縛りの狩人',
      strix: '虚空の梟', leo: '君臨の獅子', taurus: '嵐眼の牡牛',
      scorpius: '深紅の毒針', draco: '星喰い', phoenix: '始まりの炎',
      centaurus: '長子のケンタウロス', sagittarius: '天頂の射手',
    },
    cont: 'つづきから', fightN: '戦い %1 / 5',
    quick: 'クイックプレイ', quickSub: '五体の獣、そして星喰い',
    daily: 'デイリーハント', dailyOpen: 'ひとつの空を、みんなで · 残り%1',
    dailyDone: '今日: %1 · 次の空まで%2', cdHM: '%1時間%2分', cdH: '%1時間', cdM: '%1分',
    board: 'ランキング', profile: 'プロフィール',
    versus: '⚔ VS ⚔', versusSub: '星空の下の決闘',
    endWin: '空は静まった', endWinSub: '星獣はすべて討たれた · 今夜は君のもの',
    endLose: '星々が君を連れ去る', endLoseSub: '昇りはここで終わる',
    stScore: 'スコア', stBest: '自己ベスト %1', newBest: '✦ 新記録! ✦',
    stBeasts: '討った星獣', stWords: '紡いだ言葉', stLetters: '放った文字',
    stFinest: '最高の言葉', stBigHit: '最大の一撃', stTime: 'プレイ時間', stSigils: '所持シジル',
    newRun: 'もう一度', tryAgain: '再挑戦', home: 'ホーム',
    shareBtn: '✶ 今日の狩りをシェア', shareCopied: '✶ コピーした · 自慢しよう', shareFail: '✶ コピー失敗',
    sigilHead: '— シジルを選べ —', vsSigilHead: '— シジルが呼んでいる —',
    rarityRare: 'レア', rarityLegendary: '伝説',
    cdMS: '%1分%2秒', cdS: '%1秒', cdD: '%1日', cdDH: '%1日%2時間',
    lbTitle: '今夜の精鋭', lbDaily: 'デイリー', lbWeekly: '週間',
    lbNewSky: '次の空まで%1', lbWeekEnds: '今週の締切まで%1',
    lbLoading: '星に問い合わせ中…', lbEmpty: 'まだ記録なし · 一番乗りになろう',
    lbYou: 'あなた', lbYouRank: 'あなたの順位: %1位 / %2人',
    lbLocal: 'ローカル記録 · 大空には届かない',
    dpOneSky: 'ひとつの空を、みんなで', dpAwait: '今日の空が待っている',
    dpPlayed: '今日の狩り: %1', dpStreak: '%1日連続の狩り',
    dpPlay: '狩りを始める', dpAgain: 'もう一度狩る', dpTop: '本日の精鋭',
    newCamp: '新しいキャンペーン', newCampSub: '長い夜をはじめからやり直す',
    mapTitle: 'キャンペーンの星図', mapHint: '輝く星座に触れて戦いへ', mapDest: '旅の果て',
    abandonTitle: '登攀を捨てますか？', abandonBody: '%1・戦い%2のチェックポイントが闇に消えます',
    abandonYes: '捨てる', abandonNo: '登り続ける',
    zpTitle: '星座を選べ', zpSub: 'ひとつの空の下に生まれ · 星座が登りを変える',
    zpBegin: '登りを始める', zpSkip: '星座なしで登る · クラシック',
    zpPurify: 'タイルをタップして浄化', zShell: '甲羅が守った',
    rating: '星の格付け', rVeilRow: '格付けを他の人から隠す', rVeiled: '非表示', rShown: '表示',
    rHiddenCard: '星明かりに包まれている', rYourVeil: '他の人にはあなたの格付けは見えません',
    rt0: '星屑', rt1: '燠火の星', rt2: '昇る星', rt3: '黄金の星',
    rt4: '新星', rt5: '超新星', rt6: '天の冠',
    zod: {
      aries: ['牡羊', '各戦闘の開幕に突進：獣に8ダメージ。'],
      taurus: ['牡牛', '牡牛は耐える：登り開始時に最大体力+15。'],
      gemini: ['双子', '双子の文字：同じ文字を2回使う言葉は+10。'],
      cancer: ['蟹', '甲羅の守り：各戦闘の最初の一撃は半減。'],
      leo: ['獅子', '咆哮：6文字以上の言葉は+8。'],
      virgo: ['乙女', '戦闘ごとに一度、星座をタップしてからタイルをタップすると新しい文字に浄化。'],
      libra: ['天秤', '天秤：母音と子音が釣り合う言葉は+10。'],
      scorpio: ['蠍', '毒は言葉ごとに募り、詠唱のたびに獣を蝕む。'],
      sagittarius: ['射手', 'つがえた矢：SCRYが獣に6ダメージを与える。'],
      capricorn: ['山羊', '登攀：討った獣1体につき言葉が+1。'],
      aquarius: ['水瓶', '戦闘ごとに一度、体力が半分を切ると水が注がれ8回復。'],
      pisces: ['双魚', '深い潮流：一撃まで残り1詠唱で紡いだ言葉は+30%。'],
    },
    sig: {
      quill: ['燠火の羽根ペン', 'すべての言葉のダメージ+4。'],
      choir: ['母音の聖歌隊', '母音1つにつき+2。'],
      runes: ['川のルーン', 'S・R・E・Tがそれぞれ+2。'],
      salve: ['月の軟膏', '5文字以上の言葉で4回復。'],
      aegis: ['暁のイージス', '最大体力+20、今すぐ全回復。'],
      first: ['一番星の光', '各戦闘の最初の言葉が2倍。'],
      hush: ['静寂の砂時計', '星獣の一撃が1回遅れる。'],
      comet: ['彗星の尾', 'SCRYで一撃が早まらなくなる。'],
      shield: ['白銀の盾', '各戦闘の最初の一撃を防ぐ。'],
      leech: ['露飲み', '言葉を放つたび1回復。'],
      longbow: ['星の長弓', '6文字以上の言葉に+12。'],
      gilded: ['黄金の暁', '各戦闘が金のタイル付きで始まる。'],
      forge: ['星の炉', '鍛えたタイルが1段上のものになる。'],
      blood: ['血の墨', '言葉+25%。星獣の一撃も+25%。'],
      tome: ['ささやきの書', '瞳◉が強い言葉を教える。戦闘ごとに1回。'],
      storm: ['嵐縛り', '3回ごとの言葉が2回打つ。'],
      roots: ['地脈の根', '持つシジル1つにつき言葉+2。'],
      ward: ['月の護り', '星獣の一撃が3減る。最低1。'],
      echo: ['破滅の残響', '余剰ダメージが次の星獣に及ぶ。'],
      feather: ['不死鳥の羽根', '1回だけ、体力1で死を免れる。'],
      eclipse: ['日蝕', '星獣の一撃が半分になる。'],
      nova: ['新星の冠', '7文字以上の言葉が2倍。'],
      verse: ['果てなき詩', '紡いだ言葉1つにつき+1。'],
      meteor: ['流星の心臓', '星獣を討つと体力が全回復。'],
    },
  },
  ko: {
    rotate: '세로 화면으로 돌려서 플레이하세요',
    title: 'STARSPELL',
    tagline: '단어를 엮어 별짐승을 쓰러뜨려라',
    campaign: '캠페인', campaignSub: '4막 · 기나긴 하룻밤',
    act1: '제1막 · 초원의 하늘', act2: '제2막 · 깊은 밤',
    act3: '제3막 · 새벽의 왕관', act4: '제4막 · 끝없는 사냥',
    tBoss: '보스', tElite: '정예',
    beast: {
      vulpes: '잉걸불 여우', lepus: '달빛 토끼', serpens: '조수의 뱀',
      delphinus: '별빛 돌고래', columba: '전령 비둘기', lacerta: '지그재그 도마뱀',
      cygnus: '바람길 백조', pavo: '베일 쓴 공작', cancer: '어둠의 게',
      corvus: '텅 빈 까마귀', ursa: '겨울 곰', aranea: '비단 미망인',
      aquila: '천둥 독수리', lupus: '별에 굶주린 늑대', monoceros: '유리 유니콘',
      cassiopeia: '오만한 여왕', cetus: '가라앉은 리바이어던', orion: '별에 묶인 사냥꾼',
      strix: '공허의 올빼미', leo: '군림하는 사자', taurus: '폭풍눈 황소',
      scorpius: '진홍의 독침', draco: '별을 삼키는 자', phoenix: '최초의 불꽃',
      centaurus: '첫째 켄타우로스', sagittarius: '천정의 궁수',
    },
    cont: '이어하기', fightN: '전투 %1 / 5',
    quick: '빠른 대전', quickSub: '다섯 짐승, 그리고 별포식자',
    daily: '오늘의 사냥', dailyOpen: '모두가 함께 보는 하나의 하늘 · %1 남음',
    dailyDone: '오늘: %1 · 다음 하늘까지 %2', cdHM: '%1시간 %2분', cdH: '%1시간', cdM: '%1분',
    board: '리더보드', profile: '프로필',
    versus: '⚔ VS ⚔', versusSub: '별빛 아래 결투',
    endWin: '하늘이 고요해졌다', endWinSub: '별짐승을 모두 쓰러뜨렸다 · 이 밤은 너의 것',
    endLose: '별들이 너를 삼켰다', endLoseSub: '승천은 여기서 끝난다',
    stScore: '점수', stBest: '최고 기록 %1', newBest: '✦ 신기록! ✦',
    stBeasts: '쓰러뜨린 짐승', stWords: '엮은 단어', stLetters: '쓴 글자',
    stFinest: '최고의 단어', stBigHit: '최대 일격', stTime: '플레이 시간', stSigils: '인장',
    newRun: '새 도전', tryAgain: '재도전', home: '홈',
    shareBtn: '✶ 오늘의 사냥 공유', shareCopied: '✶ 복사 완료 · 자랑하세요', shareFail: '✶ 복사 실패',
    sigilHead: '— 인장을 선택하라 —', vsSigilHead: '— 인장이 자신을 바친다 —',
    rarityRare: '희귀', rarityLegendary: '전설',
    cdMS: '%1분 %2초', cdS: '%1초', cdD: '%1일', cdDH: '%1일 %2시간',
    lbTitle: '오늘 밤의 정예', lbDaily: '일간', lbWeekly: '주간',
    lbNewSky: '다음 하늘까지 %1', lbWeekEnds: '주간 마감까지 %1',
    lbLoading: '별에게 묻는 중…', lbEmpty: '아직 기록 없음 · 첫 사냥꾼이 되세요',
    lbYou: '나', lbYouRank: '내 순위: %1위 / %2명',
    lbLocal: '로컬 기록 · 넓은 하늘에 닿을 수 없음',
    dpOneSky: '모두가 함께 보는 하나의 하늘', dpAwait: '오늘의 하늘이 기다립니다',
    dpPlayed: '오늘의 사냥: %1', dpStreak: '%1일 연속 사냥',
    dpPlay: '사냥 시작', dpAgain: '다시 사냥', dpTop: '오늘의 정예',
    newCamp: '새 캠페인', newCampSub: '기나긴 밤을 처음부터 다시',
    mapTitle: '캠페인 별지도', mapHint: '빛나는 별자리를 눌러 전투로', mapDest: '여정의 끝',
    abandonTitle: '등반을 포기할까요?', abandonBody: '%1 · 전투 %2 체크포인트가 어둠 속으로 사라집니다',
    abandonYes: '포기', abandonNo: '계속 오르기',
    zpTitle: '별자리를 선택하라', zpSub: '한 하늘 아래 태어나 · 별자리가 등반을 바꾼다',
    zpBegin: '등반 시작', zpSkip: '별자리 없이 오르기 · 클래식',
    zpPurify: '타일을 눌러 정화하세요', zShell: '껍질이 버텼다',
    rating: '별 등급', rVeilRow: '내 등급을 다른 사람에게 가리기', rVeiled: '가림', rShown: '공개',
    rHiddenCard: '별빛에 가려져 있음', rYourVeil: '다른 사람에게는 등급이 가려져 보입니다',
    rt0: '별먼지', rt1: '잉걸불 별', rt2: '떠오르는 별', rt3: '금빛 별',
    rt4: '신성', rt5: '초신성', rt6: '천상의 왕관',
    zod: {
      aries: ['양자리', '전투 시작마다 들이받기: 짐승이 8 피해를 입는다.'],
      taurus: ['황소자리', '황소의 인내: 등반 시작 시 최대 체력 +15.'],
      gemini: ['쌍둥이자리', '쌍둥이 글자: 같은 글자를 두 번 쓴 단어는 +10.'],
      cancer: ['게자리', '껍질의 수호: 매 전투 첫 공격이 절반이 된다.'],
      leo: ['사자자리', '포효: 6글자 이상 단어는 +8.'],
      virgo: ['처녀자리', '전투마다 한 번, 별자리를 누른 뒤 타일을 누르면 새 글자로 정화된다.'],
      libra: ['천칭자리', '천칭: 모음과 자음이 균형을 이룬 단어는 +10.'],
      scorpio: ['전갈자리', '독은 단어마다 쌓이고, 시전 후마다 짐승을 갉아먹는다.'],
      sagittarius: ['궁수자리', '메긴 화살: SCRY가 짐승에게 6 피해를 준다.'],
      capricorn: ['염소자리', '등반: 이번 판에 쓰러뜨린 짐승 하나당 단어가 +1.'],
      aquarius: ['물병자리', '전투마다 한 번, 체력이 절반 아래로 떨어지면 물이 부어져 8 회복.'],
      pisces: ['물고기자리', '깊은 해류: 공격까지 한 번 남았을 때 엮은 단어는 +30%.'],
    },
    sig: {
      quill: ['잉걸불 깃펜', '모든 단어의 피해 +4.'],
      choir: ['모음 성가대', '모음 하나마다 +2.'],
      runes: ['강의 룬', 'S·R·E·T가 각각 +2.'],
      salve: ['달의 연고', '5글자 이상 단어가 4를 회복.'],
      aegis: ['여명의 방패', '최대 체력 +20, 즉시 회복.'],
      first: ['첫 별빛', '전투마다 첫 단어가 2배.'],
      hush: ['고요한 모래시계', '짐승의 일격이 한 번 늦어진다.'],
      comet: ['혜성의 꼬리', 'SCRY가 일격을 앞당기지 않는다.'],
      shield: ['은빛 방패', '전투마다 첫 일격을 막는다.'],
      leech: ['이슬 마시는 자', '단어마다 1을 회복.'],
      longbow: ['별의 장궁', '6글자 이상 단어에 +12.'],
      gilded: ['금빛 여명', '전투가 금빛 타일과 함께 시작.'],
      forge: ['별의 대장간', '벼려진 타일이 한 단계 높아진다.'],
      blood: ['핏빛 잉크', '단어 +25%. 짐승의 일격도 +25%.'],
      tome: ['속삭이는 마도서', '눈 ◉이 강한 단어를 알려준다. 전투당 1회.'],
      storm: ['폭풍 결속자', '세 번째 단어마다 두 번 타격.'],
      roots: ['지맥의 뿌리', '가진 인장 하나마다 단어 +2.'],
      ward: ['달의 수호', '짐승의 일격이 3 감소. 최소 1.'],
      echo: ['파멸의 메아리', '초과 피해가 다음 짐승에게 이어진다.'],
      feather: ['불사조 깃털', '한 번, 체력 1로 죽음을 견딘다.'],
      eclipse: ['일식', '짐승의 일격이 절반이 된다.'],
      nova: ['신성의 왕관', '7글자 이상 단어가 2배.'],
      verse: ['끝없는 시', '엮은 단어 하나마다 +1.'],
      meteor: ['유성의 심장', '짐승을 쓰러뜨리면 체력이 가득 찬다.'],
    },
  },
  zh: {
    rotate: '请竖屏游玩',
    title: 'STARSPELL',
    tagline: '编织词语 · 击落星兽',
    campaign: '战役', campaignSub: '四幕 · 一整夜',
    act1: '第一幕 · 草原之空', act2: '第二幕 · 深沉之夜',
    act3: '第三幕 · 黎明之冠', act4: '第四幕 · 无尽狩猎',
    tBoss: '首领', tElite: '精英',
    beast: {
      vulpes: '余烬之狐', lepus: '月光之兔', serpens: '潮汐巨蛇',
      delphinus: '星光海豚', columba: '信使白鸽', lacerta: '之字蜥蜴',
      cygnus: '风渡天鹅', pavo: '遮面孔雀', cancer: '幽暗之蟹',
      corvus: '空洞乌鸦', ursa: '寒冬之熊', aranea: '丝绸寡妇',
      aquila: '雷霆之鹰', lupus: '饥星之狼', monoceros: '琉璃独角兽',
      cassiopeia: '虚荣女王', cetus: '沉没的海怪', orion: '缚星猎人',
      strix: '虚空之枭', leo: '威严雄狮', taurus: '暴风眼公牛',
      scorpius: '猩红毒刺', draco: '噬星者', phoenix: '初焰',
      centaurus: '长子半人马', sagittarius: '天顶射手',
    },
    cont: '继续', fightN: '第 %1 战，共 5 战',
    quick: '快速游戏', quickSub: '五头星兽，然后是食星者',
    daily: '每日狩猎', dailyOpen: '同一片星空，人人共享 · 剩余%1',
    dailyDone: '今日: %1 · 距下一片星空%2', cdHM: '%1小时%2分', cdH: '%1小时', cdM: '%1分',
    board: '排行榜', profile: '个人资料',
    versus: '⚔ 对战 ⚔', versusSub: '星空下的决斗',
    endWin: '星空归于寂静', endWinSub: '星兽尽数陨落 · 今夜属于你',
    endLose: '星辰将你收回', endLoseSub: '攀升到此为止',
    stScore: '得分', stBest: '最佳 %1', newBest: '✦ 新纪录! ✦',
    stBeasts: '击落星兽', stWords: '编织词语', stLetters: '施放字母',
    stFinest: '最佳词语', stBigHit: '最强一击', stTime: '用时', stSigils: '持有印记',
    newRun: '再来一局', tryAgain: '重新挑战', home: '主页',
    shareBtn: '✶ 分享今日狩猎', shareCopied: '✶ 已复制 · 去炫耀吧', shareFail: '✶ 复制失败',
    sigilHead: '— 选择印记 —', vsSigilHead: '— 印记自荐 —',
    rarityRare: '稀有', rarityLegendary: '传说',
    cdMS: '%1分%2秒', cdS: '%1秒', cdD: '%1天', cdDH: '%1天%2小时',
    lbTitle: '今夜之最', lbDaily: '每日', lbWeekly: '每周',
    lbNewSky: '距新天空%1', lbWeekEnds: '本周结束还有%1',
    lbLoading: '正在问询星辰…', lbEmpty: '尚无狩猎记录 · 做第一人',
    lbYou: '你', lbYouRank: '你的名次: 第%1名 / 共%2人',
    lbLocal: '本地排行 · 无法连接更广的星空',
    dpOneSky: '同一片星空，人人共享', dpAwait: '今日的天空在等你',
    dpPlayed: '今日狩猎: %1', dpStreak: '连续狩猎%1天',
    dpPlay: '开始狩猎', dpAgain: '再次狩猎', dpTop: '今日之最',
    newCamp: '新战役', newCampSub: '重新开始漫漫长夜',
    mapTitle: '战役星图', mapHint: '点击发光的星座进入战斗', mapDest: '旅途终点',
    abandonTitle: '放弃这次攀登？', abandonBody: '你的存档（%1 · 第 %2 战）将消散于黑暗',
    abandonYes: '放弃', abandonNo: '继续攀登',
    zpTitle: '选择你的星座', zpSub: '生于同一片星空 · 星座塑造攀登',
    zpBegin: '开始攀登', zpSkip: '无星座攀登 · 经典模式',
    zpPurify: '点击一块字牌以净化', zShell: '甲壳撑住了',
    rating: '星辰评级', rVeilRow: '对他人隐藏我的评级', rVeiled: '已隐藏', rShown: '公开',
    rHiddenCard: '隐于星光之中', rYourVeil: '他人看不到你的评级',
    rt0: '星尘', rt1: '余烬之星', rt2: '新升之星', rt3: '鎏金之星',
    rt4: '新星', rt5: '超新星', rt6: '天穹之冠',
    zod: {
      aries: ['白羊', '每场战斗开场猛撞：星兽受到8点伤害。'],
      taurus: ['金牛', '金牛坚忍：攀登开始时生命上限+15。'],
      gemini: ['双子', '孪生字母：同一字母用两次的词+10。'],
      cancer: ['巨蟹', '甲壳护体：每场战斗的第一击减半。'],
      leo: ['狮子', '狮吼：6个字母以上的词+8。'],
      virgo: ['室女', '每场战斗一次，点击星座再点击字牌，将其净化为新字母。'],
      libra: ['天秤', '天秤：元音与辅音均衡的词+10。'],
      scorpio: ['天蝎', '毒素随词累积，每次施放后侵蚀星兽。'],
      sagittarius: ['人马', '搭弦之箭：SCRY同时对星兽造成6点伤害。'],
      capricorn: ['摩羯', '攀登：本局每击倒一头星兽，词伤+1。'],
      aquarius: ['宝瓶', '每场战斗一次，生命跌破一半时倾下清泉：回复8。'],
      pisces: ['双鱼', '深流：距离攻击仅剩一次施放时织出的词+30%。'],
    },
    sig: {
      quill: ['烬火羽笔', '每个词语伤害+4。'],
      choir: ['元音颂歌', '每个元音+2。'],
      runes: ['河之符文', 'S、R、E、T各+2。'],
      salve: ['月之膏', '5字母以上的词语回复4点。'],
      aegis: ['黎明神盾', '生命上限+20，立即治愈。'],
      first: ['初光', '每场战斗的第一个词语双倍。'],
      hush: ['静默沙漏', '星兽的攻击推迟一次。'],
      comet: ['彗星之尾', 'SCRY不再加速攻击。'],
      shield: ['白银之盾', '格挡每场战斗的第一击。'],
      leech: ['饮露者', '每个词语回复1点。'],
      longbow: ['星辰长弓', '6字母以上的词语+12。'],
      gilded: ['鎏金黎明', '每场战斗以一枚鎏金字块开局。'],
      forge: ['星之熔炉', '锻造的字块再升一阶。'],
      blood: ['血墨', '词语+25%。星兽攻击也+25%。'],
      tome: ['低语法典', '之眼◉揭示一个强力词语，每场战斗一次。'],
      storm: ['缚风暴者', '每第三个词语攻击两次。'],
      roots: ['地脉之根', '每持有一枚印记，词语+2。'],
      ward: ['月之守护', '星兽攻击减少3点，至少为1。'],
      echo: ['湮灭回响', '溢出伤害殃及下一头星兽。'],
      feather: ['凤凰之羽', '每局一次，以1点生命逃过死亡。'],
      eclipse: ['日蚀', '星兽攻击减半。'],
      nova: ['新星之冠', '7字母以上的词语双倍。'],
      verse: ['无尽之诗', '本局每编织一个词语，伤害+1。'],
      meteor: ['陨星之心', '击落星兽后生命全满。'],
    },
  },
  hi: {
    rotate: 'खेलने के लिए फ़ोन को सीधा करें',
    title: 'STARSPELL',
    tagline: 'शब्द बुनो · तारा-दानवों को हराओ',
    campaign: 'अभियान', campaignSub: 'चार अंक · एक लंबी रात',
    act1: 'अंक I · घास के मैदान का आकाश', act2: 'अंक II · गहरी रात',
    act3: 'अंक III · भोर का मुकुट', act4: 'अंक IV · अनंत शिकार',
    tBoss: 'बॉस', tElite: 'विशिष्ट',
    beast: {
      vulpes: 'अंगारों की लोमड़ी', lepus: 'चाँदनी का खरगोश', serpens: 'ज्वार का सर्प',
      delphinus: 'तारों की डॉल्फ़िन', columba: 'दूत कबूतर', lacerta: 'टेढ़ी छिपकली',
      cygnus: 'हवाओं का हंस', pavo: 'घूँघट वाला मोर', cancer: 'अंधकार का केकड़ा',
      corvus: 'खोखला कौआ', ursa: 'सर्दियों का भालू', aranea: 'रेशम की विधवा',
      aquila: 'गरज का बाज़', lupus: 'तारों का भूखा भेड़िया', monoceros: 'काँच का एकश्रृंगी',
      cassiopeia: 'घमंडी रानी', cetus: 'डूबा हुआ समुद्री दानव', orion: 'तारों से बंधा शिकारी',
      strix: 'शून्य का उल्लू', leo: 'प्रभुता का सिंह', taurus: 'तूफ़ानी आँखों वाला बैल',
      scorpius: 'गहरा लाल डंक', draco: 'तारा-भक्षक', phoenix: 'पहली ज्वाला',
      centaurus: 'ज्येष्ठ सेंटौर', sagittarius: 'शीर्ष का धनुर्धर',
    },
    cont: 'जारी रखें', fightN: 'लड़ाई %1 / 5',
    quick: 'त्वरित खेल', quickSub: 'पाँच दानव, फिर तारा-भक्षक',
    daily: 'दैनिक शिकार', dailyOpen: 'एक आकाश, सबका साझा · %1 शेष',
    dailyDone: 'आज: %1 · अगला आकाश %2 में', cdHM: '%1 घं %2 मि', cdH: '%1 घं', cdM: '%1 मि',
    board: 'लीडरबोर्ड', profile: 'प्रोफ़ाइल',
    versus: '⚔ वर्सस ⚔', versusSub: 'तारों तले द्वंद्व',
    endWin: 'आकाश शांत है', endWinSub: 'सारे तारा-दानव गिर चुके · यह रात तुम्हारी है',
    endLose: 'तारों ने तुम्हें ले लिया', endLoseSub: 'चढ़ाई यहीं समाप्त होती है',
    stScore: 'स्कोर', stBest: 'सर्वश्रेष्ठ %1', newBest: '✦ नया रिकॉर्ड! ✦',
    stBeasts: 'दानव हराए', stWords: 'शब्द बुने', stLetters: 'अक्षर चले',
    stFinest: 'श्रेष्ठ शब्द', stBigHit: 'सबसे बड़ा वार', stTime: 'खेल अवधि', stSigils: 'मुद्राएँ',
    newRun: 'नया खेल', tryAgain: 'फिर से', home: 'होम',
    shareBtn: '✶ आज का शिकार साझा करें', shareCopied: '✶ कॉपी हो गया · शेखी बघारें', shareFail: '✶ कॉपी विफल',
    sigilHead: '— एक मुद्रा चुनो —', vsSigilHead: '— एक मुद्रा स्वयं आई है —',
    rarityRare: 'दुर्लभ', rarityLegendary: 'पौराणिक',
    cdMS: '%1 मि %2 से', cdS: '%1 से', cdD: '%1 दिन', cdDH: '%1 दिन %2 घं',
    lbTitle: 'रात के सर्वश्रेष्ठ', lbDaily: 'दैनिक', lbWeekly: 'साप्ताहिक',
    lbNewSky: 'नया आकाश %1 में', lbWeekEnds: 'सप्ताह %1 में समाप्त',
    lbLoading: 'सितारों से पूछ रहे हैं…', lbEmpty: 'अभी कोई शिकार दर्ज नहीं — पहले बनो',
    lbYou: 'आप', lbYouRank: 'आपका स्थान: #%1 / %2',
    lbLocal: 'स्थानीय सूची — विस्तृत आकाश पहुँच से बाहर',
    dpOneSky: 'एक आकाश, सबका साझा', dpAwait: 'आज का आकाश आपकी प्रतीक्षा में है',
    dpPlayed: 'आज का शिकार: %1', dpStreak: 'लगातार %1 दिन शिकार',
    dpPlay: 'शिकार शुरू करें', dpAgain: 'फिर से शिकार', dpTop: 'आज के सर्वश्रेष्ठ',
    newCamp: 'नया अभियान', newCampSub: 'लंबी रात फिर से शुरू करें',
    mapTitle: 'अभियान का आकाश', mapHint: 'लड़ाई में उतरने के लिए चमकते तारामंडल को छुएँ', mapDest: 'यात्रा का अंत',
    abandonTitle: 'चढ़ाई छोड़ दें?', abandonBody: 'आपका पड़ाव — %1, लड़ाई %2 — अंधेरे में खो जाएगा',
    abandonYes: 'छोड़ें', abandonNo: 'चढ़ते रहें',
    zpTitle: 'अपनी राशि चुनो', zpSub: 'एक ही आकाश के नीचे जन्मे · हर राशि चढ़ाई बदलती है',
    zpBegin: 'चढ़ाई शुरू करें', zpSkip: 'बिना राशि चढ़ें · क्लासिक',
    zpPurify: 'शुद्ध करने के लिए एक टाइल छुएँ', zShell: 'कवच ने थाम लिया',
    rating: 'तारा रेटिंग', rVeilRow: 'मेरी रेटिंग दूसरों से छिपाएँ', rVeiled: 'छिपी', rShown: 'दिखती',
    rHiddenCard: 'तारों की रोशनी में ओझल', rYourVeil: 'दूसरों को आपकी रेटिंग ओझल दिखती है',
    rt0: 'तारों की धूल', rt1: 'अंगार तारा', rt2: 'उदित तारा', rt3: 'स्वर्णिम तारा',
    rt4: 'नोवा', rt5: 'सुपरनोवा', rt6: 'आकाशीय मुकुट',
    zod: {
      aries: ['मेष', 'हर लड़ाई की शुरुआत टक्कर से: दानव को 8 क्षति।'],
      taurus: ['वृषभ', 'वृषभ डटा रहता है: चढ़ाई की शुरुआत में अधिकतम जीवन +15।'],
      gemini: ['मिथुन', 'जुड़वाँ अक्षर: एक ही अक्षर दो बार इस्तेमाल करने वाले शब्द +10।'],
      cancer: ['कर्क', 'कवच की रक्षा: हर लड़ाई का पहला वार आधा होता है।'],
      leo: ['सिंह', 'दहाड़: 6+ अक्षरों के शब्द +8।'],
      virgo: ['कन्या', 'हर लड़ाई में एक बार, अपनी राशि छूकर फिर एक टाइल छुएँ — वह नए अक्षर में शुद्ध हो जाएगी।'],
      libra: ['तुला', 'तुला: स्वर और व्यंजन के संतुलन वाले शब्द +10।'],
      scorpio: ['वृश्चिक', 'हर शब्द से विष बढ़ता है — हर वार के बाद दानव उसे झेलता है।'],
      sagittarius: ['धनु', 'चढ़ा हुआ तीर: SCRY दानव पर 6 क्षति भी करता है।'],
      capricorn: ['मकर', 'चढ़ाई: इस खेल में गिराए हर दानव पर शब्द +1।'],
      aquarius: ['कुंभ', 'हर लड़ाई में एक बार, आधे जीवन से नीचे गिरने पर जल बरसता है: 8 भरपाई।'],
      pisces: ['मीन', 'गहरी धारा: वार से एक कदम पहले बुने शब्द +30%।'],
    },
    sig: {
      quill: ['अंगार लेखनी', 'हर शब्द +4 क्षति करता है।'],
      choir: ['स्वर वृंद', 'हर स्वर +2 का होता है।'],
      runes: ['नदी की रूण', 'S, R, E और T प्रत्येक +2।'],
      salve: ['चंद्र लेप', '5+ अक्षर के शब्द 4 स्वास्थ्य देते हैं।'],
      aegis: ['उषा का कवच', '+20 अधिकतम स्वास्थ्य, अभी भरा।'],
      first: ['पहली किरण', 'हर लड़ाई का पहला शब्द दोगुना।'],
      hush: ['मौन घड़ी', 'दानव एक चाल देर से वार करते हैं।'],
      comet: ['धूमकेतु की लकीर', 'SCRY अब वार तेज़ नहीं करता।'],
      shield: ['रजत ढाल', 'हर लड़ाई का पहला वार रोकता है।'],
      leech: ['ओस पीने वाला', 'हर शब्द 1 स्वास्थ्य देता है।'],
      longbow: ['तारों का धनुष', '6+ अक्षर के शब्द +12 करते हैं।'],
      gilded: ['स्वर्णिम उषा', 'हर लड़ाई एक सुनहरी टाइल से शुरू।'],
      forge: ['तारा भट्ठी', 'गढ़ी टाइलें एक स्तर ऊँची आती हैं।'],
      blood: ['रक्त स्याही', 'तुम्हारे शब्द +25%। दानवों के वार +25%।'],
      tome: ['फुसफुसाती पोथी', 'आँख ◉ एक कड़ा शब्द दिखाती है, प्रति लड़ाई एक बार।'],
      storm: ['तूफ़ान-बंधक', 'हर तीसरा शब्द दो बार वार करता है।'],
      roots: ['भू-रेखा की जड़ें', 'हर धारण की मुद्रा पर शब्द +2।'],
      ward: ['चंद्र रक्षक', 'दानवों के वार 3 कम, 1 से नीचे कभी नहीं।'],
      echo: ['विनाश की गूँज', 'बची क्षति अगले दानव को लगती है।'],
      feather: ['फ़ीनिक्स पंख', 'प्रति खेल एक बार, 1 स्वास्थ्य पर मृत्यु से बचो।'],
      eclipse: ['ग्रहण', 'दानवों के वार केवल आधे लगते हैं।'],
      nova: ['नोवा का मुकुट', '7+ अक्षर के शब्द दोगुने।'],
      verse: ['अनंत छंद', 'इस खेल में बुने हर शब्द पर +1।'],
      meteor: ['उल्का का हृदय', 'दानव गिराने पर पूरा स्वास्थ्य।'],
    },
  },
  ar: {
    rotate: 'أدر هاتفك عموديًا للعب',
    title: 'STARSPELL',
    tagline: 'انسج الكلمات · واصرع وحوش النجوم',
    campaign: 'الحملة', campaignSub: 'أربعة فصول · ليلة واحدة طويلة',
    act1: 'الفصل الأول · سماء المرج', act2: 'الفصل الثاني · الليل العميق',
    act3: 'الفصل الثالث · تاج الفجر', act4: 'الفصل الرابع · الصيد الأبدي',
    tBoss: 'زعيم', tElite: 'نخبة',
    beast: {
      vulpes: 'ثعلب الجمر', lepus: 'أرنب ضوء القمر', serpens: 'أفعى المد',
      delphinus: 'دلفين النجوم', columba: 'حمامة البشارة', lacerta: 'السحلية المتعرجة',
      cygnus: 'بجعة الرياح', pavo: 'الطاووس المحجوب', cancer: 'سلطعون الظلام',
      corvus: 'الغراب الأجوف', ursa: 'دب الشتاء', aranea: 'أرملة الحرير',
      aquila: 'نسر الرعد', lupus: 'الذئب الجائع للنجوم', monoceros: 'وحيد القرن الزجاجي',
      cassiopeia: 'الملكة المغرورة', cetus: 'الحوت الغارق', orion: 'الصياد المقيد بالنجوم',
      strix: 'بومة الفراغ', leo: 'الأسد المتوَّج', taurus: 'الثور العاصف العينين',
      scorpius: 'اللسعة القرمزية', draco: 'آكل النجوم', phoenix: 'اللهب الأول',
      centaurus: 'القنطور البكر', sagittarius: 'رامي الذروة',
    },
    cont: 'متابعة', fightN: 'المعركة %1 من 5',
    quick: 'لعب سريع', quickSub: 'خمسة وحوش، ثم آكل النجوم',
    daily: 'صيد اليوم', dailyOpen: 'سماء واحدة يتشاركها الجميع · يتبقى %1',
    dailyDone: 'اليوم: %1 · السماء التالية بعد %2', cdHM: '%1 س %2 د', cdH: '%1 س', cdM: '%1 د',
    board: 'لوحة الصدارة', profile: 'الملف الشخصي',
    versus: '⚔ مبارزة ⚔', versusSub: 'تحت النجوم',
    endWin: 'سكنت السماء', endWinSub: 'سقطت كل وحوش النجوم · الليل لك',
    endLose: 'النجوم تستردّك', endLoseSub: 'ينتهي الصعود هنا',
    stScore: 'النقاط', stBest: 'الأفضل %1', newBest: '✦ رقم قياسي جديد! ✦',
    stBeasts: 'وحوش صُرعت', stWords: 'كلمات نُسجت', stLetters: 'حروف أُلقيت',
    stFinest: 'أجمل كلمة', stBigHit: 'أقوى ضربة', stTime: 'مدة الجولة', stSigils: 'الأختام',
    newRun: 'جولة جديدة', tryAgain: 'حاول مجددًا', home: 'الرئيسية',
    shareBtn: '✶ شارك صيد اليوم', shareCopied: '✶ تم النسخ · تباهَ به', shareFail: '✶ فشل النسخ',
    sigilHead: '— اختر ختمًا —', vsSigilHead: '— ختمٌ يعرض نفسه —',
    rarityRare: 'نادر', rarityLegendary: 'أسطوري',
    cdMS: '%1 د %2 ث', cdS: '%1 ث', cdD: '%1 يوم', cdDH: '%1 يوم %2 س',
    lbTitle: 'نخبة الليل', lbDaily: 'اليومية', lbWeekly: 'الأسبوعية',
    lbNewSky: 'سماء جديدة بعد %1', lbWeekEnds: 'ينتهي الأسبوع بعد %1',
    lbLoading: 'نستشير النجوم…', lbEmpty: 'لا صيد مسجّل بعد — كن الأول',
    lbYou: 'أنت', lbYouRank: 'مركزك: %1 من %2',
    lbLocal: 'ترتيب محلي — السماء الأوسع بعيدة المنال',
    dpOneSky: 'سماء واحدة يتشاركها الجميع', dpAwait: 'سماء اليوم بانتظارك',
    dpPlayed: 'صيدك اليوم: %1', dpStreak: 'صيد متواصل: %1 أيام',
    dpPlay: 'ابدأ الصيد', dpAgain: 'صِد مجددًا', dpTop: 'نخبة اليوم',
    newCamp: 'حملة جديدة', newCampSub: 'ابدأ الليل الطويل من جديد',
    mapTitle: 'سماء الحملة', mapHint: 'المس الكوكبة المتوهجة لتدخل المعركة', mapDest: 'نهاية الرحلة',
    abandonTitle: 'أتتخلى عن الصعود؟', abandonBody: 'نقطة حفظك — %1، المعركة %2 — ستتلاشى في الظلام',
    abandonYes: 'تخلَّ', abandonNo: 'واصل الصعود',
    zpTitle: 'اختر برجك', zpSub: 'وُلدنا تحت سماء واحدة · كل برج يغيّر الصعود',
    zpBegin: 'ابدأ الصعود', zpSkip: 'اصعد بلا برج · الصعود الكلاسيكي',
    zpPurify: 'المس بلاطة لتطهيرها', zShell: 'صمدت الصدفة',
    rating: 'تصنيف النجوم', rVeilRow: 'إخفاء تصنيفي عن الآخرين', rVeiled: 'محجوب', rShown: 'ظاهر',
    rHiddenCard: 'محجوب في ضوء النجوم', rYourVeil: 'يرى الآخرون تصنيفك محجوبًا',
    rt0: 'غبار النجوم', rt1: 'نجم الجمر', rt2: 'نجم صاعد', rt3: 'نجم مذهّب',
    rt4: 'مستعر', rt5: 'مستعر أعظم', rt6: 'التاج السماوي',
    zod: {
      aries: ['الحمل', 'تفتتح كل معركة بنطحة: يتلقى الوحش 8.'],
      taurus: ['الثور', 'الثور يصمد: +15 للصحة القصوى عند بدء الصعود.'],
      gemini: ['التوأمان', 'حروف توأم: الكلمات التي تستخدم الحرف نفسه مرتين تزيد +10.'],
      cancer: ['السرطان', 'الصدفة تصمد: أول ضربة في كل معركة تُخفَّض إلى النصف.'],
      leo: ['الأسد', 'الزئير: كلمات من 6 حروف فأكثر تزيد +8.'],
      virgo: ['العذراء', 'مرة في كل معركة، المس برجك ثم بلاطة لتطهيرها إلى حرف جديد.'],
      libra: ['الميزان', 'الميزان: الكلمات المتوازنة بين الصوائت والصوامت تزيد +10.'],
      scorpio: ['العقرب', 'السم يتراكم مع كل كلمة — ويعانيه الوحش بعد كل إلقاء.'],
      sagittarius: ['الرامي', 'السهم المُشرَع: SCRY يضرب الوحش أيضًا بمقدار 6.'],
      capricorn: ['الجدي', 'الصعود: تزيد الكلمات +1 عن كل وحش صُرع في هذه الجولة.'],
      aquarius: ['حامل الماء', 'مرة في كل معركة، إذا هبطت تحت نصف الصحة تنسكب المياه: شفاء 8.'],
      pisces: ['السمكتان', 'التيار العميق: الكلمات المنسوجة قبل الضربة بإلقاء واحد تزيد +30%.'],
    },
    sig: {
      quill: ['ريشة الجمر', 'كل كلمة تُحدث +4 ضررًا.'],
      choir: ['جوقة العلّة', 'كل حرف علة يساوي +2.'],
      runes: ['رونات النهر', 'S وR وE وT تساوي +2 لكل منها.'],
      salve: ['بلسم القمر', 'الكلمات من 5 أحرف فأكثر تشفيك 4.'],
      aegis: ['درع الفجر', '+20 صحة قصوى، تُشفى الآن.'],
      first: ['الضوء الأول', 'كلمتك الأولى في كل معركة تضرب ضعفين.'],
      hush: ['ساعة الصمت', 'تضرب الوحوش بعد رمية إضافية.'],
      comet: ['ذيل المذنّب', 'لم يعد SCRY يعجّل الضربة.'],
      shield: ['الدرع الفضي', 'يصدّ أول ضربة في كل معركة.'],
      leech: ['شارب الندى', 'كل كلمة تشفيك 1.'],
      longbow: ['قوس النجوم', 'الكلمات من 6 أحرف فأكثر +12.'],
      gilded: ['الفجر الذهبي', 'تبدأ كل معركة ببلاطة ذهبية.'],
      forge: ['مصهر النجوم', 'البلاطات المسبوكة تأتي أعلى بدرجة.'],
      blood: ['حبر الدم', 'كلماتك +25%. وضربات الوحوش +25%.'],
      tome: ['السِّفر الهامس', 'العين ◉ تكشف كلمة قوية، مرة كل معركة.'],
      storm: ['قيّاد العواصف', 'كل كلمة ثالثة تضرب مرتين.'],
      roots: ['جذور خطوط الطاقة', 'الكلمات +2 عن كل ختم تحمله.'],
      ward: ['حِمى القمر', 'ضربات الوحوش أقل بـ3، ولا تقل عن 1.'],
      echo: ['صدى الخراب', 'الضرر الفائض يجرح الوحش التالي.'],
      feather: ['ريشة العنقاء', 'مرة كل جولة، تنجو من الموت بصحة 1.'],
      eclipse: ['الكسوف', 'ضربات الوحوش نصفها فقط.'],
      nova: ['تاج المستعرات', 'الكلمات من 7 أحرف فأكثر تضرب ضعفين.'],
      verse: ['البيت الذي لا ينتهي', 'الكلمات +1 عن كل كلمة نسجتها هذه الجولة.'],
      meteor: ['قلب النيزك', 'صرع وحش يعيد لك كل صحتك.'],
    },
  },
};

// native names, for the language sheet — never translated
const SS_LANGS = {
  en: 'English', es: 'Español', fr: 'Français', pt: 'Português', de: 'Deutsch',
  ja: '日本語', ko: '한국어', zh: '中文', hi: 'हिन्दी', ar: 'العربية',
};

const SS_LANG = (() => {
  const qs = new URLSearchParams(location.search);
  const q = (qs.get('lang') || '').toLowerCase();
  if (SS_STR[q]) { try { localStorage.setItem('beta3.lang', q); } catch (e) { } return q; }
  let saved = null;
  try { saved = localStorage.getItem('beta3.lang'); } catch (e) { }
  if (SS_STR[saved]) return saved;
  const nav = ((navigator.language || 'en').slice(0, 2)).toLowerCase();
  return SS_STR[nav] ? nav : 'en';
})();

function SS_T(key) {
  let s = (SS_STR[SS_LANG] && SS_STR[SS_LANG][key]) || SS_STR.en[key] || key;
  for (let i = 1; i < arguments.length; i++) s = s.replace('%' + i, arguments[i]);
  return s;
}

// Localized name/desc for a sigil def. English lives in data.js (the canonical
// copy); other languages carry a `sig` map of id → [name, desc] and fall back
// per-sigil so a partial map ships gracefully.
function SS_SIG(s) {
  const m = (SS_STR[SS_LANG] && SS_STR[SS_LANG].sig) || {};
  const t = m[s.id];
  return t ? { name: t[0], desc: t[1] } : { name: s.name, desc: s.desc };
}

// Localized flavor title for a beast. English lives in data.js (the canonical
// copy); other languages carry a `beast` map of id → title with per-beast
// fallback. Latin constellation NAMES (VULPES, ORION…) are never translated.
function SS_BEAST_T(b) {
  const m = (SS_STR[SS_LANG] && SS_STR[SS_LANG].beast) || {};
  return m[b.id] || b.title;
}

// Localized title/desc for a zodiac sign. English lives in data.js (the
// canonical copy); other languages carry a `zod` map of id → [title, desc]
// with per-sign fallback. Latin sign NAMES (ARIES, LIBRA…) never translate.
function SS_ZOD(z) {
  const m = (SS_STR[SS_LANG] && SS_STR[SS_LANG].zod) || {};
  const t = m[z.id];
  return t ? { title: t[0], desc: t[1] } : { title: z.title, desc: z.desc };
}

// Act display name — acts carry a nameKey into the strings table.
function SS_ACT_N(act) { return SS_T(act.nameKey); }

try { document.title = SS_T('title'); } catch (e) { }
